bible_loader.load_commentary(14, 13, {
  "1": {
    "John Trapp": "Now in the eighteenth year. ] See #1Ki 15:1,2 .\nVer.\n1. Now in the eighteenth year.] See #1Ki 15:1,"
  },
  "2": {
    "John Trapp": "His mother\u2019s name was Michaiah. ] Alias Maachah. See on #2Ch 11:21,22 . And there was war between Abijah and Jeroboam. ] Like as there had been between Rehoboam and Jeroboam. So the dissension betwixt England and Scotland, which consumed more Christian blood, wrought more spoil and destruction, and continued longer, than ever quarrel we read of did between any two people in the world.\nVer.\n2. Ver.\n2. His mother\u2019s name was Michaiah.] Alias Maachah. See on #2Ch 11:21,"
  },
  "3": {
    "John Trapp": "And Abijah set the battle in array. ] Josephus saith, that Jeroboam began the war, in hope to vanquish young Abijah; but Sethus Calvisius saith, that Abijah, rashly offering war to Jeroboam, yet obtained the victory, when he called upon God. Even four hundred thousand, &amp;c. ] Yet was this great army out numbered by Jeroboam\u2019s; so was Asa\u2019s six hundred thousand by Zera\u2019s million. Huge were the armies of the Jews, that small people in comparison: five hundred thousand\u2014not fifty thousand only, as Ruffinus ill translateth Josephus\u2014were slain on one side; the greatest number that ever we read of slain in any battle.\nVer.\n3. And Abijah set the battle in array.] Josephus saith, that Jeroboam began the war, in hope to vanquish young Abijah; but Sethus Calvisius saith, that Abijah, rashly offering war to Jeroboam, yet obtained the victory, when he called upon God. Even four hundred thousand, &c.] Yet was this great army out numbered by Jeroboam\u2019s; so was Asa\u2019s six hundred thousand by Zera\u2019s million. Huge were the armies of the Jews, that small people in comparison: five hundred thousand\u2014not fifty thousand only, as Ruffinus ill translateth Josephus\u2014were slain on one side; the greatest number that ever we read of slain in any battle.\nVer.\n3. Ver."
  },
  "4": {
    "John Trapp": "And Abijah stood upon mount Zemaraim. ] As Jotham likewise had done upon mount Gerizim. { #Jud 9:7 } It is probable that Abijah had, by his heralds or messengers, desired a parley: else he could not have delivered himself without danger.\nVer.\n4. And Abijah stood upon mount Zemaraim.] As Jotham [v_Jdg_9_7] likewise had done upon mount Gerizim `[place_Gerizim_Ref]`. {#Jud 9:7} It is probable that Abijah had, by his heralds or messengers, desired a parley: else he could not have delivered himself without danger.\nVer."
  },
  "5": {
    "John Trapp": "Ought ye not to know? ] q.d., How can ye be ignorant? and how dare you go against your knowledge? Is it not a grievous sin so to do By a covenant of salt, ] i.e., Perpetual and inviolable, solemn\u2014as with sacrifice\u2014and sure. See on #Nu 18:19 . That exposition of Sanchez is somewhat strange and far fetched: that God\u2019s covenant with the house of David `[char_David_Rut_4]` was conditional, and therefore to be taken with a grain of salt; viz., that they should have the kingdom for ever, if they kept touch with him, &amp;c.\nVer.\n5. Ought ye not to know?] q.d., How can ye be ignorant? and how dare you go against your knowledge? Is it not a grievous sin so to do By a covenant of salt, ] i.e., Perpetual and inviolable, solemn\u2014as [v_Num_18_19] with sacrifice\u2014and sure. See on #Nu 18:"
  },
  "6": {
    "John Trapp": "Yet Jeroboam the son of Nebat, the servant of Solomon `[char_Solomon_Ref]`. ] But such a servant, as being delicately brought up by him, and courteously dealt with, would needsly become his son at length, as #Pr 29:21 , rising up and rebelling against his lord, as he is justly charged, though God foretold that he should be king. { #1Ki 11:35 }\nVer.\n6. Yet Jeroboam the son of Nebat, the servant of Solomon `[char_Solomon_Ref]`.] But such a servant, as being delicately brought up by him, and courteously dealt with, would needsly become his son at length, as [v_Pro_29_21] #Pr 29:21, rising up and rebelling against his lord, as he is justly charged, though God foretold that he should be king. {#1Ki 11:35}\nVer."
  },
  "7": {
    "John Trapp": "And there are gathered unto him vain men. ] Rachas brainless fellows, light and empty; yokeless also and masterless; men of no piety or common honesty. Such also were Catiline\u2019s comrades among the Romans. When Rehoboam was young. ] Not in age, but in experience, policy, and valour; he was imbellis et metculosus, hen-hearted, as we say, and\u2014as a young plant, not yet rooted\u2014easily shaken and swayed by the insolencies of his rebellious subjects. And could not withstand them. ] Thus he layeth the fault\u2014like a good child\u2014wholly upon his father; with whom, it is like, he was displeased for obeying the prophet Shemaiah, { #2Ch 11:4 } and not reducing his rebels at first, as he might have done, but for his folly and faint-heartedness, saith Abijah.\nVer.\n7. And there are gathered unto him vain men.] Rachas brainless fellows, light and empty; yokeless also and masterless; men of no piety or common honesty. Such also were Catiline\u2019s comrades among the Romans. When Rehoboam was young.] Not in age, but in experience, policy, and valour; he was imbellis et metculosus, hen-hearted, as we say, and\u2014as a young plant, not yet rooted\u2014easily shaken and swayed by the insolencies of his rebellious subjects. And could not withstand them.] Thus he layeth the fault\u2014like a good child\u2014wholly upon his father; with whom, it is like, he was displeased for obeying the prophet Shemaiah, {#2Ch 11:4} and not reducing his rebels at first, as he might have done, but for his folly and faint-heartedness, saith Abijah.\nVer."
  },
  "8": {
    "John Trapp": "To withstand the kingdom of the Lord. ] And so, giant-like, to fight against God. Is that ever like to do well? \"Do ye provoke the Lord to anger? are ye stronger than he?\" And there are with you golden calves. ] In the camp perhaps, as #1Ch 14:12 .\nVer.\n8. To withstand the kingdom of the Lord.] And so, giant- like, to fight against God. Is that ever like to do well? \"Do ye provoke the Lord to anger? are ye stronger than he?\" And there are with you golden calves.] In the camp perhaps, as #1Ch 14:"
  },
  "9": {
    "John Trapp": "Have you not cast out the priests of the Lord? ] Who should pray for you, and make atonement. So that whosoever cometh to consecrate himself. ] Heb., To fill his hand, sc., with sacrifices; or haply with bribes.\nVer.\n9. Have you not cast out the priests of the Lord?] Who should pray for you, and make atonement. So that whosoever cometh to consecrate himself.] Heb., To fill his hand, sc., with sacrifices; or haply with bribes.\nVer."
  },
  "10": {
    "John Trapp": "But as for us, the Lord is our God, &amp;c. ] Summa ratio est quae pro religione facit, saith Papinian. Abijah was none of the best, and yet pretendeth to a great deal of religion, and pleadeth hard for it; though he \"walked in all the sins of his father\" Rehoboam. { #1Ki 15:3 } Hypocrites want for no fair words. Some think that Abijah, when he went forth to battle, was indifferent good; but puffed up with his great victory, he fell away. Pellican holdeth that he was ever naught: only the worship of God was by him externally maintained and magnified; wherewith because God was well pleased, it being of his own ordaining, he now took part with him.\nVer.\n10. But as for us, the Lord is our God, &c.] Summa ratio est quae pro religione facit, saith Papinian. Abijah was none of the best, and yet pretendeth to a great deal of religion, and pleadeth hard for it; though he \"walked in all the sins of his father\" Rehoboam. {#1Ki 15:3} Hypocrites want for no fair words. Some think that Abijah, when he went forth to battle, was indifferent good; but puffed up with his great victory, he fell away. Pellican holdeth that he was ever naught: only the worship of God was by him externally maintained and magnified; wherewith because God was well pleased, it being of his own ordaining, he now took part with him.\nVer."
  },
  "11": {
    "John Trapp": "Upon the pure table and the candlestick of gold. ] Either it is table, for tables, as #1Ki 7:48 ; or else this king, who little minded such matters, thought there had been but one such table and candlestick in the temple, as of old in the tabernacle. { a } { a } Lavat.\nVer.\n11. Upon the pure table and the candlestick of gold.] Either it is table, for tables, as #1Ki 7:48; or else this king, who little minded such matters, thought there had been but one such table and candlestick in the temple, as of old in the tabernacle. {a} {a} Lavat.\nVer."
  },
  "12": {
    "John Trapp": "And, behold, God himself is with us. ] \u0395\u03c0\u03b9\u03c6\u03bf\u03c1\u03b1 , qua praecipua argumenta repetit: he is speaking his last to them, and therefore speaks thick. For our captain. ] Deus est dux; he is in the head of us, who is himself a whole army. Fight ye not against the Lord. ] A good motion, had it come from a better mouth.\nVer.\n12. Ver.\n12. And, behold, God himself is with us.] \u0395\u03c0\u03b9\u03c6\u03bf\u03c1\u03b1, qua praecipua argumenta repetit: he is speaking his last to them, and therefore speaks thick. For our captain.] Deus est dux; he is in the head of us, who is himself a whole army. Fight ye not against the Lord.] A good motion, had it come from a better mouth.\nVer."
  },
  "13": {
    "John Trapp": "But Jeroboam caused an ambushment. ] While Abijah was thus haranguing and persuading the people to lay down their arms, and to return to their obedience, Jeroboam closely divided his army, causing one part to wheel about, and to come upon their backs, and the other to set upon them before, thinking so to surprise them unawares.\nVer.\n13. But Jeroboam caused an ambushment.] While Abijah was thus haranguing and persuading the people to lay down their arms, and to return to their obedience, Jeroboam closely divided his army, causing one part to wheel about, and to come upon their backs, and the other to set upon them before, thinking so to surprise them unawares.\nVer."
  },
  "14": {
    "John Trapp": "And when Judah looked back. ] For till then, they suspected not any such treachery. And they cried unto the Lord. ] Inter arma silent leges: preces non sileant. Prayers are the soldier\u2019s surest great ordnance.\nVer.\n14. And when Judah looked back.] For till then, they suspected not any such treachery. And they cried unto the Lord.] Inter arma silent leges: preces non sileant. Prayers are the soldier\u2019s surest great ordnance.\nVer."
  },
  "15": {
    "John Trapp": "Then the men of Judah gave a shout. ] Initio pugnae, de more antiquorum. Together with their loud outcries\u2014first for fear perhaps, afterwards to affright their enemies\u2014prayers went up to God. And see the happy effect thereof. God smote Jeroboam. ] With a panic terror, with furies in his own conscience, and with some grievous disease, whereof, Nabal-like, at length he died. { #2Ch 13:20 }\nVer.\n15. Then the men of Judah gave a shout.] Initio pugnae, de more antiquorum. Together with their loud outcries\u2014first for fear perhaps, afterwards to affright their enemies\u2014prayers went up to God. And see the happy effect thereof. God smote Jeroboam.] With a panic terror, with furies in his own conscience, and with some grievous disease, whereof, Nabal-like, at length he died. {#2Ch 13:20}\nVer."
  },
  "17": {
    "John Trapp": "So there fell down slain of Israel five hundred thousand. ] A monstrous and matchless slaughter, far beyond that of Tamerlane when he took Bajazet, or Aetius, the Roman prefect, when he fought with Attilas and his Huns in the fields of Catalaunia, where were slain on both sides one hundred and sixty-five thousand. See on #2Ch 13:3 .\nVer.\n17. So there fell down slain of Israel five hundred thousand.] A monstrous and matchless slaughter, far beyond that of Tamerlane when he took Bajazet, or Aetius, the Roman prefect, when he fought with Attilas and his Huns in the fields of Catalaunia, where were slain on both sides one hundred and sixty- five thousand. See on #2Ch 13:"
  },
  "18": {
    "John Trapp": "Because they relied upon the Lord. ] Deo confisi nunquam confusi. Trust in God never miscarrieth.\nVer.\n18. Because they relied upon the Lord.] Deo confisi nunquam confusi. Trust in God never miscarrieth.\nVer."
  },
  "19": {
    "John Trapp": "And took cities from him, Bethel. ] Where stood one of the golden calves, secured, haply, by the inhabitants before the enemy came, as idolaters\u2019 main care is for their idols.\nVer.\n19. That exposition of Sanchez is somewhat strange and far fetched: that God\u2019s covenant with the house of David `[char_David_Rut_4]` was conditional, and therefore to be taken with a grain of salt; viz., that they should have the kingdom for ever, if they kept touch with him, &c.\nVer.\n19. And took cities from him, Bethel.] Where stood one of the golden calves, secured, haply, by the inhabitants before the enemy came, as idolaters\u2019 main care is for their idols.\nVer."
  },
  "20": {
    "John Trapp": "And the Lord struck him. ] That is, Jeroboam (see on #2Ch 13:15 ); not Abijah, as the Hebrews sense the text, saying that God therefore struck him, because, when he took Bethel, he destroyed not the idol there, but kept it and worshipped it. A fable.\nVer.\n20. And the Lord struck him.] That is, Jeroboam (see on #2Ch 13:15); not Abijah, as the Hebrews sense the text, saying that God therefore struck him, because, when he took Bethel, he destroyed not the idol there, but kept it and worshipped it. A fable.\nVer."
  },
  "21": {
    "John Trapp": "And married fourteen wives. ] Some of them before he came to the kingdom. Junius well readeth it, He had married fourteen wives. This was against an express law, { #De 17:17 } besides the utter unlawfulness of polygamy, whereof before. But many great men make little of laws; it is plea sufficient for their offence that it is\u2014 \u201c facinus maioris abollae. \u201d\nVer.\n21. And married fourteen wives.] Some of them before he came to the kingdom. Junius well readeth it, He had married [v_Deu_17_17] fourteen wives. This was against an express law, {#De 17:17} besides the utter unlawfulness of polygamy, whereof before. But many great men make little of laws; it is plea sufficient for their offence that it is\u2014 \u201c facinus maioris abollae.\u201d\nVer."
  },
  "22": {
    "John Trapp": "And his ways. ] Which were not good. Prodit se libidinosum fuisse; by his many wives he appeareth to have been libidinous, as was also his father. And his sayings. ] His oration, { #2Ch 13:5 , &amp;c. } which is very artificial, and other apophthegms, as being Solomon `[char_Solomon_Ref]`\u2019s grandchild, &amp;c.\n22. And there was war between Abijah and Jeroboam.] Like as there had been between Rehoboam and Jeroboam. So the dissension betwixt England and Scotland, which consumed more Christian blood, wrought more spoil and destruction, and continued longer, than ever quarrel we read of did between any two people in the world.\nVer.\n22. And his ways.] Which were not good. Prodit se libidinosum fuisse; by his many wives he appeareth to have been libidinous, as was also his father. And his sayings.] His oration, {#2Ch 13:5, &c.} which is very artificial, and other apophthegms, as being Solomon `[char_Solomon_Ref]`\u2019s grandchild, &c."
  }
});
