bible_loader.load_commentary(15, 32, {
  "1": {
    "Psalms": "Praise waiteth for thee, O God, in Sion, etc.] Who dwells in Sion, as Jarchi interprets it; and so the Targum; whose Shechinah, or glorious [v_Psa_76_2] Majesty, is in Sion; (see <197602>"
  },
  "116": {
    "Psalms": "Uphold me according unto thy word, etc.] In thy ways, that my footsteps slip not; in thine arms, and with the right hand of thy righteousness, from fainting and sinking under difficulties and discouragements, in trying circumstances; and from slipping and sliding out of the way of God; and from a total and final filling away, according to thy word of promise, that, as are the days of thy people, their strength shall be; and that thou wilt never leave them nor forsake them. The Targum is, \u201cuphold me in thy word;\u201d or by thy word, either essential or written; that I may live; meaning not corporeally, though none so live but whom the Lord upholds in life; but, spiritually, live by faith on Christ the Saviour, live comfortably on the word of promise, and live honourably, agreeably to the word of God, in all holy conversation and godliness; and let me not be ashamed of my hope: as men are, when they are disappointed or having and enjoying what they have been hoping and waiting for; but the grace of hope makes not ashamed, nor shall those who have it ever have any reason to be ashamed of it; since it is a good hope through grace; is an anchor of the soul, sure and steadfast; is upon a good foundation, Christ, and by which men are saved; and so may rejoice, in full hope of the glory of God they shall certainly enjoy.\nVer."
  },
  "117": {
    "Psalms": "Hold thou me up, and I shall be safe, etc.] As all are, and none but such, who are in the hands of Christ; enclosed in the arms of everlasting love, upheld with the right hand of Jehovah, supported by his promises and grace, surrounded by his power, sustained by his love, and preserved in Christ Jesus `[char_Jesus_Ref]`; and I will have respect unto thy statutes continually; for nothing can more strongly engage a constant regard unto them than a sense of divine love, and a view of safety and security in the arms of it; or better enable to keep them than fresh communications of grace and strength: being upheld, saints hold on and out to the end; they go from strength to strength, run and are not weary, walk and faint not; and, having a supply of the Spirit, walk on in the judgments of the Lord, and keep his statutes, and do them. Or, \u201cand I will rejoice\u201d f1686 in them, as Aben Ezra and Kimchi; or, \u201cemploy myself\u201d in them, as Jarchi. 1425\nVer."
  },
  "118": {
    "Psalms": "Thou hast trodden down all them that err from thy statutes, etc.] That wander from the way of the Lord\u2019s commandments; that deviate from his precepts, go astray constantly and wilfully; a people that err in their hearts, and with all their hearts. These the Lord treads down, as mire in the streets, as grapes in a winepress; which shows his abhorrence of them, his indignation at them, and how easily they are subdued under him; for their deceit [is] falsehood: or, \u201ctheir hypocrisy [is] a lie\u201d f1687: the appearance they make is a false one; they appear outwardly righteous, but are inwardly wicked; have a form of godliness, but deny the power of it: or all their deceitful doctrines are lies in hypocrisy, though dressed up with all the art and cunning they are masters of; or all their subtle schemes to corrupt and subvert the true doctrines of the word are in vain and to no purpose.\nVer."
  },
  "119": {
    "Psalms": "Thou puttest away all the wicked of the earth [like] dross, etc.] Which is of no worth and value, useless and unprofitable; which is cast into the fire, and separated from the choice metal. This expresses the character and state of wicked men; who are of no account with God, are of no profit and advantage to him; nor to men, but harmful and pernicious; are cast into the fire of God\u2019s judgments here, and into everlasting burnings hereafter; and will be separated from the righteous, and have no part and lot with them: these seem to be hypocrites also, who have made a show of being gold and silver, when they were nothing but dross; and being reprobate silver, were rejected of God as such; therefore I love thy testimonies; which discover such persons when brought to be tried by them; and which require purity of heart and life, and caution against evil ways and evil men, and are a means of preserving from them.\nVer."
  },
  "120": {
    "Psalms": "My flesh trembleth for fear of thee, etc.] Not for fear of the wrath of God coming down upon himself, nor for fear of eternal damnation; but for fear of what was coming upon the wicked, for their sins and transgressions. The word f1688 used signifies such a dread and horror, which seizes a man to such a degree, that it makes the hair of his flesh to [v_Psa_119_53] stand up; as Jarchi and Kimchi observe; (see <19B953>\nVer."
  },
  "121": {
    "Psalms": "AIN. I have done judgment and justice, etc.] As king of Israel; [v_2Sa_8_15] which is the character given of him, (<100815>2 Samuel 8:15); and in which he [v_Jer_23_5] was a type of Christ, (<242305>Jeremiah 23:5 <230907>Isaiah `[char_Isaiah_Gen_26]` 9:7); and as a private person; which is everyone\u2019s duty, and every good man especially will be desirous of performing it: it is not indeed perfectly done by any, and therefore not to be trusted to; nor was it so done by David `[char_David_Rut_4]`; nor did he place his confidence in it; nor did he say this in a boasting way, but in defence of himself and his innocence against those who oppressed him with their calumnies, as appears from the next clause. The Syriac version takes it to be an address to God, and as describing him, \u201cO thou that doest judgment and justice!\u201d to whom the following petition is directed: leave me not to mine oppressors; David `[char_David_Rut_4]` had his oppressors, as all good men have, and power was on their side; but they could do no more, nor further exercise it, than as they were permitted by the Lord; for they had no power but what was given them from above; and he applies to God, and not men, for relief; and deprecates being given up to them, and left in their hands.\nVer."
  },
  "122": {
    "Psalms": "Be surety for thy servant for good, etc.] The psalmist was, in a like case with Hezekiah, oppressed; and therefore desires the Lord would [v_Psa_38_14] undertake for him, appear on his side, and defend him, (<193814>"
  }
});
