bible_loader.load_commentary(19, 86, {
  "2": {
    "Commentary Vol. 154": "I will be glad and rejoice in thee, etc.] Not in himself, in any attainments or works of his; not in his wisdom, riches, and strength, nor in his warlike exploits, but in the Lord; not in second causes, in horses and chariots, in armies, and in the courage and valour of men, but in God, as the author of deliverance, victory, and salvation; not in God only as the God of nature and providence, but as the God of all grace, and as his covenant God and Father; and because of the blessings of this covenant, as forgiveness of sin, a justifying righteousness, etc. for he rejoiced not in his own righteousness, but in the righteousness of Christ, as well as in his person, grace, and sacrifice; so the Chaldee paraphrase renders it, \u201cI will be glad and rejoice\u201d, \u00c6rmymb, \u201cin thy Word\u201d, the Logos, the essential Word of God, of whom there were many types, promises, and prophecies in the former dispensation; two words being here used express the greatness of this joy, and especially the latter word denotes a very vehement joy, a joy unspeakable and full of glory; such as arises from a sight of Christ the object, and which the psalmist had now in view; and this was not a carnal and worldly joy, but joy in the Holy Ghost; I will sing praise to thy name, O thou most High; that is, to the glory of his name, his being, and perfections, as displayed in his marvellous works, and in the revelation of his word, and especially in his son; and under the character of the \u201cmost high\u201d God, the supreme Being over all creatures, [v_Psa_7_17] angels and men; (see <190717>"
  },
  "1": {
    "Commentary Vol. 154": "Bow down thine ear, O Lord, hear me, etc.] This is spoken of God after the manner of men, who, when they listen and attentively hearken to what is said to them, stoop and bow the head, and incline the ear; and it denotes condescension in the Lord, who humbles himself as to look upon men, so to bow down the ear and hearken to them: this favour is granted to the saints, to whom he is a God hearing and answering prayer, and which [v_Heb_5_7] Christ, as man and Mediator, enjoyed; (see <580507>Hebrews 5:7 <431141>John `[char_John_Ref]` 11:41,42), for I am poor and needy; weak and feeble, destitute and distressed, and so wanted help and assistance; and which carries in it an argument or reason enforcing the above petition; for the Lord has a regard to the poor and [v_Psa_6_2] needy; (see <190602>"
  },
  "7": {
    "Commentary Vol. 154": "In the day of my trouble I will call upon thee, etc.] David `[char_David_Rut_4]` had his troubles, both inward and outward, before and after he came to the throne, in private and public life; and every good man has his troubles; and there are some particular times or days of trouble; which trouble arises from different causes; sometimes from themselves, their corruptions, the weakness of their grace, and the poor performance of their duties; sometimes from others; from the persecutions of the men of the world; from the wicked lives of profane sinners, and especially professors of religion, and from the spread of false doctrine; sometimes from Satan and his temptations; and sometimes from the more immediate hand of God in afflictions, and from the hidings of his face: these troubles do not last always; they are but for a day, for a particular time; and such a season is a fit one for prayer, and the Lord invites and encourages his people to call [v_Psa_50_15] upon him in prayer when this is the case, (<195015>"
  },
  "16": {
    "Commentary Vol. 154": "O turn unto me, and have mercy upon me, etc.] For it seems the Lord had turned away from him, and had hid his face, and withheld the manifestation of his grace and mercy from him, and had not yielded him the help and assistance he expected; and therefore entreats that he would turn again to him, and show him his face and favour, and be merciful to him: give thy strength unto thy servant; spiritual strength, strength in his soul, to exercise grace, perform duty, bear the cross, and stand up against all enemies, and hold out to the end: this is God\u2019s gift; and the psalmist pleads his relation to him as his servant, not merely by creation, but by grace; this is interpreted by the Jews of the King Messiah f1227: and save the son of thine handmaid; out of the hands of those that were [v_Psa_119_94] risen up against him; (see <19B994>"
  },
  "5": {
    "Commentary Vol. 155": "He hath given meat to them that fear him, etc.] Or a \u201cprey\u201d f1587, alluding to the spoil of the Egyptians; or to the manna; corporeal food, [v_Psa_34_9] daily bread, which they that fear him shall not want, (<193409>"
  },
  "6": {
    "Commentary Vol. 155": "The Lord preserveth the simple, etc.] Such as have but a small degree of understanding, either in things natural or spiritual, in comparison of others; babes, as the Septuagint, Vulgate Latin, Syriac, Arabic, and [v_Mat_11_25] Ethiopic versions render it, so in the Talmud f1612; (see <401125>Matthew 11:25). Such who are sensible of their lack of wisdom, and what they have they do not lean unto or trust in, but being sensible of their weakness commit themselves to the Lord; they are sincere and upright, harmless and inoffensive, artless and incautious, and so easily imposed upon by designing men; but the Lord preserves them, as from sin, from a total and final falling away by it, so from gross errors and heresies; he preserves them from the snares and pollutions of the world, and from the temptations of Satan, so as not to be overcome with them; he preserves them by his Spirit, power, and grace, safe to his kingdom and glory. I was brought low and he helped me; the psalmist returns to his own case, and gives an instance of the divine goodness in himself; he had been brought low by affliction of body, by distress of enemies, through want of the necessaries and conveniences of life; he had been brought low as to spiritual things, through the weakness of grace, the prevalence of corruption, the temptations of Satan, and the hidings of God\u2019s face; but the Lord helped him to bear up under all this; he put underneath his everlasting 1342 arms, and upheld him with the right hand of his righteousness; he helped him out of his low estate, and delivered him out of all his troubles, when none else could; when things were at the greatest extremity, and he in the utmost distress, just ready to go down into silence and dwell there, [v_Psa_94_17] (<199417>"
  }
});
