bible_loader.load_commentary(42, 40, {
  "19": {
    "Ruckman, Dr. Peter S_": "can be applied to Christ, or to the Jewish remnant, or to David `[char_David_Rut_4]` personally, or for that matter to Lester Roloff, Harlan Popov, Richard Wurmbrand, John `[char_John_Ref]` Huss, Martin Luther, Alex Dunlap, Jack Chick, Jerry Falwell, Jesse Helms, J. Edgar Hoover, Oliver North, or J. Frank Norris. There is nothing \u201cout of date\u201d about the Bible."
  },
  "20": {
    "Ruckman, Dr. Peter S_": "is self explanatory, as are\nverses 21 and 22. 1. \u201cMake haste.\u201d 2. \u201cMake haste to help me.\u201d 3. \u201cForsake me not.\u201d 4. \u201cBe not far from me.\u201d Notice that a saint can be sinning when he is on the right way trying to do right (vs. 20). Notice also that his sins are between him and God, and that he can be hated for right actions even while he is out of fellowship with God (vss. 19\u201320). These two tremendous New Testament doctrinal and practical truths escape the eyes of Kroll, Motyer, Dummelow, Ellicott, Jamieson, Fausset, Brown, Briggs, Davidson, and Keil, exactly as they escaped the notice of Yates, Baethgen, Sumner, Freerksen, Wemp, Kutilek, Clarke, Lange, Williams, Hitzig, and Hupfeld. [v_Pro_17_27] Unknown"
  },
  "27": {
    "Ruckman, Dr. Peter S_": "The bridled tongue is like the bridled horse of James 3:"
  },
  "3": {
    "Ruckman, Dr. Peter S_": "Blessed is the man that can \u201cbridle\u201d it. David `[char_David_Rut_4]`, like Laban, speaks neither good nor bad (vs. 2), but it is because of his listeners. Laban speaks neither good nor bad because God had warned him about it (Gen. 31:29). The tongue will lie to cover up the \u201cways\u201d (vs. 1) that are not right. Silence is necessary at times because the \u201caudience\u201d (in this case \u201cthe wicked\u201d ) will misquote you, misapply what you say, and use it for personal purposes it was never intended for. Long forbearance in a Bible believer (see Jer. 15:15\u201318) produces \u201cheartburn\u201d (vs. 3). He finally must speak out (Jer. 20:9) for \u201csilence is consent\u201d to wickedness. A modern politician consents to all wickedness by simply being \u201ccaring\u201d and \u201csensitive\u201d to the needs of wicked people; he is not allowed to speak out against them. It would show a lack of \u201csensitivity\u201d and \u201ccaring\u201d\u2014at least that is the common load of stinking garbage now being dished out (1980\u20131997) by the NEA and the News Media. Sometimes it is wrong even to say the right things: Christ says, \u201cYe are not able to receive them now.\u201d The tongue is \u201cset on fire\u201d of Hell (James 3:6), so when old Jeremiah finally speaks out of his burning heart, his words are \u201cHell\u201d to those who hear them (Jer. 38:1\u20134). God\u2019s words are HELL to a Bible rejector. If you ever doubt it, go to any college campus, get up on a \u201cstump,\u201d and preach Isaiah `[char_Isaiah_Gen_26]`"
  }
});
