bible_loader.load_commentary(23, 20, {
  "5": {
    "Commentary Vol. 89": ",6).\nVer.\n5. And they shall be afraid and ashamed, &c.] That is, those that\ntrusted and depended upon the Egyptians and Ethiopians, particularly the\nJews after mentioned, shall be \u201cafraid\u201d that it will be their turn next, that\nthey also shall be taken and carried captive; and they shall be \u201cashamed\u201d\nthat they have put their trust and confidence in those nations, and not in the\nLord:\nof Ethiopia their expectation; from whom they expected assistance and\nprotection, particularly when Tirhakah king of Ethiopia went out against\nthe king of Assyria, that he would have been a match for him, and have\novercome him, and so have freed them from such a powerful enemy:\nand of Egypt their glory; who was their ally, and a very potent one, and in\nwhom they gloried; but now should be ashamed, when both those people\non whom they relied were carried captive.\nVer."
  },
  "1": {
    "Commentary Vol. 89": "In the year that Tartan `[char_Tartan_Ref]` came unto Ashdod, &c.] Or Azotus, as the\nSeptuagint here call it; and which is its name in the New Testament, (see\n[v_Act_8_40] Gill on \u201c<440840>Acts 8:40\u201d). This Tartan, or whom the Septuagint names\nTanathan, and the Arabic version Tathan, was one of Sennacherib\u2019s\n[v_2Ki_18_17] generals, (<121817>2 Kings 18:17):\n(when Sargon the king of Assyria `[nation_Assyria_Gen_2]` sent him); to the above place to besiege\nit. This Sargon is generally thought to be the same with Sennacherib, since\nTartan was one of his generals, who might have more names than one.\nJerom says he had seven; the Jewish Rabbinsf398 eight; though some think a\npredecessor of his is meant, Shalmaneser; and others his son Esarhaddon,\nwho in the Apocrypha\n\u201cAnd there passed not five and fifty days, before two of his sons\nkilled him, and they fled into the mountains of Ararath; and\nSarchedonus his son reigned in his stead; who appointed over his\nfather\u2019s accounts, and over all his affairs, Achiacharus my brother\nAnael\u2019s son.\u201d (Tobit 1:21)\nis called Sarchedon, which might easily pass by pronunciation into Sargon:\nand fought against Ashdod, and took it; which was held by the Assyrians\ntill the time of Psammiticus, and was so strong a city, and so well fortified,\n309\nthat it held out a siege of twenty nine years before he could be master of\nitf399; how long Tartan lay against it, before he took it, is not said; nor is it\ncertain what year he came against it; those who take Sargon to be\nShalmaneser place it in the fourth year of Hezekiah\u2019s reign, who sent\nTartan to Ashdod at the same time that he went against Samaria, (<121809>2\nKings 18:9) but others, who think Sennacherib is Sargon, fix it to the\nfourteenth year of Hezekiah\u2019s reign, as Kimchi; who, hearing of Tirhakah\nking of Ethiopia and Egypt coming against him, went forth to meet him,\nand subdued him; and at the same time sent Tartan against Ashdod; or\nrather this was done when he took the fenced cities of Judah, of which this\nwas one, having been taken a little before by Hezekiah from the Philistines;\n[v_2Ki_18_8] (see <121808>2 Kings 18:8,13) though, if Esarhaddon is Sargon, this must be in\nthe times of Manasseh, perhaps about the twenty second year of his reign,\nby whom he was taken, and carried captive; but it is most likely to have\nbeen in Hezekiah\u2019s time.\nVer."
  },
  "2": {
    "Commentary Vol. 89": "At the same time spake the Lord by Isaiah `[char_Isaiah_Gen_26]` the son of Amoz, &c.]\nOr, \u201cby the hand of Isaiah `[char_Isaiah_Gen_26]`\u201d, by his means; and it was to him likewise, as the\nfollowing words show; and so the Septuagint version renders it; he spoke\nby him, by the sign he used, according to his order, and he spoke to him to\nuse the sign:\nsaying; so the Arabic version, \u201cwith him\u201d; and with these versions Noldius\nagrees:\ngo, and loose the sackcloth from off thy loins; a token of mourning, and\nwhich the prophet wore, as Kimchi thinks, because of the captivity of the\nten tribes; and it may be also on account of the miseries that were coming\nupon the people of the Jews; though some think this was his common garb,\nand the same with the royal garment the prophets used to wear,\n[v_Zec_13_4] (<381304>Zechariah 13:4) but that he had put off, and had put on sackcloth in its\nroom, which he is now bid to take off:\nand put off thy shoe from thy foot; as a sign of distress and mourning also,\n[v_2Sa_15_30] (<101530>2 Samuel 15:30):\nand he did so, walking naked and barefoot; Kimchi thinks this was only\nvisionally, or in the vision of prophecy, as he calls it, and not in reality; but\nthe latter seems most probable, and best to agree with what follows; for he\nwas obedient to the divine command, not regarding the disgrace which\nmight attend it, nor the danger of catching cold, to which he was exposed;\n310\nand hence he has the character of a servant of the Lord, in the next words,\nand a faithful obedient one he was.\nVer."
  },
  "3": {
    "Commentary Vol. 89": "And the Lord said, &c.] Here follows the explanation of the sign,\nand the accommodation of it to the thing signified by it:\nlike as my servant Isaiah `[char_Isaiah_Gen_26]` hath walked naked and barefoot; not wholly\nnaked, for that would have been very indecent and dangerous indeed; but\n[v_1Sa_19_24] without his upper garment, as Saul, (<091924>1 Samuel 19:24) and David `[char_David_Rut_4]`, (<100614>2\nSamuel 6:14,20) or with rent and ragged clothes, and old shoes, as\nJarchif400 interprets it, and which might be only when he appeared abroad;\nand how long he thus walked is not certain, whether only one day, as\nsome, or three days, as others, or three years, which is not said, though our\nversion inclines to it; but the three years next mentioned are not to be\njoined to Isaiah `[char_Isaiah_Gen_26]`\u2019s walking, but to the thing signified by it; for the accent\n\u201cathnach\u201d is at the word which is rendered \u201cbarefoot\u201d, and distinguishes\nthis clause from the following. The Septuagint indeed puts the phrase\n\u201cthree years\u201d into both clauses, but it only belongs to the latter:\nthree years [for] a sign and wonder upon Egypt, and upon Ethiopia; that\nis, the prophet\u2019s walking naked and barefoot was a sign that three years\nafter this Egypt and Ethiopia should be subdued by the Assyrians; or, that\nso long he should be in subduing them, or their calamities should last such\na term of time. This sign was only seen by the Jews, for whose sake chiefly\nthis prophecy was, to take off their dependence on the above nations;\nthough probably this might be made known to the Egyptians and\nEthiopians.\nVer."
  },
  "4": {
    "Commentary Vol. 89": "So shall the king of Assyria lead away the Egyptians prisoners,\nand the Ethiopians captives, &c.] As beasts are led or driven, being taken\nprisoners, and carried captive by the king of Assyria, namely Sargon,\nwhoever is intended by him:\nyoung and old; without any regard to age, sparing none for their tender\nyears or gray hairs:\nnaked and barefoot; as prisoners of war commonly are, being stripped by\ntheir conquerors of their clothes, and having only a few rags given them to\ncover their nakedness with, and obliged to travel without shoes on their\nfeet:\n311\neven with [their] buttocks uncovered, to the shame of Egypt; having no\nclothes on them to cover those parts; or the skirts of their garments cut off,\n[v_2Sa_10_4] as David `[char_David_Rut_4]`\u2019s servants were by the Ammonites, (<101004>2 Samuel 10:4) and this\nto humble and mortify the pride of the Egyptians.\nVer."
  },
  "6": {
    "Commentary Vol. 89": "And the inhabitants of this isle shall say, in that day, &c.] Not of\n[v_Isa_20_1] Ashdod, (<232001>Isaiah `[char_Isaiah_Gen_26]` 20:1) or the isle of Caphtor, (<244704>Jeremiah 47:4) but the\nland of Israel, as both Jarchi and Kimchi interpret it; so called, because it\nbordered on the sea, as such countries are sometimes called isles; (see\n[v_Jer_25_22] <242522>Jeremiah 25:22 <262703>Ezekiel 27:3,15). Ben Melech interprets it of\nJerusalem, and observes that the word signifies a place or country, whether\nit has a river or sea encompassing it, or not; besides, the land of Canaan\nhad the Mediterranean sea on one side of it, and the sea of Galilee and\nTiberias on the other, and was moreover separated from all other countries\nby the power, providence, and presence of God:\nbehold, such [is] our expectation, whither we flee for help, to be delivered\nfrom the king of Assyria; signifying that it was vain and foolish, and they\nhad acted a very weak, as well as a wicked part, in having recourse to the\nEgyptians and Ethiopians to help them against the Assyrians, as it plainly\nappeared by both nations now being conquered by them:\nand how shall we escape? seeing they had not, who were more powerful\nthan they were; and how could they think that they could save them, who\ncould not save themselves? and so the Targum,\n312\n\u201cif they have not delivered their souls (themselves), how shall we be\ndelivered?\u201d\n313"
  }
});
