bible_loader.load_commentary(53, 1, {
  "1": {
    "John Trapp": "In God our Father, and the Lord, &amp;c. ] As God is in his people of a truth, #1Co 14:25 , so are they in God; and as Christ is at God\u2019s right hand, so is the Church at Christ\u2019s right hand, #Ps 45:9 . Yea, they are in him, and part of him, &amp;c.\nVer.\n1. In God our Father, and the Lord, &c.] As God is in his people of a truth, #1Co 14:25, so are they in God; and as Christ is at God\u2019s right hand, so is the Church at Christ\u2019s right hand, #Ps 45:"
  },
  "2": {
    "John Trapp": "Grace be to you, &amp;c. ] { See Trapp on \"1Co 1:3\" } And the Lord Jesus `[char_Jesus_Ref]` Christ ] Who is both the fountain, #Joh 1:16 , and the conduit, #Joh 1:17 ; for of his fulness we have all received grace for grace. Grace, that is, God\u2019s favour and reconciliation; for grace, that is, for the favour and love that God the Father bare unto his Son, #Eph 1:6 .\nVer.\n2. Grace be to you, &c.] {See Trapp on \"1Co 1:3\"} [v_Jhn_1_16] And the Lord Jesus `[char_Jesus_Ref]` Christ] Who is both the fountain, #Joh 1:16, [v_Jhn_1_17] and the conduit, #Joh 1:17; for of his fulness we have all received grace for grace. Grace, that is, God\u2019s favour and reconciliation; for grace, that is, for the favour and love that God the Father bare unto [v_Eph_1_6] his Son, #Eph 1:\n2. Though things be otherwise darkly delivered, yet when the Jews were to lose land and life, then plainly the general [v_Heb_11_35] judgment is mentioned: so #Heb 11:"
  },
  "3": {
    "John Trapp": "We are bound to thank God ] Duty is a debt, and a good heart is not well till it have discharged it. As he that hath somewhat lying on his stomach cannot be at ease till he hath got it up, so neither must we, till disburdened in sounding forth God\u2019s praises for the good he hath bestowed on us, or on others for our use. This, saith Luther, is sancta crapula; and it can be no hurt to have our hearts thus overcharged. Because that your faith groweth exceedingly ] As corn or plants do after a binding drought. They were under persecution, #2Th 1:4 , and gat by it. Storms of persecution beat God\u2019s people into their harbour; make them look to their tackling, patience; to their anchor, hope; to their helm, faith; to their card, the word of God; to their captain, Christ; whereas security, like a calm, maketh us forget both our danger and deliverer; Adversity hath whipped many a soul to heaven, saith one, which otherwise prosperity had coached to hell. We are like to children\u2019s tops, saith another, that will go but little longer than they are whipped. How often are we sitting down on earth, as if we were loth to go any further, till affliction call to us, as the angel to Elijah, \"Up, thou hast a great way to go,\" and then we trigg.\nVer.\n3. We are bound to thank God] Duty is a debt, and a good heart is not well till it have discharged it. As he that hath somewhat lying on his stomach cannot be at ease till he hath got it up, so neither must we, till disburdened in sounding forth God\u2019s praises for the good he hath bestowed on us, or on others for our use. This, saith Luther, is sancta crapula; and it can be no hurt to have our hearts thus overcharged. Because that your faith groweth exceedingly] As corn or plants do after a binding drought. They were under persecution, #2Th 1:4, and gat by it. Storms of persecution beat God\u2019s people into their harbour; make them look to their tackling, patience; to their anchor, hope; to their helm, faith; to their card, the word of God; to their captain, Christ; whereas security, like a calm, maketh us forget both our danger and deliverer; Adversity hath whipped many a soul to heaven, saith one, which otherwise prosperity had coached to hell. We are like to children\u2019s tops, saith another, that will go but little longer than they are whipped. How often are we sitting down on earth, as if we were loth to go any further, till affliction call to us, as the angel to Elijah, \"Up, thou hast a great way to go,\" and then we trigg.\nVer."
  },
  "4": {
    "John Trapp": "For your patience and faith ] Faith patienteth the heart, by putting the head into heaven beforehand, and giving a man a glimpse of future glory. Faith drinks to a suffering saint in a cup of Nepenthes, and saith, \"Be of good courage, and of good carriage under the cross.\" Flebile principium melior fortuna sequetur. The right hand of the Lord can mend all. Faith wraps itself in the promises, lays the soul upon Christ, and maketh it of weak to become strong, #Heb 11:34 . Whatsoever cross cometh upon it, faith is either as a wreath between the shoulder and the burden, that it wring not, or else a remover of it from the soul to God, by virtue of that writ or warrant, #Ps 55:22 \"Cast thy burden,\" &amp;c.\nVer.\n4. For your patience and faith] Faith patienteth the heart, by putting the head into heaven beforehand, and giving a man a glimpse of future glory. Faith drinks to a suffering saint in a cup of Nepenthes, and saith, \"Be of good courage, and of good carriage under the cross.\" Flebile principium melior fortuna sequetur. The right hand of the Lord can mend all. Faith wraps itself in the promises, lays the soul upon Christ, and maketh it of weak to become strong, [v_Heb_11_34] #Heb 11:"
  },
  "5": {
    "John Trapp": "Which is a manifest token ] \u03b5\u03bd\u03b4\u03b5\u03b9\u03b3\u03bc\u03b1, indigitatio. The saints\u2019 sufferings here are an ocular demonstration of a future judgment, wherein all their wrongs shall be righted, all their labour of love recompensed. This held Job\u2019s head above water, when else he had been overwhelmed with the floods of affliction, #Job 19:25 . So #Da 12:1,2 . Though things be otherwise darkly delivered, yet when the Jews were to lose land and life, then plainly the general judgment is mentioned: so #Heb 11:35 .\nVer.\n5. Which is a manifest token] \u03b5\u03bd\u03b4\u03b5\u03b9\u03b3\u03bc\u03b1, indigitatio. The saints\u2019 sufferings here are an ocular demonstration of a future judgment, wherein all their wrongs shall be righted, all their labour of love recompensed. This held Job\u2019s head above water, when else [v_Job_19_25] he had been overwhelmed with the floods of affliction, #Job 19:25. [v_Dan_12_1] So #Da 12:1,"
  },
  "6": {
    "John Trapp": "To recompense tribulation ] To trouble these troublers of Israel, and that throughout all eternity, because they would be always troubling God\u2019s people if they might; as it is said of the scorpion, that there is not one minute wherein it doth not put forth the sting. (Pliny.)\nVer.\n6. Ver.\n6. To recompense tribulation] To trouble these troublers of Israel, and that throughout all eternity, because they would be always troubling God\u2019s people if they might; as it is said of the scorpion, that there is not one minute wherein it doth not put forth the sting. (Pliny.)\nVer."
  },
  "7": {
    "John Trapp": "Rest with us ] As Noah `[char_Noah_Neh_6]`\u2019s ark, after much tossing, rested upon the mountains of Ararat; as the ark of the covenant, formerly transportative, was at length settled in Solomon `[char_Solomon_Ref]`\u2019s temple. The word \u03b1\u03bd\u03b5\u03c3\u03b9\u03bd here used properly signifieth remission and relaxation from hard labour, #Re 14:13 \"they rest from their labours.\" And as the sleep of a labouring man is sweet, so here. With his mighty angels ] Oh, what a glorious day must that needs be, when so many glorious suns shall shine at once; the Lord Christ outshining them all, velut inter ignes luna minores! he will not leave one angel in heaven behind him, #Mr 8:38 .\nVer.\n7. Rest with us] As Noah `[char_Noah_Neh_6]`\u2019s ark, after much tossing, rested upon the mountains of Ararat; as the ark of the covenant, formerly transportative, was at length settled in Solomon `[char_Solomon_Ref]`\u2019s temple. The word \u03b1\u03bd\u03b5\u03c3\u03b9\u03bd here used properly signifieth remission and relaxation from [v_Rev_14_13] hard labour, #Re 14:13 \"they rest from their labours.\" And as the sleep of a labouring man is sweet, so here. With his mighty angels] Oh, what a glorious day must that needs be, when so many glorious suns shall shine at once; the Lord Christ outshining them all, velut inter ignes luna minores! he will not leave one angel in heaven behind him, #Mr 8:"
  },
  "8": {
    "John Trapp": "In flaming fire ] Natural fire, #2Pe 3:6,7 , whereby the elements shall melt like scalding lead upon the wicked, while they give account with all the world on a flaming fire about their ears. Of this last dreadful fire the very heathen had some blind notions. Esse quoque in fatis meminit, &amp;c. (Ovid, Metam. lib. i.) Lucretius and Cicero (De Nat. Deor.) say somewhat to it, but little to the purpose. And that obey not the gospel ] This is the grand sin of this age, #Joh 3:19 . No sin will gripe so in hell as this. This will be a bodkin at the heart one day, I might have been delivered, but I have wilfully cut the throat of my poor soul by refusing those rich offers of mercy made me in the gospel.\nVer.\n8. In flaming fire] Natural fire, #2Pe 3:6,7, whereby the elements shall melt like scalding lead upon the wicked, while they give account with all the world on a flaming fire about their ears. Of this last dreadful fire the very heathen had some blind notions. Esse quoque in fatis meminit, &c. (Ovid, Metam. lib. i.) Lucretius and Cicero (De Nat. Deor.) say somewhat to it, but little to the purpose. And that obey not the gospel] This is the grand sin of this age, [v_Jhn_3_19] #Joh 3:"
  },
  "9": {
    "John Trapp": "Who shall be punished ] Here is the pain of sense, of eternity, of extremity. From the presence ] Here is the pain of loss, which is of the two the greater. And from the glory of his power ] God will set himself to inflict upon the damned such a measure of misery as his power can extend unto.\nVer.\n9. Yea, they are in him, and part of him, &c.\nVer.\n9. Who shall be punished] Here is the pain of sense, of eternity, of extremity. From the presence] Here is the pain of loss, which is of the two the greater. And from the glory of his power] God will set himself to inflict upon the damned such a measure of misery as his power can extend unto.\nVer."
  },
  "10": {
    "John Trapp": "To be glorified ] This is the chief end of his coming, like as he reprobateth some that his mercy in electing others may the more appear. To be admired ] When they shall be seen to shine as the firmament, nay, as the stars, #Da 12:3 , nay, as the sun, #Mt 13:43 , nay, as Christ himself, that Sun of righteousness, to the great admiration of all men. Admiration is the overplus of expectation; Christ admired at his own work in the Centurion\u2019s faith, in Nathanael\u2019s integrity (\"Behold an Israelite indeed\"), in his spouse\u2019s beauty, #So 4 How much more shall others admire it at that day, when grace shall become glory, when there shall be no spot, wrinkle, or other deformity! when the saints shall set the crown upon Christ\u2019s head, #So 3:11 , and cast down their crowns at his feet, #Re 4:10,11 , saying, \"Thou art worthy,\" &amp;c.\nVer.\n10. To be glorified] This is the chief end of his coming, like as he reprobateth some that his mercy in electing others may the more appear. To be admired] When they shall be seen to shine as the firmament, [v_Dan_12_3] nay, as the stars, #Da 12:3, nay, as the sun, #Mt 13:43, nay, as Christ himself, that Sun of righteousness, to the great admiration of all men. Admiration is the overplus of expectation; Christ admired at his own work in the Centurion\u2019s faith, in Nathanael\u2019s integrity (\"Behold an Israelite indeed\"), in his spouse\u2019s beauty, #So 4 How much more shall others admire it at that day, when grace shall become glory, when there shall be no spot, wrinkle, or other deformity! when the saints shall set the crown upon Christ\u2019s head, [v_Sng_3_11] #So 3:11, and cast down their crowns at his feet, #Re 4:10,11, saying, \"Thou art worthy,\" &c.\nVer."
  },
  "11": {
    "John Trapp": "The work of faith with power ] Without which power neither the goodness of God, nor the good pleasure of his goodness, that is, his decree of glorifying us, nor the work of faith, could be effected.\nVer.\n11. The work of faith with power] Without which power neither the goodness of God, nor the good pleasure of his goodness, that is, his decree of glorifying us, nor the work of faith, could be effected.\nVer."
  },
  "12": {
    "John Trapp": "That the name of our Lord ] It is much for the honour of the saints that Christ shall account himself glorified in their glory. Neither is it for their honour only, but for their advantage; for this glory of Christ shall redound unto them; therefore it is added by the apostle, \"And ye in him.\"\n12. That the name of our Lord] It is much for the honour of the saints that Christ shall account himself glorified in their glory. Neither is it for their honour only, but for their advantage; for this glory of Christ shall redound unto them; therefore it is added by the apostle, \"And ye in him.\""
  }
});
