bible_loader.load_commentary(19, 140, {
  "8": {
    "Commentary Vol. 154": "He sitteth in the lurking places of the villages, etc.] Which were by the wayside, where thieves and robbers harboured, and out of which they came, and robbed passengers as they came by. The word f180 signifies \u201cpalaces\u201d or \u201ccourts\u201d: and so it is rendered by the Chaldee paraphrase and Syriac version; and so the allusion is not to mean thieves and robbers, but to persons of note and figure. Hence the Septuagint and Vulgate Latin, Arabic, and Ethiopic versions, render it, \u201che sitteth in lurking places with the rich\u201d; and may be fitly applied to the pope and his cardinals. Antichrist sits in the temple of God, and by his emissaries gets into the villages, the particular churches and congregations of saints, where they lie in ambush to do mischief, to corrupt their faith, worship, and manners; and like thieves and robbers enter in to steal, kill, and destroy; in secret places doth he murder the innocent; the harmless lambs and sheep of Christ; who, though they are not without sin in themselves, yet are innocent with respect to the cause and the things for which they suffer: 113 these are the saints and prophets and martyrs of Jesus `[char_Jesus_Ref]`, whose blood is shed by antichrist; and the taking away of their lives is reckoned murder with [v_Rev_9_21] God; and is so styled in the Scriptures, (<660921>Revelation 9:21); though the antichristian party call it doing God good service, and impute it to zeal for the good of holy church; and yet this they choose to do in secret, by private massacres, or by the inquisition; which having condemned men to death, delivers them over to the secular power to execute the sentence on them: just as the Jews delivered Christ to the Roman governor, to shift off the sin and blame from themselves; murder being what no one cares to be known in, or chargeable with; his eyes are privily set against the poor: the word hklj, rendered \u201cpoor\u201d, is used nowhere but in this psalm, in which it is used three times, [v_Psa_10_1] [v_Psa_10_2] [v_Psa_10_3] [v_Psa_10_4] here, and in (<191001>"
  },
  "1": {
    "Commentary Vol. 155": "Deliver me, O Lord, from the evil man, etc.] Either Saul; so Theodoret; or rather Doeg, according to R. Obadiah: but Jarchi interprets it of Esau; by whom he means Edom, or Rome, or rather the Christians in general. Were his sense confined to the Papists, he might be thought to be much in the right; for this is applicable enough to the man of sin, and his followers: for it may be understood collectively of a body of evil men; all men are evil by nature, their hearts, thoughts, words, works, and ways. David `[char_David_Rut_4]`\u2019s enemies were evil men; and so were Christ\u2019s; as Herod, Judas in particular, and the Jews in general: and such are the enemies of God\u2019s people; the world, profane sinners, persecutors, and false teachers; and to be delivered from such is desirable, and to be prayed for, and an happiness [v_2Th_3_2] when enjoyed; (see <530302>2 Thessalonians 3:2); preserve me from the violent man: or, \u201cthe man of violences\u201df1876; of a violent spirit, that breathes out slaughter and death; of a fierce countenance, of blustering words, and furious actions. Such a man was 1588 Doeg; who loved evil, and all devouring words, devised mischief, and [v_Psa_52_1] [v_Psa_52_2] [v_Psa_52_3] [v_Psa_52_4] boasted in it, (<195201>"
  },
  "5": {
    "Commentary Vol. 155": "The proud have hid a snare for me, and cords, etc.] These were [v_Psa_119_85] the Ziphites, according to Arama; (see <19B985>"
  },
  "10": {
    "Commentary Vol. 155": "Let burning coals fall upon them, etc.] From heaven, as the Targum, Aben Ezra, and Kimchi, by way of explanation; alluding to the burning of Sodom and Gomorrah with fire from thence: and may design both the terrible judgments of God in this life, and everlasting burnings in [v_Psa_11_6] hell; so Jarchi interprets it of the coals of hell; see (<191106>\nVer."
  },
  "11": {
    "Commentary Vol. 155": "Let not an evil speaker be established in the earth, etc.] One that sets his mouth against the heavens, and speaks evil of God; of his being, perfections, purposes, and providences: whose tongue walks through the 1593 earth, and speaks evil of all men, even of dignities; and especially of the saints of the most High, and of the Gospel and ways of Christ. Or, \u201ca men of tongue\u201df1884; that uses his tongue in an ill way, in detractions and slandersf1885; in blaspheming God, his name and tabernacle, and those that [v_Rev_13_5] dwell therein, as antichrist, (<661305>Revelation 13:5); a man that calumniates with a triple tongue, so the Targum; like a serpent, whose tongue seems to be so sometimes. Kimchi applies this to Doeg, and Jarchi to Esau. The `[animal_Sea_Rev_13]` request is, that such an one might not be established in the earth; in the land of the living, as the Targum; might not increase and flourish in worldly substance, or be continued in his posterity; but be rooted out of the earth, [v_Psa_3_4] and he and his be no more; (see <190304>"
  },
  "12": {
    "Commentary Vol. 155": "I know, etc.] Here is a double reading: the \u201cKeri\u201d, or marginal reading, is, \u201cthou knowest\u201d; an appeal of the psalmist to God, who knew the thoughts of the wicked concerning him, and their devices against him; as Kimchi: but the Scripture reading is, I know; expressing his full persuasion and assurance that the Lord will maintain the cause of the afflicted, [and] the right of the poor; of his poor and afflicted people, that are afflicted within and without, by men and devils; and who are poor as to the things of this world, and poor in spirit, and sensible of their spiritual poverty, but rich in grace: the cause of these God will maintain against their oppressors, and right their wrongs, and avenge their injuries; this the psalmist knew, and was assured of from the word of God, from instances and examples in former times, [v_Psa_9_4] and from his own experience, (<190904>"
  },
  "4": {
    "Commentary Vol. 155": "I looked on [my] right hand, and beheld, etc.] On the left, so Kimchi supplies it, and after him Piscator; he looked about him every way to the right and left, to see if he could get any help, or find out any way of deliverance. To this sense the Targum, Septuagint, Vulgate Latin, Syriac, and Arabic versions render the words; and so Kimchi and Aben Ezra understand them: but some render them in the imperative, \u201clook on the right hand, and behold\u201df1905; and consider them; either as spoken to his own soul, to stir up himself to look around him for help and relief; or as an [v_Psa_80_14] address to God, to look and behold, as in (<198014>"
  }
});
