bible_loader.load_commentary(9, 44, {
  "61": {
    "Psalms": "Ver."
  },
  "62": {
    "Psalms": "He gave his people over also to the sword, etc.] To those that kill with the sword, as the Targum; that is, to the Philistines, when there fell of [v_1Sa_4_10] them thirty thousand men at once, (<090410>1 Samuel 4:10) 906 and was wroth with his inheritance; and the above showed that he was, though they were his inheritance, his portion and possession, and he had [v_Psa_33_12] chosen them for it, (<193312>\nVer."
  },
  "63": {
    "Psalms": "The fire consumed their young men, etc.] Not Nadab and Abihu, as some of the Jewish Rabbins interpret it, of which Jarchi makes mention; but the young men, the choice, the flower, of the Israelitish army, which engaged with the Philistines in the times of Eli; and the fire that consumed them is not to be understood of material fire, or of extraordinary fire from heaven, but either of the wrath of God, as Jarchi, or of the flaming glittering sword of the enemy, which consumed them like fire; (see [v_Num_21_28] <042128>Numbers 21:28 <232611>Isaiah `[char_Isaiah_Gen_26]` 26:11) and their maidens were not given to marriage; the young men to whom they should have been married, and to whom they might have been espoused, being slain in battle: or, \u201cwere not honoured\u201d f1143; that with [v_Heb_13_4] marriage, which is honourable to all, (<581304>Hebrews 13:4), or \u201cwere not praised\u201d f1144; were not attended with epithalamies and nuptial songs, such as used to be sung at the time of marriage; hence, as Kimchi observes, the nuptial chamber is called alwlh tyb, \u201cthe house of praise\u201d; and so frequently, when a great calamity is threatened or described, it is said, the [v_Jer_16_9] voice of the bride and bridegroom is not heard; (see <241609>Jeremiah 16:9 [v_Rev_18_23] 25:10 <661823>Revelation 18:23).\nVer."
  },
  "64": {
    "Psalms": "Their priests fell by the sword, etc.] Hophni and Phinehas, the sons of Eli, and other priests; which shows the cruelty of the enemy, not to spare men unarmed, as the priests were; and the justice of God, which pursued these men, who were very wicked, and whose character and office could not secure them from divine wrath: and their widows made no lamentation; for their husbands the priests, who fell by the sword; particularly the widow of Phinehas, who upon the news fell into labour, and as soon as she brought forth her child died, and while she lived took no notice of the death of her husband, nor lamented that, [v_1Sa_4_19] [v_1Sa_4_20] [v_1Sa_4_21] [v_1Sa_4_22] only that the ark of the Lord was taken, (<090419>1 Samuel 4:19-22), and which might be the case of others; nor could they attend their funerals, or follow them to the grave with lamentations, they falling in battle; and such was their concern for the public loss, that their private sorrow was swallowed up in it. Some understand it of the disrespect and neglect of others, who 907 came not to lament with them, and comfort them, as was usual: one of the Targums paraphrases the whole thus, \u201cat the time that the Philistines carried captive the ark of the Lord, the priests of Shiloh, Hophni, and Phinehas, fell by the sword; and at the time they brought their wives the news of it, they wept not, for they died even the same day.\u201d\nVer."
  },
  "65": {
    "Psalms": "Then the Lord awaked as one out of sleep, etc.] He seemed to be asleep, while he suffered the ark to be taken, and the Israelites to be slain; and he may be said to awake when he exerted his power in smiting the [v_Psa_7_6] Philistines, and causing their idol to fall before his ark; (see <190706>"
  }
});
