bible_loader.load_commentary(19, 28, {
  "1": {
    "Commentary Vol. 154": "Unto thee will I cry, etc.] This denotes the distress the psalmist was in, fervency and ardour in prayer, resolution to continue in it, and singularity with respect to the object of it; determining to cry to the Lord only; to which he was encouraged by what follows; O Lord my rock; he being a strong tower and place of defence to him, in whom were all his safety, and his trust and confidence, and in whom he had an interest; be not silent to me; or \u201cdeaf\u201d f434; persons that do not hear are silent, and make no answer; as the Lord seems to be, when he returns no answer to the cries of his people; when he does not arise and help them; when he seems not to take any notice of his and their enemies, but stands at a [v_Psa_39_12] distance from them, and as if he had forsaken them; (see <193912>",
    "Tony W. Cartledge": "must be to suggest a time early\nin David `[char_David_Rut_4]`\u2019s reign when David `[char_David_Rut_4]` has been delivered\n\u201cfrom the hand of all his enemies, and from the\nhand of Saul.\u201d Saul was hardly a factor in David `[char_David_Rut_4]`\u2019s\nlater life, but his relentless pursuit of the younger\nDavid `[char_David_Rut_4]` could have inspired the distress of vv. 5-\nv. 1 is similar to 2 Samuel\n7:1, which says that \u201cthe king was settled in his\nhouse, and the LORD had given him rest from all his enemies\naround him.\u201d David `[char_David_Rut_4]` would battle other enemies after this point,\nbut generally on the offensive rather than the defensive, and thus\nnot in need of deliverance. In the context of"
  },
  "5": {
    "Commentary Vol. 154": "Because they regard not the works of the Lord, etc.] Neither the work of creation, as if there was no first cause of all things; nor the work of Providence, taking no notice either of the judgments or of the mercies of God; as though they believed that God had forsaken the earth, and would do neither good nor evil; and still less the work of redemption, which in covenant, promise, and prophecy, was appointed for the Messiah to work out; and as for the work of the Spirit of God upon the soul, they had no notion of that, of the nature and necessity of it; the things of the Spirit of God being foolishness to them, and undiscernible by them; (see <230512>Isaiah `[char_Isaiah_Gen_26]` 5:12). Perhaps the psalmist may have some regard to his being anointed by Samuel, according to the will of God, and to the victory which he obtained over Goliath, and over others, which justly gained him great esteem among some, and created envy in others; and also the wonderful protection of him from time to time; the Chaldee paraphrase is, \u201cbecause they do not understand the law of the Lord\u201d. It follows, 319 nor the operation of his hands; in which his hand was so very apparent, that nothing less could be said than that this was the finger of God; wherefore, he shall destroy them, and not build them up; that is, they shall be irrecoverably lost; they shall be punished with everlasting destruction; there will be no help or remedy for them: some f436 understand this as a prayer, that God would destroy them in such a manner, and render it, \u201clet him destroy them\u201d, etc. f437.\nVer.\n5. My soul shall be satisfied as [with] marrow and fatness, etc.] When he should return to the house of the Lord, and partake of the provisions of it, called the fatness of his house, (see Gill on \u201c<193608>"
  },
  "6": {
    "Commentary Vol. 154": "Blessed [be] the Lord, etc.] Which must be understood, not as invoking nor as conferring a blessing on him, neither of which can be done by a creature; nor does he stand in need of any, he being Elshaddai, God all sufficient, God over all, blessed for ever; but as ascribing all blessedness to him, congratulating his greatness and happiness, and giving him praise and glory for mercies received; and particularly for the following: because he hath heard the voice of my supplications; what he had prayed [v_Psa_28_2] for, (<192802>"
  },
  "7": {
    "Commentary Vol. 154": "The Lord [is] my strength, etc.] That is, the author both of natural and spiritual strength; that gave him strength of body, and fortitude of mind, to bear up under all the exercises he was tried with; the strength of his life, spiritual and temporal, and of his salvation; the strength of his heart under present distresses, and who he knew would be so in the hour of death, when his heart and strength would fail; and my shield; to protect and defend him; as were the love, power, and faithfulness of God, and the Lord Jesus `[char_Jesus_Ref]` Christ, his power and fulness, his blood, righteousness, and salvation; my heart trusted in him; in the Lord as his strength and shield; not in any creature, nor in his own strength and righteousness; but in the Lord God, in whom are righteousness and strength: and it is plain he did not trust in his own heart, since his heart trusted in the Lord; and which shows that his trust was an hearty one, his faith was a faith unfeigned, he believed with the heart unto righteousness; 320 and I am helped: this was the fruit of his trust, even a gracious experience of divine assistance: saints are helpless in themselves, and are also as to the help of man; God is the only helper of them; he helps them out of all their troubles; in whatsoever he calls them unto, and to what they want; and the help he affords is sometimes quick, and always seasonable; and sometimes by means, and sometimes without them; therefore my heart greatly rejoiceth; that is, in the Lord, the ground of which was the help he had from him; and this joy was very great, a joy unspeakable, and full of glory; it was not carnal, but spiritual, a heart joy, joy in the Holy Ghost; and with my song will I praise him; praise is due to God, what glorifies him, and is acceptable to him; it becomes the saints, is comely for them, and it is pleasant work to them, when grace is in exercise; (see <196930>",
    "Tony W. Cartledge": "Mitchell Dahood\u2019s translation of s\u02c7a\u00af<\u00fbl as \u201cSheol\u201d\n(cf. 22:6) rather than \u201cSaul\u201d is unconvincing.1\nThe terminology of"
  },
  "3": {
    "Commentary Vol. 155": "The Lord, that made heaven and earth, bless thee out of Zion.] These are not the words of the priests blessing the people in this form, as some; but rather, as others, the wish of the servants of the Lord, that he would bless him that exhorted them to this service; whether one of the priests, or the captain of the temple, or the psalmist: though, according to Kimchi, and which seems agreeable, they are the words of the psalmist, promising a blessing from the Lord to those that blessed him; as an encouragement to them, to everyone of them, to be constant and diligent in this service. For so it may be rendered, \u201cthe Lord shall bless thee\u201df1802; all 1535 blessings come from the Lord, whether spiritual or temporal; and are to be asked of him, and expected from him: and the blessings here promised or asked for are blessings out of Zion, the church, where God blesses his people with his word and ordinances, with his presence, and with communion with himself. Wherefore it is good to be there waiting on him and worshipping him, praying to him and praising of him; and he that made heaven and earth is able to bless both with heavenly and earthly things: and this description of the Lord is no doubt given to encourage faith in him; for, what is it he cannot do? 1536"
  }
});
