bible_loader.load_commentary(58, 62, {
  "7": {
    "Warren W. Wiersbe": ", His sinless life in"
  },
  "8": {
    "Warren W. Wiersbe": ", and His sacrificial death in\nverse"
  },
  "6": {
    "Warren W. Wiersbe": "However, it was first of all a psalm about David and his needs and how the Lord met them, but the historical setting is obscure. David may have written it during his difficult exile years or perhaps during the early years of his reign. It\u2019s unusual for a psalm to have a prayer for mercy following praise and dedication. However, if\nverses 1\u20135 picture his deliverance during the dangerous exile years and\nverses 6\u201310 describe his dedication as the new king, then\nverses 11\u201317 could be a record of his prayer for personal forgiveness (\nverse 6, sacrifice means any animal whose blood was offered at the altar, followed by a communal meal. Offering refers to the meal offering that could accompany the sacrifices, and the burnt offering symbolized total dedication to the Lord. The sin offering was given to cover specific offenses and bring reconciliation between the offender and God. All of these were fulfilled in Jesus Christ, whose sacrifice on the cross satisfied the justice of God once and for all, for time and eternity (Lev. 1\u20147; Heb. 10:1 [c_Heb_10] [v_Heb_10_1] \u201317). The \u201copen ears\u201d refer to his readiness to hear and obey God\u2019s will (1 Sam. 9:15 [c_1Sa_9] [v_1Sa_9_15] ; 20:2; Isa. 48:8 [c_Isa_48] [v_Isa_48_8] ; 50:4\u20135; Matt. 3:43 [c_Mat_3] [v_Mat_3_43] ; Acts 7:51 [c_Act_7] [v_Act_7_51] , 57). This is not a reference to the servant in Exodus 21:1\u2013\n6. The passage is paraphrased in Hebrews 10:5\u201310 as \u201ca body you have prepared for me,\u201d i.e., the body in which the Messiah served the Father here on earth. An open ear means a yielded will and a surrendered body. When the heart delights in God\u2019s law, the will has no problem obeying (119:11; Deut. 6:6 [c_Deu_6] [v_Deu_6_6] ; 11:18; Prov. 3:3 [c_Pro_3] [v_Pro_3_3] ; 7:3; Jer. 31:33 [c_Jer_31] [v_Jer_31_33] ). \u201cLo, I come\u201d means \u201cHere I am, ready to obey\u201d (see 1 Sam. 3:4 [c_1Sa_3] [v_1Sa_3_4] , 6, 8; Isa. 6:8 [c_Isa_6] [v_Isa_6_8] ). The scroll may be a reference to Deuteronomy 17:14\u201320; and see 2 Kings 11:12 [c_2Ki_11] [v_2Ki_11_12]  and 22:"
  },
  "12": {
    "Warren W. Wiersbe": "; see 38:3\u20135; 39:8\u20139) and victory over his enemies following his coronation. It does seem that\nv. 12; 31:9; 38:10), but God knew the future and had everything under control. As he often did (7:1, 5; 22:19; 38:22; 71:12), David prayed for speedy deliverance. \u201cI am \u2026 thou art\u201d (\nv. 12), for he had walked before the Lord in humility and submission (7:8; 18:19\u201325; 25:21; 78:72). When confronted with his sins, he confessed them and sought the face of the Lord (2 Sam. 12:13ff.). David wanted mercy for himself but not for his enemies, except for his son Absalom (2 Sam. 18:5 [c_2Sa_18] [v_2Sa_18_5] ). Why? Because his enemies (especially Absalom) had committed treason against the Lord\u2019s chosen and anointed king. This was not a personal vendetta on David\u2019s part, but a concern for the future of the nation of Israel and the dynasty of David. As ruler of the land, David wielded the sword of justice (Rom. 13:1 [c_Rom_13] [v_Rom_13_1] \u20134), and nations today punish treason with death. More than anything else, David wanted to please God (\nv. 12; 16:11; 17:15; 21:6; 101:7; 2 Sam. 7:16 [c_2Sa_7] [v_2Sa_7_16] )."
  },
  "16": {
    "Warren W. Wiersbe": "is a royal prayer for God\u2019s blessing on the nation. You find\nverses 13\u201317 repeated in modified form in\nPsalm"
  },
  "70": {
    "Warren W. Wiersbe": "From whatever experiences led to the writing of this psalm, David learned some valuable lessons and gave us three important instructions to follow in the difficult times of life.\n1. Praise God for All He Has Done (vv. 1\u20135). No matter what our trouble or trial, it\u2019s always good to look back and recall the goodness of the Lord. David remembered how long he had waited before the Lord delivered him from his enemies and from Saul, but the day came when God inclined His ear (31:3), heard his cries, and lifted him up from the pit. If David learned anything from his exile years, it was that ultimate success depends on faith in the Lord and patience during His providential working (5:3; 33:20; 37:34; 38:15; Heb. 6:12 [c_Heb_6] [v_Heb_6_12] ). We are not to take the description of the pit literally (slime, mud, mire), but figuratively, as a picture of those difficult years David endured. \u201cThe pit\u201d is also a term for sheol, the realm of the dead, and David\u2019s life was certainly in danger. An old-fashioned country preacher used\nverses 2\u20133 for a sermon text, and his \u201cpoints\u201d were the following: God brought him up, God stood him up, and God tuned him up! David had a new beginning with a new song of praise in his mouth (18:49; 22:22; 33:3). God helped David because he trusted the Lord, did not show respect to the arrogant who opposed God, and remained true to the God of Israel. \u201cLies\u201d in"
  },
  "4": {
    "Warren W. Wiersbe": "refers to idols. Unlike David, King Saul was a proud man who trusted in himself and made himself more important than God. In looking back on those years as an exile and a hunted man, David saw the greatness of God\u2019s works (wonders) and the wisdom of His plans (\nv. 4) again unite to put David into distress and danger as his enemies plot against him and wait for him to die. These factors seem to place this psalm in the time of Absalom\u2019s rebellion. David\u2019s illness prevented him from leading the nation as he wanted to (2 Sam 15:1 [c_2Sa_15] [v_2Sa_15_1] \u20136), and Absalom took advantage of this to promote himself as king. If the \u201cdear friend\u201d of\nv. 4). God would protect him from his enemies and prolong his life in the land. That in itself would bear witness to his enemies that David was a man favored by God. God would also heal him of his sickness and raise him up from the sickbed. \u201cMake all his bed\u201d (\nv. 4). He also affirmed his integrity (\n4. Glory: How Do We Treat God ("
  },
  "5": {
    "Warren W. Wiersbe": "). This is his version of Romans 8:28."
  },
  "2": {
    "Warren W. Wiersbe": "Give God All That He Asks (vv. 6\u201310). David has moved from the pit to the rock, and now he goes to the sanctuary of God. After all God had done for David, how could the king express to the Lord his appreciation for His mercies? He could bring sacrifices to the altar, but that wasn\u2019t God\u2019s first desire. This doesn\u2019t mean that such sacrifices were wrong or that God didn\u2019t want His people to offer them, but that God wanted their hearts first of all. Throughout the Old Testament, the Lord made it clear that He could not accept sacrifices unless the worshipper showed sincere devotion, dedication, and obedience. No doubt David heard how Saul learned that important lesson\u2014too late (1 Sam. 15:22 [c_1Sa_15] [v_1Sa_15_22] ). (See 50:8\u201315; 51:16\u201317; Prov. 21:3 [c_Pro_21] [v_Pro_21_3] ; Isa. 1:11 [c_Isa_1] [v_Isa_1_11] \u201317; Jer. 7:22 [c_Jer_7] [v_Jer_7_22] \u201323; Hos. 6:6 [c_Hos_6] [v_Hos_6_6] ; Mic. 6:6 [c_Mic_6] [v_Mic_6_6] \u20138; Mark 12:32 [c_Mrk_12] [v_Mrk_12_32] \u201333.) In\n2. Treachery: How Do Others Treat Us (vv. 5\u20139)? It wasn\u2019t enough that David was sick in bed, but he also had to deal with treachery among his own family and friends, including men like Ahithophel, his official counselor, who sided with Absalom. Ahithophel was Bathsheba\u2019s grandfather (2 Sam. 11:3 [c_2Sa_11] [v_2Sa_11_3] ; 23:34) and hated David for what he did to her and to her husband Uriah. These false friends visited the king and lied to him (\u201cWe hope you\u2019ll get well soon\u201d), but they really wanted David to die and even plotted against him. But if Absalom became king, that would be the end of the Davidic dynasty, for Absalom had no son (2 Sam. 18:18 [c_2Sa_18] [v_2Sa_18_18] ). God promised David that his descendants would sit on the throne of Israel forever (2 Sam. 7:11 [c_2Sa_7] [v_2Sa_7_11] \u201316), a promise ultimately fulfilled in Jesus Christ (Luke 1:31 [c_Luk_1] [v_Luk_1_31] \u201333). David was gifted at reading people (2 Sam. 14:17 [c_2Sa_14] [v_2Sa_14_17] \u201320) and knew the truth. Jesus used"
  },
  "13": {
    "Warren W. Wiersbe": "The Old Testament predicts the coming of the Messiah (Luke 24:27 [c_Luk_24] [v_Luk_24_27] ). David was enthusiastic about telling others what the Lord had done for him, and he is a good example for us to follow (22:25; 26:12; 35:18; 111:1; 149:1). Among the worshippers at the sanctuary, the king gave glory to the Lord. This reminds us of our Lord\u2019s resurrection praises (22:31; Heb. 2:12 [c_Heb_2] [v_Heb_2_12] ).\nv. 13)? This verse was probably added later by an editor to mark the end of book I of the Psalms. Each of the first four books ends with a similar doxology (41:13; 72:18\u201320; 89:52; 106:48), and book V ends with a praise psalm (150). But the verse reminds us that the main thing in our lives must be the eternal praise and glory of the Lord. \u201cHallowed be thy name\u201d is the first request in the Disciples\u2019 Prayer (Matt. 6:9 [c_Mat_6] [v_Mat_6_9] ), and it governs all the other requests. God answers prayer, not to make His people more comfortable, but to bring glory to His name. The Lord still had more work for David to do, particularly the preparation for the building of the temple, and His glory would one day move into that holy sanctuary (1 Kings 8:1 [c_1Ki_8] [v_1Ki_8_1] \u201311). Can we honestly say \u201cAmen and amen!\u201d to the prayer in\nverse 13? QUESTIONS FOR PERSONAL REFLECTION OR GROUP DISCUSSION"
  },
  "3": {
    "Warren W. Wiersbe": "Trust God for All That Remains (vv. 11\u201317). When the worship service was ended and David had returned to his royal duties, he discovered that there were new battles to fight and fresh problems to solve, so he turned again to the Lord for help. Worship is not an escape from life but the opportunity to honor God and be equipped to face life and live for His glory. David had his own personal problems to deal with (vv. 11\u201313), for he had a sensitive conscience and knew that he was a sinful man. He also had enemies who wanted to dethrone him (vv. 14\u201315), and so he prayed for victory. (See 25:4, 21\u201327.) Most of all, David wanted the Lord to be magnified and His people to be blessed as they served Him (vv. 16\u201317). David couldn\u2019t see what lay ahead (\nv. 3) simply means \u201cheal him and raise him up.\u201d This would be the gracious and merciful act of the Lord, undeserved by David but lovingly granted by Jehovah. \u201cIf I regard wickedness in my heart, the L ORD will not hear\u201d (66:18 NASB ), so it\u2019s important that we confess our sins to the Lord. If we haven\u2019t been merciful to others, how can our hearts be right to ask Him for mercy?\n3. Mercy: How Does God Treat Us (vv. 10\u201312)? God in His mercy doesn\u2019t give us what we do deserve, and God in His grace gives us what we don\u2019t deserve, and He does this because of Jesus Christ His Son, who died for us on the cross. David prayed for mercy, because he knew he had sinned ("
  },
  "17": {
    "Warren W. Wiersbe": ") says it all. The great I AM is adequate for every need."
  },
  "9": {
    "Warren W. Wiersbe": "is David\u2019s counselor Ahithophel, then the matter of the historical setting is settled (2 Sam. 16:15ff.). Jesus quoted\nverse 9 in the upper room when referring to Judas (John 13:18 [c_Jhn_13] [v_Jhn_13_18] ), so the psalm has messianic overtones. When we find ourselves in difficulty, we may use this psalm to take an inventory of our spiritual condition by asking and answering four questions.\nverse 9 when referring to the traitor Judas (John 13:18 [c_Jhn_13] [v_Jhn_13_18] \u201319; and see 55:12\u201314; 69:25; 109:8; Matt. 26:63 [c_Mat_26] [v_Mat_26_63] ; Mark 14:18 [c_Mrk_14] [v_Mrk_14_18] ; Luke 22:21 [c_Luk_22] [v_Luk_22_21] ; Acts 1:16 [c_Act_1] [v_Act_1_16] \u201320). Note that our Lord didn\u2019t quote the phrase \u201cwhom I trusted\u201d from\nverse 9, for He knew that Judas had no saving faith (John 6:70 [c_Jhn_6] [v_Jhn_6_70] \u201371). This psalm opens with a statement about the poor, and Judas tried to identify himself with the poor (John 12:4 [c_Jhn_12] [v_Jhn_12_4] \u20136; 13:26\u201330). David\u2019s enemies wanted the king\u2019s name to perish, but it was Judas who destroyed a good name\u2014\u201cJudah,\u201d which means \u201cpraise.\u201d We call our sons David, but we would never call a son Judas. (See 2 Sam. 16:15 [c_2Sa_16] [v_2Sa_16_15] \u201317:23 for Ahithophel\u2019s part in the rebellion.) The phrase \u201clifted up his heel\u201d pictures a deceptive and underhanded attack, but see Romans 16:20 [c_Rom_16] [v_Rom_16_20] ."
  },
  "1": {
    "Warren W. Wiersbe": "Integrity: How Do We Treat Others (vv. 1\u20134)? Before we can claim God\u2019s promises, we must examine our own hearts to see if we have sincerely met the conditions the Lord has laid down. David no doubt based his prayer on the stipulations given in the covenant (Lev. 26:1 [c_Lev_26] [v_Lev_26_1] \u201313; Deut. 7:13 [c_Deu_7] [v_Deu_7_13] \u201316; 28:1\u201314). He knew that he had no right to claim mercy from the Lord if he himself had not shown mercy to others. But David had fully obeyed the Lord\u2019s rules and had shown mercy to King Saul, to Saul\u2019s grandson Mephibosheth, and to the needy in the land. (See Matt. 5:7; Luke 6:37 [c_Luk_6] [v_Luk_6_37] \u201338.) \u201cPoor\u201d refers to the helpless, the miserable people whose lot was difficult and who depended on the help of others. To \u201cconsider\u201d these pitiable people meant being attentive to their needs and assisting them. It also meant not judging and blaming them, as Job\u2019s friends blamed him and the disciples blamed the blind man (John 9:1 [c_Jhn_9] [v_Jhn_9_1] \u20134). We have every reason to believe that David sought to care for the poor and needy in his kingdom and therefore was praying with integrity. In\nverse 1, he referred to himself in the third person, a true mark of his humility before the Lord. He listed in\nverses 2\u20133 the blessings God would send because he confessed his sins and asked God to be merciful to him ("
  },
  "11": {
    "Warren W. Wiersbe": "; 18:19; 22:8; 35:27; 2 Sam. 15:26 [c_2Sa_15] [v_2Sa_15_26] ). He had confidence that the Lord would heal him, restore him to the throne, and deal with those who opposed him. Even more, he was certain that one day he would be in the presence of the Lord and serve in His holy courts in heaven forever ("
  }
});
