bible_loader.load_commentary(65, 22, {
  "6": {
    "E.W. Bullinger": "Milton has described this war, but he only drew on his imagination, which was limited\nby earthly battlefields. This war is wholly different in its occasion, its scenes, its combatants,\nand its weapons. This war has its foreknown and therefore its foretold ending.\nxii."
  },
  "8": {
    "E.W. Bullinger": "And they prevailed not; nor was even their place found any more in heaven.]\nThe great object with which that war is waged will be accomplished.\n8. The Structure of this fourth Vision \"on Earth\" is presented in two separate parts, because\nthey concern two separate Peoples (Jew and Gentile), which are never \"reckoned\" together\n(Num. xxiii. 9). The two divisions are as follows:\u2014\nE4, xii. 13-xiii."
  },
  "9": {
    "E.W. Bullinger": "And the great dragon was cast down, the old serpent; who is called the Devil, and\nSatan, he who deceiveth the whole world: he was cast down unto the earth, and his angels\nwere cast down with him.]\u00a0\u00a0\u00a0\u00a0 There can be no doubt as to whom this \"sign\" refers. By four\nnames is he defined, so that we might make no mistake. And yet, it will hardly be believed\n263\nThe Fourth Vision In Heaven\nthat, in spite of this, there are interpreters who maintain that it means the \"Pagan Roman\nEmpire,\" and Michael is the \"Christian Roman Empire.\" There are others who understand\nit of no real war at all, but only a prolonged antagonism between good and evil. How refresh-\ning to come back to the Word of God, and believe that we have there the climax which the\nLord Jesus `[char_Jesus_Ref]`, looking forward to the result of His \"sufferings,\" in \"the glory\" that should follow,\nalready foresaw with His spiritual prophetic vision in Luke x. 18, and said: \"I beheld Satan\nas lightning fall from heaven.\"\nA., xii. 10-\nEach of these visions seen in heaven are marked by heavenly voices and utterances. We\nhave one in this Vision. The Structure is as beautiful as it is simple. The subjects of the ut-\nterance are two:\n(1) Rejoicing in heaven;\n(2) Woe to the earth;\nand between them there is a call for universal rejoicing.\nA, xii. 10-\nA |\u00a0\u00a0\u00a0\u00a0 h |\u00a0\u00a0\u00a0\u00a0 k | 10-.\u00a0 Rejoicing in heaven.\nl | -10,\ni | 12-.\u00a0 Call to rejoice.\nh |\u00a0\u00a0\u00a0\u00a0 k | -12-.\u00a0 Woe to the earth.\nl | -\nxii."
  },
  "10": {
    "E.W. Bullinger": "And I heard a loud voice in heaven, saying,24\n\"Now is come the salvation, and the power, and the kingdom of our God, and the\nauthority of His Christ: because the accuser of our brethren is cast down, who accused\nthem before our God day and night. (11) And they overcame him because of the blood\nof the Lamb, and because of the word of their testimony; and they loved not their life\neven unto death. (12) Therefore Rejoice, ye heavens, and ye who dwell in them. Woe to25\nthe earth and to the sea! because the devil is come down to you, having great fury,\nknowing that he hath but a short season.\"]\nThis is the song of victory sung in heaven. It will be sung by those who will have been\ncaught up to heaven out of \"the great Tribulation.\" (Ch. vii., xiv., xv.) For they speak of \"our\nbrethren.\" \"Now is come\" is the shout of triumph which celebrates, by anticipation, the results\nof Satan's being cast out of heaven. This is the first step arising out of Heaven's declaration\nof war. The emphasis is on the pronoun \"they,\" in"
  },
  "11": {
    "E.W. Bullinger": ", for they who overcame on earth\nThis is the order of the words according to G.L.T.Tr.A. WH. and RV.\nG.L.T.Tr.A. WH. and RV. omit \"the inhabiters of.\"\n264\nThe Fourth Vision In Heaven\nnow call on all heaven to rejoice over the wondrous victory. When the fruits of this heavenly\nvictory are fully reaped on earth, then there will be others to call for the new songs, which\nare already written down for the singers in Ps. xciii.\u2014, xcviii., cxlix. This call to rejoice finds\nits echo in the final song of triumph in Rev. xix. But all is traced up to and grounded on the\ninfinite merits of \"the blood of the Lamb\": and the wonderous efficacy of His atonement.\nAgain, we see that the Church cannot be here, for no one can accuse the Church before\nGod. See Rom. viii."
  },
  "33": {
    "E.W. Bullinger": "We shall be indeed surprised if our readers are able to see, as the cause of that heavenly\noutburst of joy, the mere \"casting down of paganism from the throne of the Roman Empire.\"\nThe result of that was blessing to the world.\nThe result of this is \"woe to the earth.\" ("
  },
  "12": {
    "E.W. Bullinger": ")!\nBut such a difference as this does not count with the expositors of this Book. Nor does\nthe fact that the result of that conflict has gone on for centuries, in which the whole Reform-\nation period is included; while this is to last for a very brief period \u2014 one of many great\nevents occurring in the last 3 1/2 years.\nWhen Satan is cast down, \"he hath but a short time,\" which is definitely stated to be 3\n1/2 years, during which he is wroth with the woman, and makes war with the remnant of\nher seed (xii. 14-17).\nThis \"Woe\" is the last of a series of three (viii. 13); and must, therefore, be subsequent\nto the first two, which at this stage will have passed (xi. 14). The third is proclaimed in chap.\nxii. 12, and consists of the casting out of Satan.\nThis conclusively shows that, though the Vision of ch. xii. is anticipative, the actual\ncasting out cannot take place till the middle of the last of the seventy weeks (Dan. ix. 27).\nThe Beast will be reigning on the earth during the first half of this week (Rev. vi. \u2014 xi.); but,\nin his human and mortal form; and acting \"peaceably\" (Dan. xi. 21). But now, in the middle\nof the week, the crisis or \"Third Woe\" comes (xii. 12). Satan is cast out. The Beast, having\nreceived his \"deadly wound,\" reappears in his superhuman form, and \"makes war with the\nsaints\" (xiii. 7). This last half of the week is \"the great and terrible day of the Lord.\" But this\nbrings us to the next, the Fourth Vision \"on Earth\" (xii. 13 \u2014 xiii. 18).\n265\nThe Fourth Vision In Heaven\nThe Fourth Vision \"On Earth\"\nE4, xii. 13\u2014"
  },
  "18": {
    "E.W. Bullinger": "THE RESULT \"ON EARTH\" OF THE \"WAR IN HEAVEN.\"\nThis Vision, as a whole, is occupied with the Result \"on Earth\" of the \"war in heaven\"\n(chap. xii.). It is two-fold: First, the effect is given as it concerns Israel, and then, the effect\nas it concerns the Earth as a whole; and all forming part of this parenthesis or Episode, which\ntakes us back to the period before xi. 13, and shows us how the Beast came to be on the\nearth. It is he who makes war against the \"Two Witnesses\" (ch. xi.); and it is against him and\nhis armies that the judgments and plagues of chaps. vi.-ix. are directed.\nNow, we are taken back to have these prior events further made known and explained\nto us. The Episode does not end till chap. xv.\n18. The Fourth Vision \"on Earth.\"\nThe Result \"on Earth\" of the \"War in Heaven.\"\nE4 |\u00a0\u00a0\u00a0\u00a0 W | xii. 13-xiii. 1-.\u00a0 The effect as regards Israel.\nX | xiii. -1-\n18. The effect as regards the Earth.\nDealing first with the former of these two divisions, we have to give its expansion. It\nwill be seen that its Structure exactly corresponds with the preceding Vision \"in heaven,\"\n(chap. xii. 1-12); the correspondence showing that both parts of chap. xii. refer to the same\nsubject, viz., Israel. The following is the expansion of W:\nW, xii. 13-xiii. 1-.\u00a0 The Result of the War \"in Heaven\" as regards Israel.\nW |\u00a0\u00a0\u00a0\u00a0 A | xii. 13-.\u00a0 The Dragon cast unto the earth.\nB |\u00a0\u00a0\u00a0\u00a0 a | -\nb | 14-\nc |\nA | xiii. 1-.\u00a0 The Dragon standing on the sand of the sea.\nThe Dragon, as soon as he is cast down into the earth, at once proceeds to make war\nwith the Woman, and the remnant of her seed. He does this by bringing up the Beast in his\nsuperhuman form.\nxii."
  },
  "13": {
    "E.W. Bullinger": "And when the dragon saw that he was cast down to the earth, he pursued (or\npersecuted) the woman which brought forth the man-child1 (14) And there was given to"
  }
});
