bible_loader.load_commentary(21, 29, {
  "2": {
    "Milton P. Horne": "nizes that the internal disposition affects one\u2019s external actions (Eccl\n8:1). But"
  },
  "15": {
    "Milton P. Horne": "offers an application to a real problem: can one who\nis poor ameliorate his suffering by facing poverty with the appro-\npriate disposition? This would be the implication of the two\nstatements in\nv.\n15. Are readers to understand that the way to\naddress the suffering poverty brings is by maintaining a cheerful\nheart, a positive attitude, or a balanced emotional state? Or is this a\nform of denial that too easily glosses over real social problems?\nVerses 16-17 take the question further."
  },
  "16": {
    "Milton P. Horne": ", a Yahweh\nsaying, states that religion joined with poverty is better than wealth\nconjoined with trouble."
  },
  "17": {
    "Milton P. Horne": "is not a Yahweh saying but\nexpresses a similar idea: poverty, represented by a table of vegeta-\nbles, with love is better than wealth, represented by the \u201cfatted ox,\u201d\nconjoined with hatred. Both sayings rest on the assumptions set\nout in vv. 13 and"
  },
  "14": {
    "Milton P. Horne": "One may wonder, however, whether the\nauthor of this saying was himself wealthy or poor. On the other\nhand, readers again anticipate the words of Ecclesiastes, who may\nhimself have been wealthy and concluded that all is absurdity (Eccl\n2:1-11). [Theodicy]\nVerses 18 and 19 apparently stand on their own. There may be\nsome thematic connection between vv. 17 and 18 in the conclusion\nof 17b with the word \u201chate\u201d (\u221ein<\u00e2-b\u00f4) and the opening of 18a with\n\u201chot-tempered\u201d (<\u00ee\u00a1 \u02d9\u2211m\u00e2)."
  },
  "18": {
    "Milton P. Horne": "recalls the concerns of the\nopening four sayings (vv. 1-4) with its interest in anger (\u02d9\u2211m\u00e2)."
  },
  "19": {
    "Milton P. Horne": "contrasts two different kinds of categories, laziness and\n195\n[v_Pro_15_1] [v_Pro_15_2] [v_Pro_15_3] [v_Pro_15_4] [v_Pro_15_5] [v_Pro_15_6] [v_Pro_15_7] [v_Pro_15_8] [v_Pro_15_9] [v_Pro_15_10] [v_Pro_15_11] [v_Pro_15_12] [v_Pro_15_13] [v_Pro_15_14] [v_Pro_15_15] [v_Pro_15_16] [v_Pro_15_17] [v_Pro_15_18] [v_Pro_15_19] [v_Pro_15_20] [v_Pro_15_21] [v_Pro_15_22] [v_Pro_15_23] [v_Pro_15_24] [v_Pro_15_25] [v_Pro_15_26] [v_Pro_15_27] [v_Pro_15_28] [v_Pro_15_29] [v_Pro_15_30] [v_Pro_15_31] [v_Pro_15_32] [v_Pro_15_33] Proverbs 15:1-33\nTheodicy\nThe term theodicy denotes the phenomenon of\nmaintaining belief in the justice and righteousness\nof God in the face of disconfirming experiences. Although the\nterm is not in the Old Testament, it provides the conceptual\numbrella for readers\u2019 understanding of the many questions\nabout innocent suffering and righteous retribution within\n[v_Jer_12_1] (e.g., Jer 12:1; Job 21:1-16; Gen 18:22-33). James L.\nCrenshaw notes that the concept was never merely theoret-\nical in the Old Testament. The issue of God\u2019s just governance\nof the universe involved society itself, from economics, to\nsocial disparity, and including individuals\u2019 rights. Little\nwonder that the wisdom literature took the question so seri-\nously. The sages\u2019 conviction of the order and harmony of\ncreation had to withstand an awesome challenge from all\ndisconfirming realities, including the Babylonian captivity.\nThe Old Testament literature documents Israel\u2019s commit-\nment to hold on to belief in God\u2019s justice, even when he\ndecreed the sacrifice of Abraham `[char_Abraham_Exo_17]`\u2019s firstborn (Gen 22), or his\n[v_Hos_11_1] [v_Hos_11_2] [v_Hos_11_3] [v_Hos_11_4] [v_Hos_11_5] [v_Hos_11_6] [v_Hos_11_7] [v_Hos_11_8] [v_Hos_11_9] [v_Hos_11_10] [v_Hos_11_11] own firstborn, Israel (Hos 11:1-11). If theodicy is indeed the\nbeginning point for theological reflection, theology takes on a\ndefensive posture, bearing the weight of justifying evil before\npraise can take place.\nThe confession of Yahweh\u2019s presence may be taken as an\nassertion of theodicy. Nothing happens without the Lord\u2019s\nknowing it; no event falls outside the order of the Lord\u2019s uni-\nverse. The wisdom tradition gives fullest expression to the\nstruggle to maintain a good faith commitment to God\u2019s right-\n[v_Pro_15_3] eousness. While asserting God\u2019s presence, as in Prov 15:3,\nthe tale of Job makes clear that the maintenance of such\nviews exacts high prices in the realm of human surrender\nand submission.\nFor further reading, see James L. Crenshaw, \u201cTheodicy,\u201d\nIDBSup, 895-96; Leo G. Perdue, Wisdom in Revolt (JSOTSup\n112; Sheffield: JSOT Press, 1991); and R. J. Williams,\n\u201cTheodicy in the Ancient Near East,\u201d CJT 2 (1956): 14-\nv. 19, where industriousness is moral-\nized\u2014using the same root, y\u00e5\u00a1\u00e5r\u2014"
  },
  "26": {
    "Milton P. Horne": "James L. Crenshaw, \u201cTheodicy,\u201d ABD 6: 444-47.\nmoral uprightness. The implication is that industriousness is given\nmoral value. On the other hand, there may be humor in the\nimages. The lazy person always has an excuse for not working\u2014in\nthis case that excuse consists of the \u201cthorns\u201d along his way.\nRetrospect on Solomon `[char_Solomon_Ref]`\u2019s Sayings, 15:20-33\nThe concluding section of sayings recapitulates several themes\nreaders have encountered throughout the opening five chapters of\nthe \u201cProverbs of Solomon `[char_Solomon_Ref]`.\u201d The sayings are gathered rhetorically in\nthree subgroups, the two outer groups paralleling each other. The\ninner group functions as a kind of central focus.\nVerses 20-24\nconcern wisdom and folly, education and instruction.\nVerses 25-27\ncontrast righteousness with wickedness and Yahweh\u2019s judgment.\nVerses 28-33 return to the themes of the initial subgroup, only here\nthe appeal to Yahweh reinforces and legitimizes the claim that one\u2019s\ndesire for discipline is wisdom. Moreover, these closing verses com-\n[v_Pro_10_1] plete an inclusio for the entire section, Proverbs 10:1\u201315:33, by\nreturning to the themes encountered in 10:1-4, which initially\nassert the idea of wisdom\u2019s profitability.\nVerses 20-24 concern the themes of wisdom and folly and fore-\n[v_Ecc_2_1] shadow Ecclesiastes\u2019 \u201ctest\u201d of wisdom and folly (e.g., Eccl 2:1).\nVerse 26 returns to the\nabomination formula readers have encountered in vv. 8 and 9 to\nassert the contrast between evil plans and pleasant words. The\n[v_Pro_11_29] imagery of"
  },
  "20": {
    "Milton P. Horne": "returns to the images of 15:5, 13:1, and 10:1 concerning\nthe pleasure wise children give to their parents."
  },
  "24": {
    "Milton P. Horne": ", perhaps\nthe climax of this initial group, offers the broadest statement justi-\nfying both the success of wise children and the joy it brings to\nparents: \u201cthe path of life leads upward for the wise,\u201d avoiding the\ndownward slope toward Sheol for fools. Within these two sayings\nthere are examples of folly and wisdom."
  },
  "21": {
    "Milton P. Horne": "begins with a\ngeneral statement that folly causes rejoicing only to those who lack\nsense. By contrast, 21b moralizes the understanding person\u2019s\nbehavior. That person \u201cwalks straight ahead.\u201d The verbal root for\n\u201cto walk straight\u201d is the same root encountered in the noun \u201cthe\nupright\u201d (y\u00e5\u00a1\u00e5r). Thus, as in\nv. 21 has a similar moralizing\nstrategy."
  },
  "22": {
    "Milton P. Horne": "offers another example of folly by asserting that\nthere are no plans where there is no council.\nVerses 21 and 23\nbalance each other in their use of the image of \u201cjoy\u201d (\u221eim\u02d9\u00e2) to\ncharacterize their examples of wisdom or folly. In"
  },
  "23": {
    "Milton P. Horne": "joy is the\nresult of a timely answer, something only a wise person could pos-\nsibly appreciate. The combination of terminology provides a\nbackground for the theological implications of \u201cjoy.\u201d Ecclesiastes\ninterprets joy as the \u201canswer\u201d of God to the plight of humanity\n196\n[v_Pro_15_1] [v_Pro_15_2] [v_Pro_15_3] [v_Pro_15_4] [v_Pro_15_5] [v_Pro_15_6] [v_Pro_15_7] [v_Pro_15_8] [v_Pro_15_9] [v_Pro_15_10] [v_Pro_15_11] [v_Pro_15_12] [v_Pro_15_13] [v_Pro_15_14] [v_Pro_15_15] [v_Pro_15_16] [v_Pro_15_17] [v_Pro_15_18] [v_Pro_15_19] [v_Pro_15_20] [v_Pro_15_21] [v_Pro_15_22] [v_Pro_15_23] [v_Pro_15_24] [v_Pro_15_25] [v_Pro_15_26] [v_Pro_15_27] [v_Pro_15_28] [v_Pro_15_29] [v_Pro_15_30] [v_Pro_15_31] [v_Pro_15_32] [v_Pro_15_33] Proverbs 15:1-33\n[v_Ecc_5_18] [v_Ecc_5_19] [v_Ecc_5_20] (e.g., Eccl 5:18-20; 9:7-10) in what is perhaps one of the climactic\nstatements of the book of Ecclesiastes. Joy may be all that is left\nwhen everything else is absurd. In\nv. 23 something as simple as the\nright word at the right time provides joy.\nVerses 25-27 provide a moral center for these closing sayings\n(vv. 20-33), both metaphorically and literally. Metaphorically, they\nappeal to Yahweh as the source of wisdom\u2019s order. Literally, these\nthree moralizing verses stand in the center of two outlying groups\nof sayings on wisdom and folly (vv. 20-24 and 28-33). All three of\nthese assert explicitly or implicitly Yahweh\u2019s judgment upon\nwickedness."
  },
  "25": {
    "Milton P. Horne": "observes that Yahweh will protect the widow\nby tearing down the house of the proud."
  },
  "27": {
    "Milton P. Horne": "is not new; Proverbs 11:29 also speaks of the one\nwho \u201ctroubles his house\u201d (cf. 15:6). Readers have also encountered\nthe sages\u2019 disapproval of \u201cill-gotten gain\u201d in 1:\ntoward bribery will occur again in 17:8, 19:6, and 21:\nv. 27,\nthe implication is that Yahweh guarantees life to those who hate\nbribes since it is through bribery that one\u2019s profit is inappropriately\nobtained.\nVerses 28-33 each contain either explicit or implicit references to\nhearing, heeding, or reflecting upon instruction, good news, or\nprayer. With such language and imagery, this opening section (Prov\n10\u201315) on the profitability of wisdom comes to a close. The impli-\ncation is that apart from one\u2019s attentive listening, people may not\nreceive wisdom or any of its attending advantages. The opening\nimage of the righteous person\u2019s activity is one of \u201cpondering,\u201d or\n[v_Psa_1_2] \u201cmusing.\u201d"
  }
});
