bible_loader.load_commentary(11, 7, {
  "4": {
    "Commentary Vol. 1": "And the damsel [was] very fair, etc.] And so very agreeable to the\nking to be in his presence, and wait upon him, and take things of her hand,\nas well as lie with him:\nand cherished the king; enlivened his spirits by her amiable countenance,\nher graceful behaviour, and tender care of him, and especially by bedding\nwith him:\nand ministered to him; serving him with her own hands whatever he took\nfor his sustenance:\nbut the king knew her not; as a man knows his wife; which shows that she\nwas his wife, and that it would not have been criminal in him had he known\nher; but this is observed, not to point at the chastity of David `[char_David_Rut_4]`, but his\nfeebleness, and loss of desire after women, and that the damsel remained a\nvirgin; and that was the ground of Adonijah\u2019s request, and his hope of\nsucceeding.\nVer.",
    "John H. Walton, John K. Riches": "is the Hebrew verb translated\n\u201cserve\u201d used with the phrase translated \u201conly.\u201d)5 It is likely that\nIsrael is worshiping the Lord along with other gods, but there is no\nroom for polytheism or syncretism in the worship of the one true\nGod. In this regard Samuel\u2019s demand is countercultural, for such\nexclusivism did not characterize religion in the ancient Near East.\n7:4 So the Israelites put away their Baals and Ashtoreths, and served the\nLord only\ufffd The repetition of Samuel\u2019s command (\u201crid yourselves\u201d\n[",
    "Walter Brueggemann, Warren Carter": ", the conditional quality of the royal promise is intensified\nby the word \u201cif.\u201d [The \u201cIf\u201d of Faith] This is an exceedingly important\nturn in the royal theology of Israel. The initial promise by God to\n[v_2Sa_7_11] [v_2Sa_7_12] [v_2Sa_7_13] [v_2Sa_7_14] [v_2Sa_7_15] [v_2Sa_7_16] David `[char_David_Rut_4]` in 2 Samuel 7:11-16 is quite unconditional. The king may\n[v_Psa_132_11] [v_Psa_132_12] be punished, but will always be loved. In\never, the initial promise of 2 Samuel 7 is decisively changed to\nmake it conditional. The introduction of \u201cif\u201d into the royal\npromise makes the monarchy of David `[char_David_Rut_4]` subject to the conditions of\nTorah, thus reinterpreting the monarchy that had been an offer of\nfree grace. This \u201cif\u201d is very old in Mosaic teaching, present already\n[v_Exo_19_5] [v_Exo_19_6] in Exodus 19:5-\nv. 4 the prophet\nmocks routinized temple chants. In",
    "John Trapp": "And the damsel was very fair. ] And therefore lovely, \u03bf\u03c4\u03c4\u03b9 \u03ba\u03b1\u03bb\u03bf\u03bd \u03c6\u03b9\u03bb\u03bf\u03bd \u03b5\u03c3\u03c4\u03b9 , and fitter for the purpose. But the king knew her not. ] Utpote frigidus et inhabilis ad generandum; neither would it have been for his health, as the case then stood.\nVer.\n4. In three rows, ] i.e., In three stories, called also ranks here. And light was against light. ] Fenestrae ex diametro, through lights, we call them.\nVer.\n4. And the damsel was very fair.] And therefore lovely, \u03bf\u03c4\u03c4\u03b9 \u03ba\u03b1\u03bb\u03bf\u03bd \u03c6\u03b9\u03bb\u03bf\u03bd \u03b5\u03c3\u03c4\u03b9, and fitter for the purpose. But the king knew her not.] Utpote frigidus et inhabilis ad generandum; neither would it have been for his health, as the case then stood.\nVer.\n4. In three rows, ] i.e., In three stories, called also ranks here. And light was against light.] Fenestrae ex diametro, through lights, we call them.\nVer."
  },
  "5": {
    "Commentary Vol. 1": "Then Adonijah the son of Haggith exalted himself, etc.] This was\n[v_2Sa_3_4] his mother\u2019s name, (<100304>2 Samuel 3:4); his father David `[char_David_Rut_4]` being old and\ninfirm, and not like to live long, notable to oppose him; and he being the\neldest son, and a comely person, was inspired with ambition to set up for\nking:\nsaying, I will be king; though he knew that Solomon `[char_Solomon_Ref]` was appointed of\nGod, and promised by David `[char_David_Rut_4]`, and expected by the people to be king, yet he\nwas resolved to set up himself for king, and try if he could not get himself\nto the throne; on this he was bent and determined:\nand he prepared him chariots and horsemen, and fifty men to run before\nhim; just as Absalom had done, when he had the same thing in view, to\n[v_2Sa_15_1] make him respectable among the people, (see <101501>2 Samuel 15:1).",
    "John H. Walton, John K. Riches": "I will intercede \ufffd \ufffd \ufffd for you\ufffd Prior to this, the expression\n[v_Gen_20_7] \u201cintercede for\u201d is used only of Abraham `[char_Abraham_Exo_17]` (Gen. 20:7 AT; \u201cpray for,\u201d\n[v_Num_21_7] NIV) and Moses `[char_Moses_Exo_2]` (Num. 21:7; Deut. 9:20).\n[v_1Sa_7_6] Here (1 Sam. 7:6) and in Numbers 21:7 the\npeople confess their sins with the simple\nstatement \u201cWe have sinned,\u201d and the leader\nprays on behalf of the people (intercession\n[v_Gen_20_7] for an individual is in view in Gen. 20:7 and\n[v_Deu_9_20] Deut. 9:20). A similar account appears in\n[v_1Sa_12_19] 1 Samuel 12:19, 23 (AT), where the expres\nsion \u201cintercede for\u201d is used once more in\nthe context of communal confession of sin.",
    "John Trapp": "Exalted himself, saying, I will be king. ] This was another of David `[char_David_Rut_4]`\u2019s darlings. Him and Absalom, David `[char_David_Rut_4]` had honoured, as Eli had done his two wicked sons, above the Lord; { #1Sa 2:29 } therefore they proved a singular cross to him. I will be king. ] Though David `[char_David_Rut_4]` had declared Solomon `[char_Solomon_Ref]` to be designed king by God himself, { #1Ch 22:9,10 } and Adonijah knew it to be so, and therefore called not Solomon `[char_Solomon_Ref]` and his party to his feast. { #1Ki 1:19 } Vain men, whilst, like proud and yet brittle clay, they will be knocking their sides against the solid and eternal decree of God, break themselves in pieces. And he prepared him chariots. ] Absalom-like; ambition rideth without reins. David `[char_David_Rut_4]` should have now looked upon him as another Absalom, and suppressed him. But he either knew not, or suspected not this pomp, and those preparations of his.\nVer.\n5. With the windows. ] All were square: and so this house was, ad elegantiam, amaenitatem et recreationem tota comparata, very pleasant.\nVer.\n5. Exalted himself, saying, I will be king.] This was another of David `[char_David_Rut_4]`\u2019s darlings. Him and Absalom, David `[char_David_Rut_4]` had honoured, as Eli had done his two wicked sons, above the Lord; {#1Sa 2:29} therefore they proved a singular cross to him. I will be king.] Though David `[char_David_Rut_4]` had declared Solomon `[char_Solomon_Ref]` to be designed king by God himself, {#1Ch 22:9,10} and Adonijah knew it to be so, and therefore called not Solomon `[char_Solomon_Ref]` and his party to his feast. {#1Ki 1:19} Vain men, whilst, like proud and yet brittle clay, they will be knocking their sides against the solid and eternal decree of God, break themselves in pieces. And he prepared him chariots.] Absalom-like; ambition rideth without reins. David `[char_David_Rut_4]` should have now looked upon him as another Absalom, and suppressed him. But he either knew not, or suspected not this pomp, and those preparations of his.\nVer.\n5. With the windows.] All were square: and so this house was, ad elegantiam, amaenitatem et recreationem tota comparata, very pleasant.\nVer."
  },
  "3": {
    "John H. Walton, John K. Riches": "If you are returning \ufffd \ufffd \ufffd with all your hearts\ufffd The reference\nto the Israelites\u2019 \u201chearts\u201d emphasizes the need for sincere motives as\na foundation for action. The idiom \u201creturn with the heart\u201d focuses\non the internal dimension of repentance as the foundation for\n[v_1Ki_8_48] appropriate actions (see 1 Kings 8:48; 2 Kings 23:25; Joel 2:12).\nrid yourselves of the foreign gods\ufffd Joshua used this same expression\nwhen he commanded the Israelites to put away their\n* Repentance and renewed allegiance to the Lord open the door to deliverance.\n* The Lord is the one true God and the only genuine source of his people\u2019s\nsecurity.\n[v_Jos_24_14] idols (Josh. 24:14, 23). By reporting that Samuel addresses Israel in\nthis same way, the narrator may be casting him in the role of\nJoshua `[object_Joshua_Jos_2]` and suggesting that he has become the spiritual leader of\nthe nation.\nserve him only\ufffd \u201cServe\u201d carries connotations of worship and\nloyalty. The addition of \u201conly\u201d emphasizes the exclusivity that is\nintended. (Only here and in\nv. 3] and \u201cput away\u201d translate the same Hebrew verb) in the report\nof Israel\u2019s response highlights the people\u2019s sincerity and obedience.\nApparently this is a firm decision on the part of Israel, for we do not\nread of the people as worshiping the Baals again until the time of\n[v_1Ki_16_31] Ahab (1 Kings 16:31), who ruled in 874\u2013853 BC.6 If we date\nSamuel\u2019s victory to roughly 1070 BC, then it appears that Israel did\nnot worship Baal for close to two hundred years.",
    "John Trapp": "Upon the beams. ] Heb., Ribs: for beams are to a building what ribs are to a living creature. In Africa they make, if not beams, yet rafters for houses, of the whale\u2019s ribs.\nVer.\n3. Upon the beams.] Heb., Ribs: for beams are to a building what ribs are to a living creature. In Africa they make, if not beams, yet rafters for houses, of the whale\u2019s ribs.\nVer."
  },
  "6": {
    "John H. Walton, John K. Riches": "they drew water and poured it out\ufffd\nThe significance of this action is unclear.\nPerhaps it symbolizes their repentant spirit\n[v_Lam_2_19] (see Lam. 2:19),7 indicates their willing\nness to deprive themselves of the bare\nessentials of life (thus fasting\nin\nv. 6),8 and/or symbolizes\npurification of guilt.9\nthey fasted\ufffd Their\nfasting apparently ex\npresses their sincere\nsorrow over their\npast sins (see Judg.\n[v_1Sa_31_13] 20:26; 1 Sam. 31:13;\n[v_2Sa_1_12] 2 Sam. 1:12).",
    "Walter Brueggemann, Warren Carter": "Perhaps its fullest presentation is voiced in\n[v_Deu_30_15] [v_Deu_30_16] [v_Deu_30_17] [v_Deu_30_18] [v_Deu_30_19] [v_Deu_30_20] Deuteronomy 30:15-20, where it is affirmed,\nIf you obey\u2026then you shall live,\u2026\nBut if your heart turns away\u2026you shall not live long.\nDavid `[char_David_Rut_4]`\u2019s instruction in this utterance is peculiarly important,\nbecause in much of the royal narrative, David `[char_David_Rut_4]` is not attentive to the\nTorah, but seems to assume that he is exempt from Torah require-\nments. In the dramatic story of Uriah and Bathsheba (2 Sam\n11\u201312), David `[char_David_Rut_4]` acted beyond Torah. Moreover, in what follows in\nthis speech of David `[char_David_Rut_4]`, the rigorous \u201cif\u201d of Torah is not operative.\nBut in these verses monarchy for the future is held to severe\nv. 6), an image of making economic agreements. Moreover, the\n\u201ccedars of Lebanon\u201d are named in",
    "John Trapp": "And his father had not displeased him at any time. ] Heb., From his days, i.e., from his childhood; therefore he displeased his father in his age; little caring to crush his heart when now bedridden, by his disloyalty and usurpation. But thus was still fulfilled what had been forethreatened. { #2Sa 12:11 } In saying, Why hast thou done so? ] He cockered his children, whom he should have corrected if he had done right. David `[char_David_Rut_4]` was ever too fond a father, and he smarted for it. And he also was a very goodly man. ] As well as Absalom: this made him think the better of himself, and his father think too well of him.\nVer.\n6. Were before them. ] Or, According to them: all was suitable, and sightly.\nVer.\n6. And his father had not displeased him at any time.] Heb., From his days, i.e., from his childhood; therefore he displeased his father in his age; little caring to crush his heart when now bedridden, by his disloyalty and usurpation. But thus was still fulfilled what had been forethreatened. {#2Sa 12:11} In saying, Why hast thou done so?] He cockered his children, whom he should have corrected if he had done right. David `[char_David_Rut_4]` was ever too fond a father, and he smarted for it. And he also was a very goodly man.] As well as Absalom: this made him think the better of himself, and his father think too well of him.\nVer.\n6. Were before them.] Or, According to them: all was suitable, and sightly.\nVer."
  },
  "9": {
    "John H. Walton, John K. Riches": "the Lord an\nswered him\ufffd The\nand to David `[char_David_Rut_4]`\u2019s at Keilah (23:4), but Samuel warns that the Lord will\nnot respond to the cries of disobedient Israel (8:18), nor does he\nanswer the rejected Saul (28:6).",
    "John Trapp": "And Adonijah slew sheep and oxen. ] Hitherto all went \u2018hail well\u2019 with these gallants: and many a health, no doubt, was drunk to Adonijah: many a confident boast of their prosperous design, many a scorn of the despised faction of Solomon `[char_Solomon_Ref]`, &amp;c. But the triumphing of the wicked is short. { #Job 20:5 } { See Trapp on \"Job 20:5\" }\nVer.\n9. According to the measure of hewed stones. ] Though costly, yet as great as other hewed stones. Unto the coping, ] i.e., The top of the wall, whereon the beams were laid.\nVer.\n9. And Adonijah slew sheep and oxen.] Hitherto all went \u2018hail well\u2019 with these gallants: and many a health, no doubt, was drunk to Adonijah: many a confident boast of their prosperous design, many a scorn of the despised faction of Solomon `[char_Solomon_Ref]`, &c. But [v_Job_20_5] the triumphing of the wicked is short. {#Job 20:5} {See Trapp on \"Job 20:5\"}\nVer.\n9. According to the measure of hewed stones.] Though costly, yet as great as other hewed stones. Unto the coping, ] i.e., The top of the wall, whereon the beams were laid.\nVer."
  },
  "10": {
    "John H. Walton, John K. Riches": "the Lord thundered. See above, under \u201cHistorical and Cultural\nBackground.\u201d\nand threw them into such a panic\ufffd The use of this verb (hamam)\nlinks this event with earlier instances of the Lord\u2019s supernatural\n[v_Exo_14_24] intervention on behalf of Israel (Exod. 14:24; Josh. 10:10; Judg.\n4:15). By linking this victory with the exodus and conquest, the\nnarrator makes the point that\nthe God of Israel, who has won great victories in the past, is alive\nand well. He may be depicting Samuel, the Lord\u2019s human\ninstrument on this occasion, as a new Joshua (see 7:3).\nthey were routed\ufffd The narrator uses this verb (nagap) to highlight\nthe contrast between the Israelites\u2019 earlier defeat under\nnarrator again es\ntablishes Samuel\u2019s\ncredentials as the\nLord\u2019s chosen spiri\ntual leader and in\ntercessor. The Lord\nresponds (\nv. 10) to his\nprayer. This theme of\nthe Lord\u2019s answering\n(or not answering)\nprayer becomes im",
    "John Trapp": "But Nathan the prophet. ] These were no whit the worse men for being thus neglected. The wise historian observed, that the statues of Brutus and Cassius { a } were the more glorious and illustrious, because they were not brought out with other images in a solemn procession at the funeral of Germanicus. Cato said he had rather men should question why he had no statue or monument erected to him, than why he had. { a } Tacit.\nVer.\n10. And the foundatlon was of costly stones. ] Heb., Precious; yet not of emeralds, carbuncles, sapphires, as #Isa 54:11 , but of marble, porphyry, &amp;c., which were longlasting. Even great stones. ] Which therefore were the closer together, and the surer.\nVer.\n10. But Nathan the prophet.] These were no whit the worse men for being thus neglected. The wise historian observed, that the statues of Brutus and Cassius {a} were the more glorious and illustrious, because they were not brought out with other images in a solemn procession at the funeral of Germanicus. Cato said he had rather men should question why he had no statue or monument erected to him, than why he had. {a} Tacit.\nVer.\n10. Ver.\n10. And the foundatlon was of costly stones.] Heb., [v_Isa_54_11] Precious; yet not of emeralds, carbuncles, sapphires, as #Isa 54:11, but of marble, porphyry, &c., which were longlasting. Even great stones.] Which therefore were the closer together, and the surer.\nVer."
  },
  "29": {
    "Lloyd R. Bailey": "193",
    "John Trapp": "Who hath delivered my soul. ] Deliverance commandeth obedience. { #Ezr 9:13,14 }\nVer.\n29. See on #1Ki 7:28 .\nVer.\n29. Who hath delivered my soul.] Deliverance commandeth [v_Ezr_9_13] obedience. {#Ezr 9:13,14}\nVer.\n29. See on #1Ki 7:"
  },
  "36": {
    "Lloyd R. Bailey": "193\n8:2\n8:64\n8:65\n282\n8:66\n283\n9:20-21\n240\n11:1\n247\n11:29-31\n171\n12:32-33\n285\n18:28-29\n235",
    "John Trapp": "Amen: the Lord\u2026say so too. ] Amen is, (1.) Assenting; (2.) Assevering; (3.) Assuring. It is as much as So be it; yea, So it shall be; It must be so, if, as here, the Lord our God say so too. Only we must stretch out our hearts after our Amen, say the Rabbis, and be swallowed up in God.\nVer.\n36. According to the proportion of every one. ] Heb., According to the nakedness; that is, the true resemblance. Truth is like our first parents, most beautiful when naked. And additions round about. ] Round about the base were certain fillings and finishings, on the uppermost edgings.\nVer.\n36. Amen: the Lord\u2026say so too.] Amen is, (1.) Assenting; (2.) Assevering; (3.) Assuring. It is as much as So be it; yea, So it shall be; It must be so, if, as here, the Lord our God say so too. Only we must stretch out our hearts after our Amen, say the Rabbis, and be swallowed up in God.\nVer.\n36. And for the porch, &c.] The king\u2019s house had the like porch before it, as God\u2019s house had.\nVer.\n36. According to the proportion of every one.] Heb., According to the nakedness; that is, the true resemblance. Truth is like our first parents, most beautiful when naked. And additions round about.] Round about the base were certain fillings and finishings, on the uppermost edgings.\nVer."
  },
  "2": {
    "Terence E. Fretheim, Thomas B. Slater": "311, 321",
    "John Trapp": "He built also the house of the forest of Lebanon. ] For public feasts, games, pastimes, and delights, { #Ec 2:4-6 } for a magazine also. { #1Ki 10:16,17 Isa 22:8 } Framed it might be in Lebanon, { #1Ki 9:19 } but built it was in Jerusalem, Solomon `[char_Solomon_Ref]`\u2019s dwelling house and throne not far from it. { #1Ki 7:6-8 } It seemeth to have been called \"the house of the forest of Lebanon,\" not because it stood in that forest, as William, bishop of Tyre, and Junius hold: { a } but partly because it was made of the cedars of Lebanon, in which regard also the temple is called Lebanon, { #Zec 11:1 } and partly because it was a kind of abridgment of that famous forest, and contained in it, and in the gardens and groves about it, all the delights and pleasures of that forest, in solitary walks, sweet smells, music of birds, and sight of wild beasts, &amp;c., whence the Hebrews call it domum refrigerii, the house of refreshing. { a } Lib. xviii, belli sacri.\nVer.\n2. He built also the house of the forest of Lebanon.] For [v_Ecc_2_4] [v_Ecc_2_5] [v_Ecc_2_6] public feasts, games, pastimes, and delights, {#Ec 2:4-6} for a magazine also. {#1Ki 10:16,17 Isa 22:8} Framed it might be in Lebanon, {#1Ki 9:19} but built it was in Jerusalem, Solomon `[char_Solomon_Ref]`\u2019s dwelling house and throne not far from it. {#1Ki 7:6-8} It seemeth to have been called \"the house of the forest of Lebanon,\" not because it stood in that forest, as William, bishop of Tyre, and Junius hold: {a} but partly because it was made of the cedars of Lebanon, in which regard also [v_Zec_11_1] the temple is called Lebanon, {#Zec 11:1} and partly because it was a kind of abridgment of that famous forest, and contained in it, and in the gardens and groves about it, all the delights and pleasures of that forest, in solitary walks, sweet smells, music of birds, and sight of wild beasts, &c., whence the Hebrews call it domum refrigerii, the house of refreshing. {a} Lib. xviii, belli sacri.\nVer."
  },
  "7": {
    "Terence E. Fretheim, Thomas B. Slater": "319",
    "John Trapp": "And he conferred with Joab, &amp;c. ] Seeking to draw these grandees to his party, whom he knew to be discontented, and therefore more easily wrought upon. Joab was conscious to himself of the treacherous murdering of Abner and Amasa; for which and the death of Absalom, David `[char_David_Rut_4]` bare him still an aching tooth: and if he stayed till David `[char_David_Rut_4]` appointed a successor in the kingdom, who knew what might follow? Abiathar haply was displeased that Zadok was so much favoured: and might fear the fulfilling of that prophecy concerning the overthrow of Eli\u2019s house, of which he was. But what saith an ancient? Divinum consilium dum devitatur, impletur; humana sapientia, dum reluctatur, comprehenditur. { a } There are \"many devices in a man\u2019s heart: nevertheless the counsel of the Lord, that shall stand.\" { #Pr 19:21 } { a } Greg.\nVer.\n7. Then he made a porch for the throne. ] That stately throne of ivory. { #1Ki 10:18-20 } Even the porch of judgment. ] Built for the conveniency of such as came to the king for judgment.\nVer.\n7. And he conferred with Joab, &c.] Seeking to draw these grandees to his party, whom he knew to be discontented, and therefore more easily wrought upon. Joab was conscious to himself of the treacherous murdering of Abner and Amasa; for which and the death of Absalom, David `[char_David_Rut_4]` bare him still an aching tooth: and if he stayed till David `[char_David_Rut_4]` appointed a successor in the kingdom, who knew what might follow? Abiathar haply was displeased that Zadok was so much favoured: and might fear the fulfilling of that prophecy concerning the overthrow of Eli\u2019s house, of which he was. But what saith an ancient? Divinum consilium dum devitatur, impletur; humana sapientia, dum reluctatur, comprehenditur. {a} There are \"many devices in a man\u2019s heart: nevertheless the counsel of the [v_Pro_19_21] Lord, that shall stand.\" {#Pr 19:21} {a} Greg.\nVer.\n7. Then he made a porch for the throne.] That stately throne of ivory. {#1Ki 10:18-20} Even the porch of judgment.] Built for the conveniency of such as came to the king for judgment.\nVer."
  },
  "15": {
    "Terence E. Fretheim, Thomas B. Slater": "22\n385",
    "John Trapp": "And the king was very old. ] Yet little more than half so old as a plain countryman whom I spoke with yesterday, being May 15, A.D. 1656, at Stratford-upon-Avon, who assured me, and gave good proof of it, that he was a hundred and twenty-eight of age, being born A.D.\n15. Of eighteen cubits high apiece. ] Thirty-five cubits high, saith another prophet, { #2Ch 3:15 } that is, saith Pellican, both of them together were thirty-five cubits high, and each one almost eighteen, for which it is said to be eighteen cubits; the Scripture useth not to express such broken measures.\nVer.\n15. And the king was very old.] Yet little more than half so old as a plain countryman whom I spoke with yesterday, being May 15, A.D. 1656, at Stratford-upon-Avon, who assured me, and gave good proof of it, that he was a hundred and twenty-eight of age, being born A.D.\n15. Of eighteen cubits high apiece.] Thirty-five cubits high, saith another prophet, {#2Ch 3:15} that is, saith Pellican, both of them together were thirty-five cubits high, and each one almost eighteen, for which it is said to be eighteen cubits; the Scripture useth not to express such broken measures.\nVer."
  },
  "23": {
    "Terence E. Fretheim, Thomas B. Slater": "26\n385",
    "John Trapp": "Behold Nathan the prophet. ] Who was a privy counsellor to David `[char_David_Rut_4]`, though he had so sharply reproved him. { #2Sa 12:1-12 } He bowed himself before the king. ] Note here the exemplary modesty and submission of so great a prophet. How far from this is the false prophet of Rome!\nVer.\n23. And he made a molten sea. ] As a large laver for the priests to wash in. { #2Ch 4:6 } the Hebrews used to call the gathering together of much water a sea. It signifieth both the exceeding filthiness of sin, requiring a sea for the cleansing of it, and the infinite virtue of Christ\u2019s blood, &amp;c.\nVer.\n23. Behold Nathan the prophet.] Who was a privy counsellor to David `[char_David_Rut_4]`, though he had so sharply reproved him. {#2Sa 12:1-12} He bowed himself before the king.] Note here the exemplary modesty and submission of so great a prophet. How far from this is the false prophet of Rome!\nVer.\n23. Ver.\n23. And he made a molten sea.] As a large laver for the priests to wash in. {#2Ch 4:6} the Hebrews used to call the gathering together of much water a sea. It signifieth both the exceeding filthiness of sin, requiring a sea for the cleansing of it, and the infinite virtue of Christ\u2019s blood, &c.\nVer."
  },
  "27": {
    "Terence E. Fretheim, Thomas B. Slater": "39\n385\n8:1-13\n8:12-13\n8:25\n478\n8:48\n351\n9:4-6\n317\n9:5\n478\n9:7\n9:8-9\n160, 318\n9:8\n211, 274\n9:28\n170",
    "John Trapp": "And thou hast not showed it, &amp;c. ] See on #1Ki 1:23 .\nVer.\n27. And he made ten bases of brass. ] To bear up so many lesser layers. { #1Ki 7:38 }\nVer.\n27. And thou hast not showed it, &c.] See on #1Ki 1:\n27. And he made ten bases of brass.] To bear up so many lesser layers. {#1Ki 7:38}\nVer."
  },
  "13": {
    "Walter Brueggemann, Warren Carter": "as an emblem of pride and\narrogance. More extensively, Isaiah `[char_Isaiah_Gen_26]` 23 and Ezekiel 26\u201328 view\nTyre, later on, as a trading operation modelling autonomy, arro-\ngance, self-indulgence, and indifference to any moral, covenantal\ndimension of reality. Solomon `[char_Solomon_Ref]`\u2019s engagement with Hiram, in the\ncontext of prophetic faith, is to be viewed with deep alarm, as sure\nto distort the community.",
    "John Trapp": "Didst not thou swear\u2026unto thine handmaid? ] This was done, say the Rabbis, at that time when David `[char_David_Rut_4]` comforted Bathsheba, and went in unto her, and lay with her. { #2Sa 12:24 } Lyra saith, that then it was revealed unto him, that this son of his by Bathsheba should reign after him: this was no small comfort to her.\nVer.\n13. And king Solomon `[char_Solomon_Ref]` sent and fetched Hiram. ] He had done so long since; viz., when he first set upon temple work, { #2Ch 2:14 3:15 } to the description whereof the history here returneth.\nVer.\n13. Didst not thou swear\u2026unto thine handmaid?] This was done, say the Rabbis, at that time when David `[char_David_Rut_4]` comforted Bathsheba, and went in unto her, and lay with her. {#2Sa 12:24} Lyra saith, that then it was revealed unto him, that this son of his by Bathsheba should reign after him: this was no small comfort to her.\nVer.\n13. And king Solomon `[char_Solomon_Ref]` sent and fetched Hiram.] He had done so long since; viz., when he first set upon temple work, {#2Ch 2:14 3:15} to the description whereof the history here returneth.\nVer."
  },
  "11": {
    "Walter Brueggemann, Warren Carter": ", he accuses Israel of violating commandments and then\ntreating the temple as a place in which to hide, like \u201ca den of robbers.\u201d And in",
    "John Trapp": "Wherefore Nathan spake unto Bathsheba. ] See here, saith P. Martyr, how God by weak means confoundeth the mighty, and worketh for the accomplishment of his own will. And David `[char_David_Rut_4]` our lord knoweth it not. ] Either Adonijah\u2019s partisans and parasites kept it from David `[char_David_Rut_4]`, or else through age and weakness he took no notice of it.\nVer.\n11. And above were costly stones. ] Above ground, as well as under.\nVer.\n11. Wherefore Nathan spake unto Bathsheba.] See here, saith P. Martyr, how God by weak means confoundeth the mighty, and worketh for the accomplishment of his own will. And David `[char_David_Rut_4]` our lord knoweth it not.] Either Adonijah\u2019s partisans and parasites kept it from David `[char_David_Rut_4]`, or else through age and weakness he took no notice of it.\nVer.\n11. And above were costly stones.] Above ground, as well as under.\nVer."
  },
  "12": {
    "Walter Brueggemann, Warren Carter": ", he warns that\nthe temple in Jerusalem is not immune from the threat of Yahweh, but that in the end it will be dev-\nastated like the old shrine in the North at Shiloh. Obviously such a critique is well beyond the horizon\nof the temple texts of Solomon `[char_Solomon_Ref]`. Indeed, it may be suggested that Solomon `[char_Solomon_Ref]` introduced into Israel the\nvery understandings of the temple against which the prophets protest.",
    "John Trapp": "That thou mayest save thine own life, and the life of thy son Solomon `[char_Solomon_Ref]`. ] Which the usurper will surely take away if he carry the crown; not suffering any such rub to lie in the way, that may hinder the true running of his bowl.\nVer.\n12. And the great court round about. ] Surrounding the king\u2019s house. Both for the inward court of the house of the Lord, ] i.e., Like that inward court, #1Ki 6:36 . And for the porch, &amp;c. ] The king\u2019s house had the like porch before it, as God\u2019s house had.\nVer.\n12. That thou mayest save thine own life, and the life of thy son Solomon `[char_Solomon_Ref]`.] Which the usurper will surely take away if he carry the crown; not suffering any such rub to lie in the way, that may hinder the true running of his bowl.\nVer.\n12. And the great court round about.] Surrounding the king\u2019s house. Both for the inward court of the house of the Lord, ] i.e., Like that inward court, #1Ki 6:"
  },
  "8": {
    "John Trapp": "But Zadok the priest. ] So Cranmer and Ridley, and some few other conscientious persons, afterwards ill rewarded by Queen Mary `[char_Mary_Ref]`, refused to subscribe the letters patent for Lady Jane Gray\u2019s succession to the crown, after the death of King Edward VI; which yet were subscribed by the most of the statesmen, who were guided with respect to their particular interest, for that they were possessed of various lands which once pertained to monasteries, chanteries, &amp;c., which they foresaw they should lose, in case religion should change under Queen Mary `[char_Mary_Ref]`.\nVer.\n8. Had another court. ] Called \"the middle court.\" { #2Ki 20:4 } Like unto this porch. ] All was uniform and spacious.\nVer.\n8. But Zadok the priest.] So Cranmer and Ridley, and some few other conscientious persons, afterwards ill rewarded by Queen Mary `[char_Mary_Ref]`, refused to subscribe the letters patent for Lady Jane Gray\u2019s succession to the crown, after the death of King Edward VI; which yet were subscribed by the most of the statesmen, who were guided with respect to their particular interest, for that they were possessed of various lands which once pertained to monasteries, chanteries, &c., which they foresaw they should lose, in case religion should change under Queen Mary `[char_Mary_Ref]`.\nVer.\n8. Had another court.] Called \"the middle court.\" {#2Ki 20:4} Like unto this porch.] All was uniform and spacious.\nVer."
  },
  "14": {
    "John Trapp": "I will come in after thee, and confirm thy words, ] { a } Heb., Fill up\u2014that is, say the same, and more. There are some seeming contradictions in Scripture: and though they seem to be as the accusers of Christ, never a one speaking like the other, yet if we understand, we shall find them speaking like Nathan and Bathsheba, both speaking the same things. { a } Pollicetur suam operam in praetexenda tela.\nVer.\n14. He was a widow\u2019s son of the tribe of Naphtali. ] His father was of that tribe, but his mother of the tribe of Dan, { #2Ch 2:14 } unless the king there mistook the one tribe for the other. And cunning to work all works. ] Not in brass only, but in gold, silver, iron, stone, timber, purple, &amp;c., { #2Ch 4:16 } so that Solomon `[char_Solomon_Ref]`, for respect\u2019s sake, called him his father. { #2Ch 4:16 }\nVer.\n14. I will come in after thee, and confirm thy words, ]{ a} Heb., Fill up\u2014that is, say the same, and more. There are some seeming contradictions in Scripture: and though they seem to be as the accusers of Christ, never a one speaking like the other, yet if we understand, we shall find them speaking like Nathan and Bathsheba, both speaking the same things. {a} Pollicetur suam operam in praetexenda tela.\nVer.\n14. Ver.\n14. He was a widow\u2019s son of the tribe of Naphtali.] His father was of that tribe, but his mother of the tribe of Dan, {#2Ch 2:14} unless the king there mistook the one tribe for the other. And cunning to work all works.] Not in brass only, but in gold, silver, iron, stone, timber, purple, &c., {#2Ch 4:16} so that Solomon `[char_Solomon_Ref]`, for respect\u2019s sake, called him his father. {#2Ch 4:16}\nVer.\n14. Ver."
  },
  "16": {
    "John Trapp": "What wouldest thou? ] Heb., What to thee? q.d., I am ready to hearken to thee. She had been a good wife to him, and knew how to command him by obeying him, as Livia did Augustus, and much better. { a } For Livia, notwithstanding her smooth carriage toward her husband, is foully slandered, if she were not over familiar with Eudemus her physician, and if she did not at his death help to set him going, lest he should alter his will, and put her son Tiberius beside the empire. But good Bathsheba was none such. { b } { a } Plin. { b } Eutrop.\nVer.\n16. To set upon the tops of the pillars. ] Hence they were called chapiters, or heads, coronamenta, epistylia; crowns they are called. { #Jer 52:22 }\nVer.\n16. What wouldest thou?] Heb., What to thee? q.d., I am ready to hearken to thee. She had been a good wife to him, and knew how to command him by obeying him, as Livia did Augustus, and much better. {a} For Livia, notwithstanding her smooth carriage toward her husband, is foully slandered, if she were not over familiar with Eudemus her physician, and if she did not at his death help to set him going, lest he should alter his will, and put her son Tiberius beside the empire. But good Bathsheba was none such. {b} {a} Plin. {b} Eutrop.\nVer.\n16. To set upon the tops of the pillars.] Hence they were called chapiters, or heads, coronamenta, epistylia; crowns they are [v_Jer_52_22] called. {#Jer 52:22}\nVer."
  },
  "17": {
    "John Trapp": "Shall reign after me. ] This was the substance of the promise confirmed by oath. And he shall sit upon my throne. ] This was the evidence thereof. She allegeth both, doing as Nathan had dictated unto her.\nVer.\n17. And nets of checker work. ] These were very pleasant to the eye, and in adition significant: not such toilsome toys as nec ignoranti nocent, nec scientem iuvant. { a } { a } Sen.\nVer.\n17. Shall reign after me.] This was the substance of the promise confirmed by oath. And he shall sit upon my throne.] This was the evidence thereof. She allegeth both, doing as Nathan had dictated unto her.\nVer.\n17. And nets of checker work.] These were very pleasant to the eye, and in adition significant: not such toilsome toys as nec ignoranti nocent, nec scientem iuvant. {a} {a} Sen.\nVer."
  },
  "18": {
    "John Trapp": "And now, behold, Adonijah reigneth. ] His ambition hath turned off his obedience. Had his right to the kingdom been never so good, yet to step into the throne, while his father was yet living, without his privity and consent, was no better than treason.\nVer.\n18. And he made the pillars. ] That is, He thus decked them. Peter `[char_Peter_Mat_4]` Martyr saith that these pillars resembled a man, the nether part setting forth his feet, the second the trunk of his body, the third his head, and the fourth his hat: and that they signified God\u2019s protection over this house, as of old the pillar of fire, and pillar of smoke, showed his protection over them in the wilderness.\nVer.\n18. And now, behold, Adonijah reigneth.] His ambition hath turned off his obedience. Had his right to the kingdom been never so good, yet to step into the throne, while his father was yet living, without his privity and consent, was no better than treason.\nVer.\n18. And he made the pillars.] That is, He thus decked them. Peter `[char_Peter_Mat_4]` Martyr saith that these pillars resembled a man, the nether part setting forth his feet, the second the trunk of his body, the third his head, and the fourth his hat: and that they signified God\u2019s protection over this house, as of old the pillar of fire, and pillar of smoke, showed his protection over them in the wilderness.\nVer."
  },
  "19": {
    "John Trapp": "But Solomon `[char_Solomon_Ref]` thy servant. ] Not thy sovereign, as Adonijah affecteth to be. See on #1Ki 1:9,10 .\nVer.\n19. Were of lily work. ] As also of other flowers, leaves, and fruits, implexu coronario incursantibus. In the porch. ] That was before the holy place; for there these pillars were set, { #1Ki 7:21 } to show the stability of this house, and of the spiritual temple for ever: the Rabbis say, of the house of David `[char_David_Rut_4]`.\nVer.\n19. But Solomon `[char_Solomon_Ref]` thy servant.] Not thy sovereign, as Adonijah affecteth to be. See on #1Ki 1:9,\n19. Were of lily work.] As also of other flowers, leaves, and fruits, implexu coronario incursantibus. In the porch.] That was before the holy place; for there these pillars were set, {#1Ki 7:21} to show the stability of this house, and of the spiritual temple for ever: the Rabbis say, of the house of David `[char_David_Rut_4]`.\nVer."
  },
  "20": {
    "John Trapp": "That thou shouldest tell them, &amp;c. ] This some princes love not to do, -Queen Elizabeth for instance. A false Jesuit wrote, that she wished she might after her death hang a while in the air, to see what scuffling there would be for her kingdom. Os durum! fowl mouth!\nVer.\n20. And the pomegranates were two hundred. ] On each side a hundred, hanging down front the rows or borders upon the networks, which yet they hid not. { #2Ch 3:16 Jer 52:23 } This might signify the strengthening of our faith by the two sacraments, unto holiness and fruitfulness in good works; but especially by Christ, who is a double pillar unto his Church.\nVer.\n20. That thou shouldest tell them, &c.] This some princes love not to do, -Queen Elizabeth for instance. A false Jesuit wrote, that she wished she might after her death hang a while in the air, to see what scuffling there would be for her kingdom. Os durum! fowl mouth!\nVer.\n20. And the pomegranates were two hundred.] On each side a hundred, hanging down front the rows or borders upon the networks, which yet they hid not. {#2Ch 3:16 Jer 52:23} This might signify the strengthening of our faith by the two sacraments, unto holiness and fruitfulness in good works; but especially by Christ, who is a double pillar unto his Church.\nVer."
  },
  "21": {
    "John Trapp": "Shall be counted offenders. ] Heb., Sinners. Erimus Mamzeres -so Jerome senseth it, out of the Hebrew traditions\u2014that is, we shall be accounted bastards and infamous. It is probable that Adonijah had spoken basely of Bathsheba as an adulteress, and of Solomon `[char_Solomon_Ref]` as illegitimate, and so not fit to be king. Or by sinners here understand rebels, and public enemies.\nVer.\n21. And he set up the pillars in the porch. ] For within the temple was nothing but golden. And called the name thereof Jachin. ] As the other he called Boaz; showing not only by the matter\u2014brass\u2014but by the names of these pillars, what steadfastness the elect stand in before God, both for present and future. For present, they have strength in themselves\u2014Boaz, i.e., in it is strength; for future, God will so direct and establish them with his grace\u2014Jachin, i.e., he shall direct, or establish that they shall never wholly depart from him. \"Him that overcometh will I make a pillar in the temple of my God, and he shall go no more out.\" { #Re 3:12 }\nVer.\n21. Shall be counted offenders.] Heb., Sinners. Erimus Mamzeres -so Jerome senseth it, out of the Hebrew traditions\u2014that is, we shall be accounted bastards and infamous. It is probable that Adonijah had spoken basely of Bathsheba as an adulteress, and of Solomon `[char_Solomon_Ref]` as illegitimate, and so not fit to be king. Or by sinners here understand rebels, and public enemies.\nVer.\n21. And he set up the pillars in the porch.] For within the temple was nothing but golden. And called the name thereof Jachin.] As the other he called Boaz; showing not only by the matter\u2014brass\u2014but by the names of these pillars, what steadfastness the elect stand in before God, both for present and future. For present, they have strength in themselves\u2014 Boaz, i.e., in it is strength; for future, God will so direct and establish them with his grace\u2014Jachin, i.e., he shall direct, or establish that they shall never wholly depart from him. \"Him that overcometh will I make a pillar in the temple of my God, and he [v_Rev_3_12] shall go no more out.\" {#Re 3:12}\nVer."
  },
  "22": {
    "John Trapp": "Nathan the prophet also came in. ] And so Bathsheba went out, { #1Ki 1:28 } that it might not appear to be a plot betwixt them.\nVer.\n22. And upon the pillars was lily work ] To show the beauty and sweetness of Christ and his people, those especially that are more eminent, the glory of the churches; such as were James, Cephas, and John `[char_John_Ref]`, who \"seemed to be pillars.\" { #Ga 2:9 }\nVer.\n22. Nathan the prophet also came in.] And so Bathsheba went out, {#1Ki 1:28} that it might not appear to be a plot betwixt them.\nVer.\n22. Ver.\n22. And upon the pillars was lily work] To show the beauty and sweetness of Christ and his people, those especially that are more eminent, the glory of the churches; such as were James, [v_Gal_2_9] Cephas, and John `[char_John_Ref]`, who \"seemed to be pillars.\" {#Ga 2:9}\nVer."
  },
  "24": {
    "John Trapp": "Hast thou said? ] q.d., I think not. Exordium ex abrupto, per admirationem.\nVer.\n24. Ten in a cubit. ] Three hundred knops under the lily work, on the brim of the sea. { #2Ch 4:3 }\nVer.\n24. Hast thou said?] q.d., I think not. Exordium ex abrupto, per admirationem.\nVer.\n24. Ten in a cubit.] Three hundred knops under the lily work, on the brim of the sea. {#2Ch 4:3}\nVer."
  },
  "25": {
    "John Trapp": "And hath slain oxen and fat cattle. ] See on #1Ki 1:14 .\nVer.\n25. It stood upon twelve oxen. ] Figuring out the twelve apostles and their successors, who went into all parts of the world, teaching \"the baptism of repentance for the remission of sins.\"\nVer.\n25. And hath slain oxen and fat cattle.] See on #1Ki 1:\n25. It stood upon twelve oxen.] Figuring out the twelve apostles and their successors, who went into all parts of the world, teaching \"the baptism of repentance for the remission of sins.\"\nVer."
  },
  "26": {
    "John Trapp": "But me, even me. ] As some useless person, as an \u03bf\u03c5\u03c4\u03b9\u03b4\u03b1\u03bd\u03bf\u03c2 , as if I were no prophet of the Lord, or as if there were not a woe to such rebellious children as \"take counsel, but not of God; and cover with a covering, but not of his Spirit, that they may add sin to sin.\" { #Isa 30:1 }\nVer.\n26. It contained two thousand baths. ] This it held ordinarily; but if filled up to the brim, it could hold three thousand baths. { #2Ch 4:5 } Out of this molten sea, or lake\u2014as Junius rendereth it\u2014the priests, by cocks or otherwise, drew water to wash themselves and other things with.\nVer.\n26. But me, even me.] As some useless person, as an \u03bf\u03c5\u03c4\u03b9\u03b4\u03b1\u03bd\u03bf\u03c2, as if I were no prophet of the Lord, or as if there were not a woe to such rebellious children as \"take counsel, but not of God; and cover with a covering, but not of his Spirit, that they may [v_Isa_30_1] add sin to sin.\" {#Isa 30:1}\nVer.\n26. It contained two thousand baths.] This it held ordinarily; but if filled up to the brim, it could hold three thousand baths. {#2Ch 4:5} Out of this molten sea, or lake\u2014as Junius rendereth it\u2014the priests, by cocks or otherwise, drew water to wash themselves and other things with.\nVer."
  },
  "28": {
    "John Trapp": "Call me Bathsheba. ] See on #1Ki 1:22 .\nVer.\n28. They had borders. ] Around the vessel, like panes of wainscotting; whereon were engraven lions, oxen, and cherubims; to teach the priests courage, painfulness, and prudence.\nVer.\n28. Call me Bathsheba.] See on #1Ki 1:\n28. They had borders.] Around the vessel, like panes of wainscotting; whereon were engraven lions, oxen, and cherubims; to teach the priests courage, painfulness, and prudence.\nVer.\n28. Ver."
  },
  "30": {
    "John Trapp": "Even so will I certainly do this day. ] Before tomorrow: for the business requireth expedition, since, \u201c sero medicina paratur, Cum mala per longas invaluere moras.\u2019\u2019\u2014Ovid.\nVer.\n30. And every base had four brazen wheels. ] To remove the laver from place to place, as occasion required.\nVer.\n30. Even so will I certainly do this day.] Before tomorrow: for the business requireth expedition, since, \u201c sero medicina paratur, Cum mala per longas invaluere moras.\u2019\u2019\u2014Ovid.\nVer.\n30. And every base had four brazen wheels.] To remove the laver from place to place, as occasion required.\nVer.\n30. Ver."
  },
  "31": {
    "John Trapp": "Let my lord king David `[char_David_Rut_4]` live for ever, ] i.e., Let him live his utmost. Agrippina hastened her husband Claudius the emperor\u2019s death, that her son Nero might succeed: yea, she cried out Occidar, modo imperet. But good Bathsheba was not so hasty.\nVer.\n31. And the mouth of it within the chapiter. ] The round hollow place of the base, into which the lower part of the laver was put to the upper, was a cubit.\nVer.\n31. Let my lord king David `[char_David_Rut_4]` live for ever, ] i.e., Let him live his utmost. Agrippina hastened her husband Claudius the emperor\u2019s death, that her son Nero might succeed: yea, she cried out Occidar, modo imperet. But good Bathsheba was not so hasty.\nVer.\n31. And the mouth of it within the chapiter.] The round hollow place of the base, into which the lower part of the laver was put to the upper, was a cubit.\nVer."
  },
  "32": {
    "John Trapp": "And Nathan the prophet. ] So far was David `[char_David_Rut_4]` from hatred of truth, that he loved Nathan the better for his plain dealing while he lived, gave him free access to his bedchamber, and now nameth him a commissioner for the declaring of his successor.\nVer.\n32. And under the borders were four wheels. ] Whereby the laver was trusatile sive ambulatorium. See #1Ki 7:30 .\nVer.\n32. And Nathan the prophet.] So far was David `[char_David_Rut_4]` from hatred of truth, that he loved Nathan the better for his plain dealing while he lived, gave him free access to his bedchamber, and now nameth him a commissioner for the declaring of his successor.\nVer.\n32. And under the borders were four wheels.] Whereby the laver was trusatile sive ambulatorium. See #1Ki 7:"
  },
  "33": {
    "John Trapp": "Take with you the servants of your lord. ] My guard, and the garrison soldiers that are at hand. To ride upon mine own mule. ] In token that I have transferred upon him the royal dignity. { #Es 6:8 } And bring him down to Gihon. ] The Chaldee hath it, To Siloe, where the waters ran softly and constantly. Hereby, saith Martyr, David `[char_David_Rut_4]` would set forth his desire that Solomon `[char_Solomon_Ref]`\u2019s reign might be mild and moderate, as also perpetuum et perenne, durable and longlasting.\nVer.\n33. Like the work of a chariot wheel, ] i.e., Curiously wrought, and as having axle-tree, naves, felloes, spokes, all cast together in their moulds.\nVer.\n33. Take with you the servants of your lord.] My guard, and the garrison soldiers that are at hand. To ride upon mine own mule.] In token that I have transferred [v_Est_6_8] upon him the royal dignity. {#Es 6:8} And bring him down to Gihon.] The Chaldee hath it, To Siloe, where the waters ran softly and constantly. Hereby, saith Martyr, David `[char_David_Rut_4]` would set forth his desire that Solomon `[char_Solomon_Ref]`\u2019s reign might be mild and moderate, as also perpetuum et perenne, durable and longlasting.\nVer.\n33. Ver.\n33. Like the work of a chariot wheel, ] i.e., Curiously wrought, and as having axle-tree, naves, felloes, spokes, all cast together in their moulds.\nVer."
  },
  "34": {
    "John Trapp": "And let Zadok the priest and Nathan the prophet. ] That the young king might learn betime to hearken to such, and to give them all due respect.\nVer.\n34. And there were four undersetters. ] Heb., Shoulders, sc., to uphold the vessel.\nVer.\n34. And let Zadok the priest and Nathan the prophet.] That the young king might learn betime to hearken to such, and to give them all due respect.\nVer.\n34. And there were four undersetters.] Heb., Shoulders, sc., to uphold the vessel.\nVer."
  },
  "35": {
    "John Trapp": "For he shall be king in my stead. ] The son of our King Henry II was crowned king by his father, who at his coronation renounced the name of a king for that day, and as sewer served at that table. But this young king was so puffed up with his new dignity, that he soon bore arms against his father; and dying of discontent before his father, got not so much by his coronation as to have a name in the catalogue of the kings of England. But Solomon `[char_Solomon_Ref]` had learned better things both of his father { #Pr 4:4 } and mother, { #Pr 31:10-31 } and tutor Nathan.\nVer.\n35. Was there a round compass. ] Which was made, it should seem, to receive the water which came out at the cocks.\nVer.\n35. For he shall be king in my stead.] The son of our King Henry II was crowned king by his father, who at his coronation renounced the name of a king for that day, and as sewer served at that table. But this young king was so puffed up with his new dignity, that he soon bore arms against his father; and dying of discontent before his father, got not so much by his coronation as to have a name in the catalogue of the kings of England. But Solomon `[char_Solomon_Ref]` [v_Pro_4_4] had learned better things both of his father {#Pr 4:4} and mother, {#Pr 31:10-31} and tutor Nathan.\nVer.\n35. Was there a round compass.] Which was made, it should seem, to receive the water which came out at the cocks.\nVer."
  },
  "37": {
    "John Trapp": "And make his throne greater. ] God heard this prayer, and said Amen to it, set his fiat to it: for Solomon `[char_Solomon_Ref]`\u2019s reign, accomplished with a civil and religious happiness, represented the triumphant Church in heaven: as David `[char_David_Rut_4]`\u2019s reign had been a figure of the Church militant upon earth.\nVer.\n37. All of them had one casting. ] To teach uniformity about the things of God. It is a sweet thing when \"with one mind and one mouth God is glorified\" as \"the Father of our Lord Jesus `[char_Jesus_Ref]` Christ,\" { #Ro 15:6 } and men\u2019s prayers come before him \"as the sound of many waters.\"\nVer.\n37. And make his throne greater.] God heard this prayer, and said Amen to it, set his fiat to it: for Solomon `[char_Solomon_Ref]`\u2019s reign, accomplished with a civil and religious happiness, represented the triumphant Church in heaven: as David `[char_David_Rut_4]`\u2019s reign had been a figure of the Church militant upon earth.\nVer.\n37. All of them had one casting.] To teach uniformity about the things of God. It is a sweet thing when \"with one mind and one mouth God is glorified\" as \"the Father of our Lord Jesus `[char_Jesus_Ref]` Christ,\" {#Ro 15:6} and men\u2019s prayers come before him \"as the sound of many waters.\"\nVer."
  },
  "38": {
    "John Trapp": "And brought him to Gihon. ] See on #1Ki 1:33 .\nVer.\n38. Then made he ten lavers of brass. ] And all to show the filthiness of sin, and the necessity of Christ\u2019s blood, { #1Jo 1:7 Zec 13:1 } wherewith the holy priesthood of his chosen must be washed and sanctified in action and affection, before their service can be accepted. { #Eph 5:26 }\nVer.\n38. And brought him to Gihon.] See on #1Ki 1:\n38. Then made he ten lavers of brass.] And all to show the filthiness of sin, and the necessity of Christ\u2019s blood, {#1Jo 1:7 Zec 13:1} wherewith the holy priesthood of his chosen must be washed and sanctified in action and affection, before their service can be [v_Eph_5_26] accepted. {#Eph 5:26}\nVer."
  },
  "39": {
    "John Trapp": "Took an horn of oil. ] Whereof there was great use in the tabernacle. It was not that holy oil which was at first provided for the anointing of the priests, { see #Ex 30:32 , \"Upon man\u2019s flesh shall it not be poured\" } but some other, to show that magistrates should be holy and gracious: whence also the seat of judicature is called the holy place. { #Ec 8:10 } And anointed Solomon `[char_Solomon_Ref]`. ] When he was twenty years of age, saith Lyra: some say twenty-four. God save king Solomon `[char_Solomon_Ref]`, ] i.e., Rex Pacificus: so the Greeks had their Irenaei, the Germans their Fredericks, (that is, rich in peace,) and the Turks their Selims and Solymans.\nVer.\n39. On the right side of the house. ] That is, Of the priests\u2019 court, who had hereby plenty of water, wherein they might wash so soon as they entered to minister in the holy place. \"Holiness becometh God\u2019s house for ever.\"\nVer.\n39. Took an horn of oil.] Whereof there was great use in the tabernacle. It was not that holy oil which was at first provided for [v_Exo_30_32] the anointing of the priests, {see #Ex 30:32, \"Upon man\u2019s flesh shall it not be poured\"} but some other, to show that magistrates should be holy and gracious: whence also the seat of judicature is called the holy place. [v_Ecc_8_10] {#Ec 8:10} And anointed Solomon `[char_Solomon_Ref]`.] When he was twenty years of age, saith Lyra: some say twenty-four. God save king Solomon `[char_Solomon_Ref]`, ] i.e., Rex Pacificus: so the Greeks had their Irenaei, the Germans their Fredericks, (that is, rich in peace,) and the Turks their Selims and Solymans.\nVer.\n39. On the right side of the house.] That is, Of the priests\u2019 court, who had hereby plenty of water, wherein they might wash so soon as they entered to minister in the holy place. \"Holiness becometh God\u2019s house for ever.\"\nVer."
  },
  "40": {
    "John Trapp": "Piped with pipes. ] Or, Flutes; that Adonijah\u2019s party might hear and be startled with those noises, which at once proclaimed Solomon `[char_Solomon_Ref]`\u2019s triumph, and their confusion. And rejoiced with great joy. ] By the special operation of God\u2019s Spirit, { see #1Ch 12:40 } and to shadow forth the great joy which the saints should take in the kingdom of Christ. { #Zec 9:9 } So that the earth rent. ] After a sort, with their loud acclamations, Hyperbole sumpta a fragoris similitudine.\nVer.\n40. And the shovels. ] Which were to gather up the ashes, and to carry coals from the altar to put into the censers in the temple, for the incense. And the basons. ] Which were to receive the blood of the sacrifices, and the drink offerings.\nVer.\n40. Piped with pipes.] Or, Flutes; that Adonijah\u2019s party might hear and be startled with those noises, which at once proclaimed Solomon `[char_Solomon_Ref]`\u2019s triumph, and their confusion. And rejoiced with great joy.] By the special operation of God\u2019s Spirit, {see #1Ch 12:40} and to shadow forth the great joy which the [v_Zec_9_9] saints should take in the kingdom of Christ. {#Zec 9:9} So that the earth rent.] After a sort, with their loud acclamations, Hyperbole sumpta a fragoris similitudine.\nVer.\n40. And the shovels.] Which were to gather up the ashes, and to carry coals from the altar to put into the censers in the temple, for the incense. And the basons.] Which were to receive the blood of the sacrifices, and the drink offerings.\nVer."
  },
  "41": {
    "John Trapp": "As they had made an end of eating. ] Ever after the meal is ended, comes the reckoning. Adonijah\u2019s feast, as all wicked men\u2019s, endeth in horror; for the last dish, is served up astonishment and fearful expectation of just revenge. So doth the wise and just God befool proud and insolent sinners in those secret plots wherein they hope to undermine the son of David `[char_David_Rut_4]`, the Prince of peace.\nVer.\n41. Here is a recapitulation of the forementioned particulars; whereunto Josephus addeth many more; as ten thousand golden tables, ten thousand golden candlesticks, twenty thousand vials of gold, forty thousand of silver, &amp;c.\nVer.\n41. As they had made an end of eating.] Ever after the meal is ended, comes the reckoning. Adonijah\u2019s feast, as all wicked men\u2019s, endeth in horror; for the last dish, is served up astonishment and fearful expectation of just revenge. So doth the wise and just God befool proud and insolent sinners in those secret plots wherein they hope to undermine the son of David `[char_David_Rut_4]`, the Prince of peace.\nVer.\n41. Here is a recapitulation of the forementioned particulars; whereunto Josephus addeth many more; as ten thousand golden tables, ten thousand golden candlesticks, twenty thousand vials of gold, forty thousand of silver, &c.\nVer."
  },
  "42": {
    "John Trapp": "And bringest good tidings. ] So Adonijah would have had it; but the expectation of the wicked shall perish; when they are at the height of their joys and hopes, God oft confoundeth all their devices, and layeth them open to the scorn of the world, and to the anguish of their own guilty hearts.\nVer.\n42. See Trapp on \"1Ki 7:41\" .\nVer.\n42. And bringest good tidings.] So Adonijah would have had it; but the expectation of the wicked shall perish; when they are at the height of their joys and hopes, God oft confoundeth all their devices, and layeth them open to the scorn of the world, and to the anguish of their own guilty hearts.\nVer.\n42. See Trapp on \"1Ki 7:41\".\nVer."
  },
  "43": {
    "John Trapp": "Verily our lord king David `[char_David_Rut_4]`, ] q.d., Good news say you? truly not so good as you think, for all is like to be nought on your side: Postea nullus eris. Afterward it will be nothing.\nVer.\n43. See Trapp on \"1Ki 7:41\" .\nVer.\n43. Verily our lord king David `[char_David_Rut_4]`, ] q.d., Good news say you? truly not so good as you think, for all is like to be nought on your side: Postea nullus eris. Afterward it will be nothing.\nVer.\n43. See Trapp on \"1Ki 7:41\".\nVer."
  },
  "44": {
    "John Trapp": "And the king hath sent with him Zadok. ] All this relation was to Adonijah and his guests, as those knuckles of a man\u2019s hand were to Belshazzar, to write them their destiny; or as Daniel was to him, to read it unto them.\nVer.\n44. See Trapp on \"1Ki 7:41\" .\nVer.\n44. And the king hath sent with him Zadok.] All this relation was to Adonijah and his guests, as those knuckles of a man\u2019s hand were to Belshazzar, to write them their destiny; or as Daniel was to him, to read it unto them.\nVer.\n44. See Trapp on \"1Ki 7:41\".\nVer."
  },
  "45": {
    "John Trapp": "This is the noise that ye have heard. ] A doleful knell to those who had feasted and boasted themselves in a jocund security and promise of success. \"A dreadful sound is in their ears: in prosperity the destroyer cometh upon them. Trouble and anguish maketh them afraid, whilst they prevail against them as a king ready to the battle.\" { #Job 15:21,24 }\nVer.\n45. See Trapp on \"1Ki 7:41\" .\nVer.\n45. This is the noise that ye have heard.] A doleful knell to those who had feasted and boasted themselves in a jocund security and promise of success. \"A dreadful sound is in their ears: in prosperity the destroyer cometh upon them. Trouble and anguish maketh them afraid, whilst they prevail against them as a king [v_Job_15_21] ready to the battle.\" {#Job 15:21,24}\nVer.\n45. See Trapp on \"1Ki 7:41\".\nVer."
  },
  "46": {
    "John Trapp": "And also Solomon `[char_Solomon_Ref]` sitteth. ] He is in actual possession, and therefore you are lost. Every man is either a king or a captive; Aut Caesar, aut nullus. Either Caesar or no one. Every man, saith Augustine, shall either reign with Christ, or be damned with the devil.\nVer.\n46. In the plain of Jordon. ] Where Christ afterwards was baptized; to show, saith an expositor, that by these lavers and vessels there cast, baptism was prefigured. In the clay ground. ] Which was most fit for moulds.\nVer.\n46. And also Solomon `[char_Solomon_Ref]` sitteth.] He is in actual possession, and therefore you are lost. Every man is either a king or a captive; Aut Caesar, aut nullus. Either Caesar or no one. Every man, saith Augustine, shall either reign with Christ, or be damned with the devil.\nVer.\n46. In the plain of Jordon.] Where Christ afterwards was baptized; to show, saith an expositor, that by these lavers and vessels there cast, baptism was prefigured. In the clay ground.] Which was most fit for moulds.\nVer."
  },
  "47": {
    "John Trapp": "Better than thy name, and his throne greater. ] This wish of his servants was no grief of heart to the old king, but a matter of joy. So they prayed for Hector\u2019s son in Homer, \u201c \u03c0\u03b1\u03c4\u03c1\u03bf\u03c2 \u03b4 \u03bf\u03b3\u03b5 \u03c0\u03bf\u03bb\u03bb\u03bf\u03bd \u03b1\u03bc\u03b5\u03b9\u03bd\u03c9\u03bd. \u201d And Claudian thus bespeaketh Honorius the emperor\u2014 \u201c Aspice, completur votum; iam natus adaequat Te meritis, et quod magis est optabile, vincit.\u201d And the king bowed himself upon the bed. ] Worshipping God, as #Ge 47:31 , and joining in prayer with his servants for his son. Some think he bowed himself to his son now crowned king: what, then, would he have done to his Lord, if present?, { #Ps 110:1 } quos non honores in illum supplex ac venerabundus certatim contulisset? { a } { a } Bucholcer.\nVer.\n47. Solomon `[char_Solomon_Ref]` left all the vessels unweighed. ] Many men deal with their preservations, saith one, as Solomon `[char_Solomon_Ref]` did with the brass of the temple: it was so much, he weighed it not. See #1Ch 22:3,14 .\nVer.\n47. Better than thy name, and his throne greater.] This wish of his servants was no grief of heart to the old king, but a matter of joy. So they prayed for Hector\u2019s son in Homer, \u201c\u03c0\u03b1\u03c4\u03c1\u03bf\u03c2 \u03b4 \u03bf\u03b3\u03b5 \u03c0\u03bf\u03bb\u03bb\u03bf\u03bd \u03b1\u03bc\u03b5\u03b9\u03bd\u03c9\u03bd.\u201d And Claudian thus bespeaketh Honorius the emperor\u2014 \u201c Aspice, completur votum; iam natus adaequat Te meritis, et quod magis est optabile, vincit.\u201d And the king bowed himself upon the bed.] Worshipping God, as [v_Gen_47_31] #Ge 47:31, and joining in prayer with his servants for his son. Some think he bowed himself to his son now crowned king: what, then, would [v_Psa_110_1] he have done to his Lord, if present?, {#Ps 110:1} quos non honores in illum supplex ac venerabundus certatim contulisset? {a} {a} Bucholcer.\nVer.\n47. Solomon `[char_Solomon_Ref]` left all the vessels unweighed.] Many men deal with their preservations, saith one, as Solomon `[char_Solomon_Ref]` did with the brass of the temple: it was so much, he weighed it not. See #1Ch 22:3,"
  },
  "48": {
    "John Trapp": "To sit on my throne this day. ] Nevertheless David `[char_David_Rut_4]` did not during his life wholly lay aside the kingly power; but gave it to his son whilst he was yet alive.\nVer.\n48. The altar of gold, and the table of gold. ] Yea, tables, as it is in #2Ch 4:19 , ten tables for one made by Moses `[char_Moses_Exo_2]`; to set forth the superabundant grace under Christ, figured by Solomon `[char_Solomon_Ref]`.\nVer.\n48. To sit on my throne this day.] Nevertheless David `[char_David_Rut_4]` did not during his life wholly lay aside the kingly power; but gave it to his son whilst he was yet alive.\nVer.\n48. The altar of gold, and the table of gold.] Yea, tables, as it is in #2Ch 4:19, ten tables for one made by Moses `[char_Moses_Exo_2]`; to set forth the superabundant grace under Christ, figured by Solomon `[char_Solomon_Ref]`.\nVer."
  },
  "49": {
    "John Trapp": "And all the guests. ] Who had now nothing so good cheer as Solomon `[char_Solomon_Ref]`\u2019s guests, praise at parting; those that erewhile fed without fear, are now in great horror, the traitor\u2019s raced. Were afraid, and rose up, and went, &amp;c. ] Here is \u03c4\u03c1\u03bf\u03c0\u03bf\u03c2 \u03ba\u03b1\u03b9 \u03c4\u03bf\u03c0\u03bf\u03c2 , quo loco et quomodo diffugerint, how and whither they slunk away.\nVer.\n49. With the flowers and the lamps. ] The ornaments and the instruments thereof. Here some note that every table had its candlestick for light, to show that unless light from above goeth along with every ordinance appointed for the feeding of men\u2019s souls, it will be to them of no advantage.\nVer.\n49. And all the guests.] Who had now nothing so good cheer as Solomon `[char_Solomon_Ref]`\u2019s guests, praise at parting; those that erewhile fed without fear, are now in great horror, the traitor\u2019s raced. Were afraid, and rose up, and went, &c.] Here is \u03c4\u03c1\u03bf\u03c0\u03bf\u03c2 \u03ba\u03b1\u03b9 \u03c4\u03bf\u03c0\u03bf\u03c2, quo loco et quomodo diffugerint, how and whither they slunk away.\nVer.\n49. With the flowers and the lamps.] The ornaments and the instruments thereof. Here some note that every table had its candlestick for light, to show that unless light from above goeth along with every ordinance appointed for the feeding of men\u2019s souls, it will be to them of no advantage.\nVer."
  },
  "50": {
    "John Trapp": "On the horns of the altar. ] Which hitherto, haply, he had despised.\nVer.\n50. And the hinges of gold. ] Hinges and hooks, and all were of gold: to teach us that in a holy and religious soul dedicated to God, there should be nothing found but what is pure, solid, and precious. \"The tongue of the just is as choice silver; the heart of the wicked is little worth.\" { #Pr 10:20 }\nVer.\n50. On the horns of the altar.] Which hitherto, haply, he had despised.\nVer.\n50. And the hinges of gold.] Hinges and hooks, and all were of gold: to teach us that in a holy and religious soul dedicated to God, there should be nothing found but what is pure, solid, and precious. \"The tongue of the just is as choice silver; the heart of the [v_Pro_10_20] wicked is little worth.\" {#Pr 10:20}\nVer."
  },
  "51": {
    "John Trapp": "Hath caught hold on the horns. ] Hither fled malefactors, as to a place of security, { #Ex 21:14 } though there was no law for it.\nVer.\n51. So was ended all the work. ] Solomon `[char_Solomon_Ref]`\u2019s temple was finished in the year of the world three thousand. Hence some gather that the spiritual temple shall be consummated in three thousand more. Christ was born in the four thousandth year of the world. The temple was destroyed together with the city by the Romans, in the year of the world exactly four thousand and seventy-three. { a } The things which David `[char_David_Rut_4]` his father had dedicated. ] Partita factas partita infectas, quae ex opere superfuerant. For that of the Rabbis is not likely to be true\u2014viz., that Solomon `[char_Solomon_Ref]` made no use of the treasure gathered by his father, as not worthy, but only of that which himseff had gotten together in those four years. { a } Ussher.\n51. Hath caught hold on the horns.] Hither fled malefactors, [v_Exo_21_14] as to a place of security, {#Ex 21:14} though there was no law for it.\nVer.\n51. So was ended all the work.] Solomon `[char_Solomon_Ref]`\u2019s temple was finished in the year of the world three thousand. Hence some gather that the spiritual temple shall be consummated in three thousand more. Christ was born in the four thousandth year of the world. The temple was destroyed together with the city by the Romans, in the year of the world exactly four thousand and seventy-three. {a} The things which David `[char_David_Rut_4]` his father had dedicated.] Partita factas partita infectas, quae ex opere superfuerant. For that of the Rabbis is not likely to be true\u2014viz., that Solomon `[char_Solomon_Ref]` made no use of the treasure gathered by his father, as not worthy, but only of that which himseff had gotten together in those four years. {a} Ussher."
  },
  "1": {
    "John Trapp": "But Solomon `[char_Solomon_Ref]` was building his own house. ] Here he took greater leisure, and had less help, both for materials ready prepared, and for the people\u2019s forwardness to help it on. Add hereunto, that in these thirteen years Solomon `[char_Solomon_Ref]` had three houses to build; sc., his own, the queen\u2019s, and the house of the forest of Lebanon: which, because they stood near together, were called Solomon `[char_Solomon_Ref]`\u2019s own house, or palace royal.\nVer.\n1. But Solomon `[char_Solomon_Ref]` was building his own house.] Here he took greater leisure, and had less help, both for materials ready prepared, and for the people\u2019s forwardness to help it on. Add hereunto, that in these thirteen years Solomon `[char_Solomon_Ref]` had three houses to build; sc., his own, the queen\u2019s, and the house of the forest of Lebanon: which, because they stood near together, were called Solomon `[char_Solomon_Ref]`\u2019s own house, or palace royal.\nVer."
  }
});
