bible_loader.load_commentary(14, 18, {
  "6": {
    "Commentary Vol. 2": "Ver. 6-",
    "John Trapp": "Ver."
  },
  "12": {
    "Commentary Vol. 2": "And Baalath, etc.] (see <110918>1 Kings 9:18). From hence, to the\n[v_2Ch_8_11] end of (<140811>2 Chronicles 8:11), it is the same with (<110919>1 Kings 9:19-24).\n[v_1Ki_9_19] [v_1Ki_9_20] [v_1Ki_9_21] [v_1Ki_9_22] [v_1Ki_9_23] [v_1Ki_9_24] (See Gill on \u201c<110919>1 Kings 9:19-24\u201d).\nVer.\n12. Then Solomon `[char_Solomon_Ref]` offered burnt offerings to the Lord, etc.] Meaning\nnot barely at the time he rebuilt the above cities, for it was his constant\npractice:\non the altar of the Lord, which he had built before the porch; the brasen\naltar, which was at the entrance into the temple, within the court; of which\n[v_2Ch_4_1] (see <140401>2 Chronicles 4:1).\nVer.",
    "John Trapp": "With as much confidence as Jesuits offer to pawn their souls for the truth of their assertions, and tell us, that if we be not damned, they will be damned for us. Event, the master of fools, confuted these bold affirmers.\nVer."
  },
  "13": {
    "Commentary Vol. 2": "Even after a certain rate every day, according to the\ncommandment of Moses `[char_Moses_Exo_2]`, etc.] The daily sacrifice, morning and evening,\n[v_Exo_29_38] (<022938>Exodus 29:38,39),\non the sabbaths, and on the new moons; when there were additional\n[v_Num_28_9] sacrifices, (<042809>Numbers 28:9), etc.\nand on the solemn feasts three times in the year, [even] in the feast of\nunleavened bread, and in the feast of weeks, and in the feast of\n[v_1Ki_9_25] tabernacles; which serves to explain the three times in (<110925>1 Kings 9:25).\nVer.",
    "John Trapp": "Even what my God saith. ] His God he calleth him, though he had suffered for God, and was like to suffer more for his veracity. He would not budge\u2014as Ecebolius and other timeservers did\u2014for any man\u2019s pleasure or displeasure.\nVer.\n13. Even what my God saith.] His God he calleth him, though he had suffered for God, and was like to suffer more for his veracity. He would not budge\u2014as Ecebolius and other timeservers did\u2014for any man\u2019s pleasure or displeasure.\nVer."
  },
  "14": {
    "Commentary Vol. 2": "And he appointed, according to the order of David `[char_David_Rut_4]` his father, the\ncourses of the priests to their service, etc.] The twenty four courses which\n[v_1Ch_24_1] [v_1Ch_24_2] [v_1Ch_24_3] [v_1Ch_24_4] [v_1Ch_24_5] [v_1Ch_24_6] [v_1Ch_24_7] [v_1Ch_24_8] [v_1Ch_24_9] [v_1Ch_24_10] [v_1Ch_24_11] [v_1Ch_24_12] [v_1Ch_24_13] [v_1Ch_24_14] [v_1Ch_24_15] [v_1Ch_24_16] [v_1Ch_24_17] [v_1Ch_24_18] [v_1Ch_24_19] [v_1Ch_24_20] [v_1Ch_24_21] [v_1Ch_24_22] [v_1Ch_24_23] [v_1Ch_24_24] [v_1Ch_24_25] [v_1Ch_24_26] [v_1Ch_24_27] [v_1Ch_24_28] [v_1Ch_24_29] [v_1Ch_24_30] [v_1Ch_24_31] served weekly in their turns, (<132401>1 Chronicles 24:1-31)\nand the Levites to their charges, to praise and minister before the priests,\nas duty of every day required; who also had their courses by lot, to sing\nthe praises of God, when the priests sacrificed, or blew the trumpets, (<132501>1\nChronicles 25:1-31),\nthe porters also by their courses at every gate; from hence Dr. Lightfoot\nconcludes that these were divided into twenty four classes, as the priests\nand Levite singers were:\n[v_1Ch_26_1] [v_1Ch_26_2] [v_1Ch_26_3] [v_1Ch_26_4] [v_1Ch_26_5] [v_1Ch_26_6] [v_1Ch_26_7] [v_1Ch_26_8] [v_1Ch_26_9] [v_1Ch_26_10] [v_1Ch_26_11] [v_1Ch_26_12] [v_1Ch_26_13] [v_1Ch_26_14] [v_1Ch_26_15] [v_1Ch_26_16] [v_1Ch_26_17] [v_1Ch_26_18] [v_1Ch_26_19] [v_1Ch_26_20] [v_1Ch_26_21] [v_1Ch_26_22] [v_1Ch_26_23] [v_1Ch_26_24] [v_1Ch_26_25] [v_1Ch_26_26] [v_1Ch_26_27] [v_1Ch_26_28] [v_1Ch_26_29] [v_1Ch_26_30] [v_1Ch_26_31] [v_1Ch_26_32] for so had David `[char_David_Rut_4]` the man of God commanded, (<132601>1 Chronicles 26:1-32),\nwho in all these affairs acted as a prophet, under the inspiration and\ndirection of the Holy Spirit of God."
  },
  "17": {
    "Commentary Vol. 2": "Ganz. Tzemach David `[char_David_Rut_4]`, par. 1. fol. 12."
  },
  "1": {
    "John Trapp": "Now Jehoshaphat had riches in abundance. ] Stultitiam patiuntur opes. He was the worse for his wealth\u2014as most men also are, -else he had not been so fond of this new affinity with Ahab. { #2Ki 8:18 }\nVer.\n1. Now Jehoshaphat had riches in abundance.] Stultitiam patiuntur opes. He was the worse for his wealth\u2014as most men also are, -else he had not been so fond of this new affinity with Ahab. {#2Ki 8:18}\nVer."
  },
  "2": {
    "John Trapp": "He went down to Ahab to Samaria. ] See #1Ki 22:2 , in which chapter we have the same history related as here, not abridged\u2014as is usual with this author\u2014-but at large; this much commendeth it unto us as necessary and profitable, since the Holy Ghost doth nothing in vain. And Ahab killed sheep and oxen. ] As to feast him and his retinue, so, haply, to sacrifice to the gods, as idolaters used to do when great strangers came unto them. Dido did so when \u00c6neas came to her court. \u201c Simul Aeneam in regia ducit Tecta, simul divum templis indicit honorem.\u2019\u2019\u2014Aeneid, lib. i. Now Jezebel was Dido\u2019s countrywoman, and had a great influence upon her husband Ahab.\nVer.\n2. He went down to Ahab to Samaria.] See #1Ki 22:2, in which chapter we have the same history related as here, not abridged\u2014as is usual with this author\u2014-but at large; this much commendeth it unto us as necessary and profitable, since the Holy Ghost doth nothing in vain. And Ahab killed sheep and oxen.] As to feast him and his retinue, so, haply, to sacrifice to the gods, as idolaters used to do when great strangers came unto them. Dido did so when \u00c6neas came to her court. \u201c Simul Aeneam in regia ducit Tecta, simul divum templis indicit honorem.\u2019\u2019\u2014Aeneid, lib. i. Now Jezebel was Dido\u2019s countrywoman, and had a great influence upon her husband Ahab.\nVer."
  },
  "3": {
    "John Trapp": "I am as thou art. ] See #1Ki 22:4 . Jehoshaphat was too facile. It was noted as a fault in Henry IV of France that he was aeque male ac bono reconciliabilis, of too good a nature, as we say of some.\nVer.\n3. I am as thou art.] See #1Ki 22:"
  },
  "4": {
    "John Trapp": "Inquire, I pray thee, of the Lord today. ] Yea, but this should have been done before he had engaged to go. Good Jehoshaphat is oft taxed for being smart too late. Few consider that it is better to stop or step back than to run on out of the way.\nVer.\n4. Jehoshaphat was too facile. It was noted as a fault in Henry IV of France that he was aeque male ac bono reconciliabilis, of too good a nature, as we say of some.\nVer.\n4. Inquire, I pray thee, of the Lord today.] Yea, but this should have been done before he had engaged to go. Good Jehoshaphat is oft taxed for being smart too late. Few consider that it is better to stop or step back than to run on out of the way.\nVer."
  },
  "5": {
    "John Trapp": "Four hundred prophets. ] An ecumenical council. See on #1Ki 2:6 .\nVer.\n5. Four hundred prophets.] An ecumenical council. See on #1Ki 2:"
  },
  "9": {
    "John Trapp": "Clothed in their robes. ] And as the Septuagint have it, \u03b5\u03bd\u03bf\u03c0\u03bb\u03bf\u03b9 , in their arms, that they might provoke the people to take up arms.\nVer.\n9. Clothed in their robes.] And as the Septuagint have it, \u03b5\u03bd\u03bf\u03c0\u03bb\u03bf\u03b9, in their arms, that they might provoke the people to take up arms.\nVer."
  },
  "11": {
    "John Trapp": "And all the prophets prophesied. ] See #1Ki 22:12 . With as much confidence as Jesuits offer to pawn their souls for the truth of their assertions, and tell us, that if we be not damned, they will be damned for us. Event, the master of fools, confuted these bold affirmers.\nVer.\n11. And all the prophets prophesied.] See #1Ki 22:"
  },
  "20": {
    "John Trapp": "And there came out a spirit. ] The Rabbis fable that this was Naboth\u2019s ghost, who to be revenged on Ahab, thus offereth his service. In times of Popery, devils came saying that they were the souls of such and such dead persons; and desired to be set free from the pains of purgatory, &amp;c.\nVer.\n20. And there came out a spirit.] The Rabbis fable that this was Naboth\u2019s ghost, who to be revenged on Ahab, thus offereth his service. In times of Popery, devils came saying that they were the souls of such and such dead persons; and desired to be set free from the pains of purgatory, &c.\nVer."
  },
  "23": {
    "John Trapp": "And smote Micaiah. ] To do this in open court, and in such a presence, was great impudency; besides the violence, which yet is usually offered to Christ\u2019s servants, when other arguments are wanting. Argumenta sua formant in Barbara et Ferio, as one saith wittily. If Micaiah should have smitten Zedekiah, there would have been somewhat to do. But some may better steal a horse, than others look over the hedge.\nVer.\n23. And smote Micaiah.] To do this in open court, and in such a presence, was great impudency; besides the violence, which yet is usually offered to Christ\u2019s servants, when other arguments are wanting. Argumenta sua formant in Barbara et Ferio, as one saith wittily. If Micaiah should have smitten Zedekiah, there would have been somewhat to do. But some may better steal a horse, than others look over the hedge.\nVer."
  },
  "29": {
    "John Trapp": "But put thou on thy robes. ] As if you were the general of both armies. Ahab pretended herein to honour Jehoshaphat, but intended to save himself, and to elude Micaiah\u2019s prophecy.\nVer.\n29. But put thou on thy robes.] As if you were the general of both armies. Ahab pretended herein to honour Jehoshaphat, but intended to save himself, and to elude Micaiah\u2019s prophecy.\nVer."
  },
  "31": {
    "John Trapp": "Therefore they compassed about him. ] This great strait Jehoshaphat cast himseff into; as likewise the valiant Hunniades did, at the battle of Varna, where he was worsted, and afterwards taken prisoner by Dracula, for joining with that perjured Popish king of Hungary. And the Lord helped him. ] See #1Ki 22:32 , where yet this precious passage is not; but is here added by the penman of this book, who relateth things formerly set down, but oft with usury.\nVer.\n31. Therefore they compassed about him.] This great strait Jehoshaphat cast himseff into; as likewise the valiant Hunniades did, at the battle of Varna, where he was worsted, and afterwards taken prisoner by Dracula, for joining with that perjured Popish king of Hungary. And the Lord helped him.] See #1Ki 22:32, where yet this precious passage is not; but is here added by the penman of this book, who relateth things formerly set down, but oft with usury.\nVer."
  },
  "33": {
    "John Trapp": "Between the joints of the harness. ] The hand of Heaven carrying the arrow to that very place. As when God will save a man, a book in his bosom, the money in his purse, the buckle of his girdle shall preserve him from the deadly thrust, or shot. For I am wounded. ] Heb., I am sick, or weary. Perhaps he would have concealed his deadly wound from his chariot man; but \u201c \u0395\u03c5\u03c1\u03b5 \u03a6\u03b5\u03bf\u03c2 \u03c4\u03bf\u03bd \u03b1\u03bb\u03b9\u03c4\u03c1\u03bf\u03bd. \u201d His \"sin had now found him out\"; and, as stout hearted as he was, death seized him. For,\nVer.\n33. Between the joints of the harness.] The hand of Heaven carrying the arrow to that very place. As when God will save a man, a book in his bosom, the money in his purse, the buckle of his girdle shall preserve him from the deadly thrust, or shot. For I am wounded.] Heb., I am sick, or weary. Perhaps he would have concealed his deadly wound from his chariot man; but \u201c\u0395\u03c5\u03c1\u03b5 \u03a6\u03b5\u03bf\u03c2 \u03c4\u03bf\u03bd \u03b1\u03bb\u03b9\u03c4\u03c1\u03bf\u03bd.\u201d His \"sin had now found him out\"; and, as stout hearted as he was, death seized him. For,\nVer."
  },
  "34": {
    "John Trapp": "About the time of the sun going down he died. ] And so proved that a whole council\u2014of false prophets especially\u2014may err. Ahab might now have sent for Zedekiah, with his fellows, as Rodulphus Suevus did for the Popish bishops, who had put him on to take up arms against his master, the emperor, complaining of them at his death, that they had deceived him to his destruction, with the Popes, \"Petra dedit Petro, Petrus diadems Rodulpho.\"\n34. About the time of the sun going down he died.] And so proved that a whole council\u2014of false prophets especially\u2014may err. Ahab might now have sent for Zedekiah, with his fellows, as Rodulphus Suevus did for the Popish bishops, who had put him on to take up arms against his master, the emperor, complaining of them at his death, that they had deceived him to his destruction, with the Popes, \"Petra dedit Petro, Petrus diadems Rodulpho.\""
  }
});
