bible_loader.load_commentary(19, 74, {
  "10": {
    "Commentary Vol. 154": "The kings of Tarshish and of the isles shall bring presents, etc.] Tarshish either signifies the sea, as it is sometimes rendered in the Targum; and then the sense is, the kings of the sea, that is, of the islands of the sea, as it follows, shall be subject to the kingdom of Christ; and, as a token of it, bring presents to him, as the Moabites and Syrians did to David `[char_David_Rut_4]`, and as [v_2Sa_8_2] several nations and kings did to Solomon `[char_Solomon_Ref]`, (<100802>2 Samuel 8:2 <110421>1 Kings 4:21); or it designs a large country inhabited by the Celtae f989, and so is distinct from the islands; and then the sense is, that kings, both of the continent, and of the islands of the sea, shall do homage to the Messiah; and the kings of Sheba and Seba shall offer gifts; the Septuagint, Vulgate Latin, Ethiopic, and Arabic versions, render it, \u201cthe kings of the Arabians and Saba\u201d; and so Apollinarius, the Arabians, and Sabeans, these being places in Arabia Felix and Petraea f990: this will be fulfilled when the kings of the earth shall bring their honour and glory into the New Jerusalem, [v_Rev_21_24] (<662124>Revelation 21:24). This, and the preceding verse, are interpreted of the Messiah by the ancient Jews f991; who say f992, that all the gifts that Jacob `[char_Jacob_Ref]` their father gave to Esau, the nations of the world shall return them to the King Messiah in time to come, according to the sense of these words; where it is not written \u201cthey shall bring\u201d; but why\u00e7y f993, \u201cthey shall return [presents]\u201d. 803\nVer."
  },
  "11": {
    "Commentary Vol. 154": "Yea, all kings shall fall down before him, etc.] Or worship him; not with a civil, but religious worship; for such worship is due to Christ, he being God equal with the Father, and so to be equally honoured; the Creator of all things, the Redeemer of his people, Head and Lord of the church, and whom the angels adore; every part of worship is to be given him; internal, which lies in the exercise of faith, hope, love, fear, etc. and external, which consists of prayer to him, praise of him, preaching in his name, and the administration of ordinances; and this worship is to be performed in the same manner as to the Father, in spirit and in truth, in righteousness and holiness, with reverence and godly fear. This is to be understood, either literally of the kings of the earth, and which will have its [v_Isa_49_23] full accomplishment in the latter day; (see <234923>Isaiah `[char_Isaiah_Gen_26]` 49:23 60:3,11,16); or mystically of such who are made kings unto God the Father by Christ; who reign spiritually now, through the power of divine grace in their hearts; have the honour, riches, and attendance of kings, and a crown and kingdom prepared for them; and shall reign with Christ on earth, though under him, at whose feet they cast their crowns: all this shows the dignity of Christ\u2019s person and office; that he is the Prince of the kings of the earth, the firstborn of God, whom he has made higher than they, and King of kings, and Lord of lords; whose princes, and all whose subjects, are altogether kings. This passage is allowed to belong to the Messiah, both by ancient and modern Jews f994; and indeed it never was true of Solomon `[char_Solomon_Ref]`, nor of any other; all nations shall serve him; which will be in the latter day; (see <230202>Isaiah `[char_Isaiah_Gen_26]` [v_Rev_11_15] 2:2 <661115>Revelation 11:15 15:4); the Jews say f995, that in the world to come, or the times of the Messiah, all the Gentiles shall be voluntary proselytes.\nVer."
  },
  "12": {
    "Commentary Vol. 154": "For he shall deliver the needy when he crieth, etc.] Such as are not only in want, but are sensible of it, see their need of Christ and his righteousness, and salvation by him, and cry to him for the same, under a sense of their misery and danger; these he delivers out of all their troubles, and out of the hands of all their enemies, and supplies all their need; the poor also; the poor in spirit; who acknowledge their spiritual poverty, and apply to him for the true riches; to these he gives gold tried in the fire, that they may be rich; he gives them grace here, and glory hereafter; and [him] that hath no helper; that is in an helpless condition; can neither help himself, nor can any creature, angel or man, give him any help: but this being laid on Christ, and found in him, is given to him, whereby he is 804 delivered out of a miserable state into a very comfortable and happy one; and such humane, kind, and tender regard to the needy, poor, and helpless, in this great King spoken of, is what engages to a cheerful subjection to him, and worship and reverence of him; more of which is expressed in the following verses, as the reason of the great esteem he should be had in.\nVer."
  },
  "13": {
    "Commentary Vol. 154": "He shall spare the poor and needy, etc.] Pity them, have mercy and compassion on them, and sympathize with them; such an one is Christ, a merciful King, as well as High Priest, who is touched with a feeling of his people\u2019s infirmities, and who in his love and pity has redeemed them; and shall save the souls of the needy; not to the exclusion of their bodies, which are also his care and charge, are bought with his blood, are preserved by him, will be raised from the dead, and made like his glorious body; but souls are mentioned as being the most excellent part of man, and which having sinned, are liable to damnation and the second death; and are therefore the special objects of redemption and salvation; these are saved by him from all their sins, and from wrath to come they deserve; hence his name is called \u201cJesus `[char_Jesus_Ref]`\u201d, a Saviour.\nVer.",
    "Terence E. Fretheim, Thomas B. Slater": "642\n75:8\n208, 358\n78:38\n233\n78:42\n241\n78:65-66\n293"
  },
  "14": {
    "Commentary Vol. 154": "He shall redeem their soul from deceit and violence, etc.] From all the secret and open designs and efforts of their enemies; \u201cfrom deceit\u201d, and deceitfulness of sin and its lusts, so as that they shall not be finally hardened and destroyed by it; from the deceitfulness of the old serpent the devil, and all his cunning wiles and stratagems; and from false teachers, who lie in wait to deceive, and who would, if possible, deceive the very elect, but shall not: and from \u201cviolence\u201d; from the violent and tyrannical power of sin, so as that it shall not have the dominion over them; from the rage and fury of the men of the world, which is overcome by him; and from Satan, the strong man armed, who is stronger than they; from him the devouring lion, who will not be able to snatch them out of Christ\u2019s hands; and precious shall their blood be in his sight; so that he either prevents the shedding of it, or, when shed, avenges it; and dear are such persons to him; and very acceptable is the sacrifice of their lives for his sake, who have the [v_Psa_116_15] honour to suffer martyrdom for him; (see <19B615>"
  },
  "1": {
    "Commentary Vol. 154": "O God, why hast thou cast us off for ever? etc.]. This the church supposed because of the prevalence, oppression, and triumph of the enemy, because of the hardships and afflictions she laboured under, and because of the hidings of the face of God from her, which unbelief interpreted of a [v_Psa_77_7] casting off; (see <197707>"
  },
  "19": {
    "Commentary Vol. 154": "O deliver not the soul of thy turtledove, etc.] By which is meant the church, (see <220214>Song of Solomon `[char_Solomon_Ref]` 2:14 5:2 6:9), which is comparable to this creature for its cleanness and purity, for its amiableness and beauty, for its harmlessness and innocence, for its modesty and meekness, for its affection and chastity to its mate, for its mournful and bemoaning voice for the loss of it, for its being a timorous and fearful creature, a weak one, and exposed to the prey of others; all which is true of the church, and may be applied to it: the Targum is, \u201cdo not deliver the souls of them that teach thy law;\u201d the word having some affinity with \u201ctorah\u201d, the law; but Jarchi says, that Jonathan, in his Targum (which is not now extant) interprets it a turtle; the Syriac version, by the change of a letter, renders it, \u201cthe soul that confesseth thee\u201d: and the Arabic version, by a like change, and the addition of a letter, \u201cthe soul that knows thee\u201d; all which, indeed, is applicable to the church of God; but our version expresses the true sense of the word, with which agree Jarchi, Kimchi, Ben Melech, and others: and it is a prayer of the church for herself; that the life of her members, their corporeal life (for not the soul, the better part, and its eternal concerns, are meant, which are safe in Christ\u2019s hands), might not be delivered unto the multitude of the wicked, or \u201cto the beast\u201d f1061; to persecutors comparable to lions and bears, and particularly the Romish antichrist, often [v_Rev_11_8] called the beast in (<661108>Revelation 11:8 13:1,11 17:3), do not deliver \u201cto the people, who are like to the beasts of the field, the souls of, etc.:\u201d forget not the congregation of thy poor for ever; the church of God is a congregation of men gathered out of the world by effectual grace, and consists chiefly of such who are literally poor, and all of them are spiritually so, and are sensible of it; for the most part they are a poor and \u201cafflicted\u201d f1062 people, as the word may be also rendered, which the church is made up of; and may seem by themselves and others to be forgotten of God, when under divine desertions, or under afflictions, and immediate help is not given; but they are not forgotten, and still less for ever; (see [v_Isa_49_14] [v_Isa_49_15] [v_Isa_49_16] <234914>Isaiah `[char_Isaiah_Gen_26]` 49:14-16). 843\nVer."
  },
  "20": {
    "Commentary Vol. 154": "Have respect unto the covenant, etc.] The Targum adds, \u201cwhich thou hast made with our fathers;\u201d meaning not the covenant of works, which being broken, no good thing was to be expected from it, not liberty, life, nor eternal salvation, but all the reverse; but the covenant of grace, made with Christ before the world was, and made manifest to Adam `[char_Adam_Luk_3]`, to Noah `[char_Noah_Neh_6]`, to Abraham `[char_Abraham_Exo_17]`, Isaac, and Jacob `[char_Jacob_Ref]`, to David `[char_David_Rut_4]`, and others: this God has a respect unto, and does look unto it; he looks to the surety and Mediator of it, which is Christ, for the fulfilment of all conditions in it; to the promises of it, that they may be made good; to the blessings of it, that they be bestowed upon the persons to whom they belong; to the blood of it, for the delivering of the church\u2019s prisoners, and the salvation of them from wrath to come; and to the persons interested in it, that they be all called and brought safe to glory; and particularly to the things in it, respecting the glory of the church in the latter day, and increase of its members, and of its light, which seem chiefly designed here; and therefore it follows: for the dark places of the earth are full of the habitations of cruelty; many places of the earth are in gross darkness as to the knowledge of spiritual and divine things; even all those places which are inhabited by Pagans, Mahometans, and Papists, which make a great part of the globe; and in these dark places cruelty reigns, and especially in the antichristian states; wherefore the church pleads the covenant of God and his promises, that he would send forth his light and his truth, and cover the earth with the knowledge of the Lord, which is now covered with gross darkness, and under the tyranny and oppression of the man of sin.\nVer."
  },
  "21": {
    "Commentary Vol. 154": "O let not the oppressed return ashamed, etc.] From the throne of grace, not having an answer of their prayer, but still continuing under the oppressions of their enemies: let the poor and needy praise thy name; let them have occasion for it, by the destruction of their enemies, and their deliverance from them, as they [v_Rev_19_1] will have ere long; (see <661901>Revelation 19:1,2).\nVer."
  },
  "22": {
    "Commentary Vol. 154": "Arise, O God, plead thine own cause, etc.] The `[group_Word_Luk_1]` church\u2019s cause being the cause of God; and therefore she desires that he would arise and exert himself, and take vengeance on his and her enemies: this is an interesting argument, and a forcible one: 844 remember how the foolish man reproacheth thee daily; this being so [v_Psa_74_10] frequently repeated, as in (<197410>",
    "Commentary Vol. 155": "Gejerus Ft417 -- \u201c----pura cum veste venito, et manibus puris sumite fontis aquam, nunc lavabo ut rem divinam faciam\u201d, Tibull. l. 2. eleg."
  },
  "23": {
    "Commentary Vol. 154": "Forget not the voice of thine enemies, etc.] Their roaring in the [v_Psa_74_4] midst of the sanctuary and the congregation, (<197404>"
  },
  "2": {
    "Commentary Vol. 154": "The `[object_Temple_Hag_2]` dead bodies of thy servants have they given to be meat unto the fowls of the heaven, etc.] For such there were, both at the time of the Babylonish captivity, and in the times of Antiochus, who were good men, and served the Lord, and yet suffered in the common calamity. Nicanor, a general of Demetrius, in the time of the Maccabees, seems to have been guilty of such a fact as this, since, when he was slain, his tongue was given in pieces to the fowls, and the reward of his madness was hung up before the temple, as in the Apocrypha: \u201cAnd when he had cut out the tongue of that ungodly Nicanor, he commanded that they should give it by pieces unto the fowls, and hang up the reward of his madness before the temple.\u201d (2 Maccabees 15:33) the flesh of thy saints unto the beasts of the earth; this clause and the following verse are applied to a case in the times of the Maccabees, when sixty men of the Assideans were slain, religious, devout, and holy men, so called from the very word here translated \u201csaints\u201d; \u201cNow the Assideans were the first among the children of Israel that sought peace of them:\u201d (1 Maccabees 7:13) \u201cThe flesh of thy saints have they cast out, and their blood have they shed round about Jerusalem, and there was none to bury them.\u201d (1 Maccabees 7:17)\nVer."
  },
  "3": {
    "Commentary Vol. 154": "Their blood have they shed like water round about Jerusalem, etc.] Without any concern of mind, or remorse of conscience; without any fear of God or man; as if it had been so much water only; and this they shed in great abundance: from the Apocrypha: \u201cAnd when he had taken all away, he went into his own land, having made a great massacre, and spoken very proudly.\u201d (1 Maccabees 1:24) \u201cAnd spake peaceable words unto them, but all was deceit: for when they had given him credence, he fell suddenly upon the city, 917 and smote it very sore, and destroyed much people of Israel.\u201d (1 Maccabees 1:30) \u201cThus they shed innocent blood on every side of the sanctuary, and defiled it:\u201d (1 Maccabees 1:37) \u201cSo they rose up against them in battle on the sabbath, and they slew them, with their wives and children and their cattle, to the number of a thousand people.\u201d (1 Maccabees 2:38) in like manner the blood of the saints has been shed by the antichristian beast of Rome, for which he and his followers will be righteously [v_Rev_17_6] retaliated, (<661706>Revelation 17:6 18:24 16:6) and there was none to bury them: either the number of the slain was so great, that there were not left enough to bury the dead, or they that did remain were not suffered to do it; this will be the case of the two witnesses, [v_Rev_11_7] [v_Rev_11_8] [v_Rev_11_9] when slain, (<661107>Revelation 11:7-9).\nVer.",
    "Commentary Vol. 155": "Ft371 -- Vespes, p. 473, 516,"
  },
  "4": {
    "Commentary Vol. 154": "We are become a reproach to our neighbours, etc.] That is, those that remained; so the Jews were to the Edomites, especially at the time of [v_Psa_137_7] the Babylonish captivity, (<19D707>",
    "Commentary Vol. 155": "Enter into his gates with thanksgiving, etc.] The same with the gates of Zion, loved by the Lord more than all the dwellings of Jacob `[char_Jacob_Ref]`; the gates of Jerusalem, within which the feet of the saints stand with pleasure; the gates of Wisdom, or Christ, where his followers watch and wait; the gates into his house, the church, and the public ordinances of it, to be entered into with thankfulness for all mercies, temporal and spiritual; for the Gospel, and Gospel opportunities and ordinances: and into his courts with praise; with the sacrifice of praise, as in (<199608>Psalm [v_Psa_65_4] 96:8), of these courts, (see <196504>",
    "Terence E. Fretheim, Thomas B. Slater": "7\n318\n74:4-11\n644"
  }
});
