bible_loader.load_commentary(19, 107, {
  "1": {
    "Commentary Vol. 155": "O give thanks unto the Lord, etc.] As all men should do, at all times and for all things; the psalm begins as the former does, and gives the same reasons for thanksgiving. For he is good; and does good, and is the author of all good. For his mercy endureth for ever; and men in every age are partakers of it.\nVer."
  },
  "2": {
    "Commentary Vol. 155": "Let the redeemed of the Lord say so, etc.] That the Lord is good, and his mercy everlasting; since their redemption is a proof of his 1257 goodness, and an instance of his mercy; this is not to be understood of the Israelites redeemed from Egyptian bondage, or from the Babylonish captivity, though they had abundant reason to say as above; but rather of all such who are delivered from any sort of slavery, bondage, and confinement; whether from the power of a disease, or from a prison, or from wicked and unreasonable men; and from captivity in an enemy\u2019s country, where they have been used very severely; and as the providence of God is concerned in all such deliverances, thanks should be given him: it seems best to understand it of those who are spiritually redeemed by [v_Isa_35_10] Christ, this phrase being frequently used of such, (<233510>Isaiah `[char_Isaiah_Gen_26]` 35:10 51:11 52:12), who may be said to be so, since Christ is the author of their redemption; they are redeemed, not by themselves, nor by any creature, but by the Lord; who being their God, and near kinsman, had a right to redeem them, and, being God, was able to do it, and who has effected it by his precious blood; so that he has a right unto them and a property in them, which this phrase also suggests; and for all which they have great reason to praise the Lord and his goodness, and sing the new song of redeeming love. Whom he hath redeemed from the hand of the enemy from all their sins which war against their souls; from Satan their implacable adversary, who is stronger than they; from the law, which curses and threatens them with damnation and death; from death itself, the last enemy, and indeed from the hand of all their enemies, be they who they may.\nVer."
  },
  "3": {
    "Commentary Vol. 155": "And gathered them out of the lands, etc.] This cannot have respect to the bringing of the children of Israel out of Egypt; for they were not then brought out of several countries, but from one land only: nor to the Babylonish captivity; for, though some might be gathered out of different provinces, yet not from east, west, north, and south, as here expressed. It best suits with the gathering of the redeemed in the effectual calling, and particularly the calling of the Gentiles in Gospel times; to which the title of the Syriac version before mentioned has respect. The elect of God are [v_Zec_10_8] gathered in consequence of being redeemed, (<381008>Zechariah 10:8), they are gathered out of the world, and from among the men of it; they are gathered to Christ, and by him; they are gathered into his churches, and to communion with them, and to a participation of all privileges and ordinances: and this is usually done by the ministering of the Gospel, which is sent into all the world for this purpose; and a distinguishing blessing of grace it is to be gathered out from the rest of the world, and favoured with such rich mercies. Such have reason to adore the grace of God, and to 1258 show forth his praise, who has called them by his grace, and separated them from others for himself. From the east and from the west, and from the north and from the south; or, \u201cfrom the sea\u201d f1537; the southern sea, as the Targum; or the Red sea, the Arabian or Persian sea. The elect of God, and redeemed of the Lord, lie in all parts of the world; and from thence they are gathered by the ministry of the word unto Christ: this was fulfilled in the first times of the Gospel, and [v_Isa_43_5] will be more so in the latter day; (see <234305>Isaiah `[char_Isaiah_Gen_26]` 43:5,6).\nVer."
  },
  "4": {
    "Commentary Vol. 155": "They wandered in the wilderness in a solitary way, etc.] Not the people of Israel, as the Targum. These seem not to be particularly intended, whatever allusion there may be to their passage through the wilderness to Canaan\u2019s land; but rather, in general, travellers through waste places, especially the wild deserts of Arabia; where the wind blowing the sand, covers the roads with it, so that frequently travellers lose their way, and wander about, till directed to it by one providence or another. Some compare this with the case of the Old Testament saints, mentioned in [v_Heb_11_37] (<581137>Hebrews 11:37,38) others with the church in the wilderness, and the [v_Rev_11_2] witnesses prophesying in sackcloth, (<661102>Revelation 11:2 12:14). But it is certain that the redeemed and gathered are here meant; and this fitly describes their case, before and at effectual calling: they are in the [v_Ezk_20_35] wilderness of the people, (<262035>Ezekiel 20:35), from whence they are gathered; are in a state of error and ignorance; are like straying sheep, gone out of the right way; and are as lost sheep, they have lost their way; and though there may be many ways that present unto them, and which they think bid fair to be the right way; yet the true way of peace, life, and salvation by Christ, they know not, while in a state of nature and unregeneracy; and when they come to be effectually called, they see themselves to be in a bewildered state and condition. They found no city to dwell in; nor even to call at or lodge in, for miles together; which is the case of travellers in some parts, particularly in the deserts of Arabia. Spiritual travellers find no settlement, rest, peace, joy, and comfort, but in Christ; nor any indeed in this world, and the things of [v_Heb_13_14] it; here they have no continuing city, (<581314>Hebrews 13:14).\nVer.",
    "Walter Brueggemann, Warren Carter": "32\n368"
  },
  "5": {
    "Commentary Vol. 155": "Hungry and thirsty, etc.] As travellers in deserts sometimes are; their provisions being spent they bring with them, and none to be had on the road; there being no inns to stop at, nor any sort of food to eat, nor springs of water to drink of. In such a condition are souls, when, like the 1259 prodigal, they come to themselves, and are thoroughly convinced of their state and condition by nature; they find themselves starving and famishing, and no provision to be had from themselves or the creature: they hunger after Christ, the bread of life, and thirst after his grace, the water of life, and the blessings of it; they hunger and thirst after his righteousness, and justification by it; after the pardon of their sins through his blood, and after salvation by him, and an interest in it; after more knowledge of him, and communion with him. Their soul fainted in them; for want of food and drink; as men do, in a spiritual sense, for want of Christ, the blessings of his grace, particularly salvation; for want of views of interest in it, of the joys and comforts of it; [v_Psa_119_81] (see <19B981>"
  },
  "7": {
    "Commentary Vol. 155": "And he led them forth by the right way, etc.] Thus God by his providence directs travellers that have lost their way, and puts them into the right way. There is no doubt a very great concern of Providence in such a case, and which ought to be acknowledged with thankfulness. And thus the Lord leads awakened and inquiring souls to the right way of salvation; to Christ, who is the way, the truth, and the life; and directs and enables them to believe in him, to walk by faith, and to continue to walk in him, as they have received him; and which is a plain and straight way, in which they shall not stumble; yea, in which men, though fools, shall not err, wander, or lose themselves: and though this way is attended with many 1260 afflictions and tribulations, and so may be said to be a narrow and a rough way; yet it is a right one, and a safe one, it brings at last to eternal life: the Syriac version renders it, \u201cby the way of truth\u201d. That they might go to a city of habitation; a city to dwell in; the Targum is, \u201cto Jerusalem, a city to dwell in:\u201d but any city nearest for travellers is here meant; and in a spiritual sense may be intended, either Christ, the city of refuge, where awakened sinners are directed to flee to, and where they find safety and plenty of provisions; or the church of God, the strong city, about which salvation is as walls and bulwarks; and to which they come when effectually called, and become citizens of it; or the New Jerusalem church state, in which the tabernacle of God will be, and he will dwell with men, and they with him; or the ultimate glory and happiness of the saints in heaven, that city which has foundations, whose builder and maker is God; in which are everlasting habitations, and mansions of peace and rest for the people of God to dwell in, after they have gone through their troublesome passage in this wilderness.\nVer."
  },
  "8": {
    "Commentary Vol. 155": "O that men would praise the Lord for his goodness, etc.] For his providential goodness, in providing food and drink for them, when fainting; in directing them to their right way, when they had lost it; and in bringing them safe to the place they were bound for: and particularly for his special grace and goodness, in redemption and effectual calling; for bringing out of a wilderness state and condition, and supplying them with all spiritual provisions, and putting them in the right way to eternal glory and happiness. And for his wonderful works to the children of men! as all the above things are wonderful ones, both in providence and grace. This verse is repeated at the close of each of the instances produced; in which the goodness of God appears to persons in distress, and who being delivered, ought to acknowledge it, and be thankful for it: or \u201cconfess\u201d: that is, declare to God his goodness, and to the children of men his wonderful works; so the Targum.\nVer.\n8. Fire, and hail, etc.] These, and what follow in this verse, are in the air, but are what are exhaled or drawn up from the earth or water; \u201cfire\u201d is lightning, which is very swift in its motion, and powerful in its effects; this is the fire which consumed Sodom and Gomorrah, and the cities of the plain; which in Elijah\u2019s time came down and destroyed the captains and 1667 their fifties; and which attended the Lord\u2019s appearance on Mount Sinai; when \u201cthe voice of his thunder was in the heaven, the lightnings lightened [v_Psa_77_18] the world, and the earth trembled and shook\u201d, (<197718>"
  },
  "9": {
    "Commentary Vol. 155": "For he satisfieth the longing soul, etc.] The soul that is hungry and thirsty, and longs for food and drink, when nature in such circumstances craves. And so such who long for Christ and his grace, for an interest in 1261 him, and fellowship with him, the Lord satisfies with these things, as with marrow and fatness. And filleth the hungry soul with goodness; with the goodness and fatness of his house; with good things; with the good things laid up in Christ and in the covenant; with the good things of the Gospel; with the grace and [v_Psa_65_4] goodness of God in Christ; (see <196504>\n9. Mountains, and all hills, etc.] Which are originally formed by the Lord, and set fast by his power and strength; these are the highest parts of the earth, and are very ornamental and useful; they include all in them and upon them, the trees and herbage that grow upon them, gold, silver, brass, and iron in them; all very beneficial to mankind, and afford matter of praise [v_Isa_55_12] to God for them; (see <235512>Isaiah `[char_Isaiah_Gen_26]` 55:12); 1668 fruitful trees, and all cedars; trees bearing fruit are the fig trees, pomegranates, vines, and olives, with which the land of Canaan abounded; and such as bear lemons, oranges, plums, pears, apples, cherries, etc. which produce fruit for the use, pleasure, and delight of man, and so a means of praising God: and \u201ccedars\u201d, the trees of the Lord which he hath planted; though they bear no fruit, yet very useful in building, and were of great service in the temple at Jerusalem; and which are put for all others of like [v_Psa_96_12] usefulness, and minister just occasion of praise; (see <199612>"
  },
  "16": {
    "Commentary Vol. 155": "For he hath broken the gates of brass, etc.] The prison doors made of brass, as sometimes of iron, for the security of the prisoners; (see [v_Act_12_10] <441210>Acts 12:10). And cut the bars of iron in sunder; with which they were barred and secured. Hyperbolical phrases these, as Kimchi, expressing how exceeding strong the prison doors were, and the impossibility of an escape out of them, unless the Lord had delivered them; but when he works, none 1264 can let; all obstructions are easily removed by him; which is the sense of the [v_Isa_45_2] words, (see <234502>Isaiah `[char_Isaiah_Gen_26]` 45:2). Vitringa, on (<661202>Revelation 12:2), interprets this of the subjection of the Roman emperors to the faith and obedience of Christ.\nVer."
  },
  "17": {
    "Commentary Vol. 155": "Fools, because of their transgression, etc.] Or, \u201cbecause of the way\u201d f1539 \u201cof it\u201d; their sinful course of life; for it is not for a single transgression they are afflicted, but for a continued series of sinning, which is a transgression of the law of God. By \u201cfools\u201d are meant not idiots, men devoid of common sense and natural understanding, but immoral persons; such who have no understanding of divine and spiritual things; are destitute of the fear of God, which is the beginning of wisdom; without the true knowledge of God himself; place their happiness in sensual enjoyments; seek only the gratification of their lust; scoff at religion, make a mock at sin, and have no concern about a future state, and the welfare of their immortal souls. And because of their iniquities, are afflicted; or \u201cafflict themselves\u201d, or \u201cfind themselves afflicted\u201d f1540; rather \u201cbring affliction on themselves\u201d f1541. Not that these are the only persons that are afflicted; for many truly wise, good, and gracious persons, have a large share of afflictions; though not in a way of punishment for sin, or in wrath and hot displeasure, but in a way of fatherly chastisement, and in love: nor are fools for the most part afflicted, nor so much as others; they are not in trouble and plagued as other men; which has been a stumbling to good men: however, sometimes they are afflicted in this life, and in a way of punishment for sin; and very often are but the more hardened by it; though to some it is an ordinance for good; they are awakened by it to a sense of sin, and acknowledgment of it, and to seek for pardoning grace and mercy. This is the \u201cthird\u201d instance of persons in distress calling on the Lord, and finding relief f1542, and being under obligation to praise him.\nVer.",
    "Walter Brueggemann, Warren Carter": "20\n428\n115:4-8\n483\n115:8\n480\n117:1\n335"
  },
  "18": {
    "Commentary Vol. 155": "Their soul abhorreth all manner of meat, etc.] Not only bread and common food, but dainty meat, the most delicious fare, (<183320>Job 33:20), in which they most delighted in time of health, and too much indulged themselves in; and by that means brought diseases upon them, which caused this loathing in them, as is common. Thus to those who are distempered with sin, whose taste is not changed, nor can it discern perverse things, the word of God, the Gospel of Christ, which is delicious 1265 food, is not relished by them; the doctrines of it are insipid things, they loath them as light bread, as the Israelites did the manna. And they draw near unto the gates of death; that is, the grave; the house appointed for all living; the dwelling place of men till the resurrection; and [v_Job_33_22] so is said to have gates and doors; (see <183322>Job 33:22 30:23) and men sometimes are brought so low by affliction as that they seem to be near to death, just upon the brink of eternity, ready to enter into the grave, and lie down among the dead.\nVer."
  },
  "19": {
    "Commentary Vol. 155": "Then they cry unto the Lord in their trouble, etc.] A time of affliction is a time of trouble, and a proper season for prayer; and by it persons are brought to the throne of grace, when humbled under the mighty hand of God, to seek for relief. Hezekiah in his affliction prayed to the Lord, though Asa sought to the physicians only, and not to the Lord; this is to be understood of such who are convinced of their folly, brought to a sense of sin and danger, and therefore cry to the Lord for his sparing mercy, and pardoning grace. And he saveth them out of their distresses: their afflictions, which were distressing to them, by removing their disorders and restoring them to health again; as follows.\nVer."
  },
  "20": {
    "Commentary Vol. 155": "He sent his word, and healed them, etc.] It was his will and pleasure they should be healed, and accordingly they were; he issued his orders for the removal of the affliction, and it was done; diseases are his servants, which come and go at his command; so Christ, in the days of his [v_Mat_8_3] flesh, healed by speaking a word, (<400803>Matthew 8:3,8). This is true of Christ the essential Word, who was sent in the fulness of time, and was made flesh and dwelt among men, and went about healing all manner of diseases among the people; and who is also the physician of souls who came with healing in his wings; that is, with pardon of sin, for which his blood was shed: he is the only physician, the skilful, universal, and infallible one, and does all freely, and in a most marvellous manner, by his stripes, blood and wounds, and by an application of these to diseased persons sensible of their case. It may also be applied to the word of the Gospel; the law is the means of wounding, it is the killing letter; the Gospel is the means of healing, the doctrines of it are the leaves of the tree of life, which are for the healing of the nations; it is the doctrine of remission of sins by the blood of Christ, and by it Christ speaks peace and pardon to wounded consciences. 1266 And delivered them from their destructions; from the destruction of the body, of the beauty and strength of it by diseases; restoring to health is a redeeming of the life from destruction; from the grave, the pit of corruption and destruction, so called because in it bodies corrupt, putrefy, and are destroyed by worms; and such who are savingly convinced of sin, and blessed with pardoning grace and mercy, are delivered from the everlasting destruction of body and soul in hell.\nVer."
  },
  "21": {
    "Commentary Vol. 155": "Oh that men would praise the Lord for his goodness, etc.] Both in restoring to bodily health, which is an instance of divine goodness; and in healing the diseases of the soul, or in the pardon of sin, which is according to the multitude of his mercies, and the riches of his grace. And for his wonderful works to the children of men; bodily health is sometimes restored in a wonderful manner, when all means used are without success, and the prescriptions of doctors fail; and pardon of sin is a wonder of grace now, and will be to all eternity; and for these things praise ought to be given to the Lord, and they should be declared to men for his glory.\nVer."
  },
  "22": {
    "Commentary Vol. 155": "And let them sacrifice the sacrifices of thanksgiving, etc.] Not legal sacrifices, but spiritual and evangelical ones, the sacrifices of praise and thankfulness which God has enjoined are well pleasing to him through Christ, glorify him, and are but our reasonable service; (see <581315>Hebrews 13:15). And declare his works with rejoicing: tell them to the children of men, what he has done for them, for soul and body; let them come to Zion with joy and everlasting joy on their heads; to the gates thereof, or to the public assemblies of the saints, and there declare what great things the Lord has done for them; and has had compassion upon them in healing their bodily diseases, and curing them of their soul maladies.\nVer."
  },
  "23": {
    "Commentary Vol. 155": "They that go down to the sea in ships, etc.] This is the fourth instance of persons in distress crying to the Lord for help, and, having it, are laid under obligation to praise him; the case of seafaring men: so the Targum introduces it, \u201cmariners that go down to the sea in ships;\u201d [v_Isa_42_10] the same form of expression as here is used in (<234210>Isaiah `[char_Isaiah_Gen_26]` 42:10). Some affirm the sea to be higher than the earth, but by this it should be lower; 1267 besides the earth is said to be founded on the seas, which suggests superiority; and all the rivers run into the sea, which supposes a declivity; but, be it so that it is higher than the earth, yet this phrase is to be justified by the shores being higher than the sea, from whence men go down to take shipping, as Kimchi observes; though Kimchi\u2019s father is of opinion that it respects persons going down into the ship, which is deep, as Jonah is said [v_Jon_1_3] to do, (Jon 1:3). That do business in great waters: which refers either to the steering and working of the ship, and everything relating to the management of the ropes and sails, and other affairs; and in a storm much business is done, all hands are employed: or else to the business they go to sea about, as catching fish, curing them, and carrying them to market; or else to traffic and merchandise of goods, they convey from place to place. The phrase is [v_Rev_18_17] much like that, \u201cas many as trade by sea\u201d, (<661817>Revelation 18:17).\nVer."
  },
  "24": {
    "Commentary Vol. 155": "These see the works of the Lord, etc.] In creation, the sea itself, its flux and reflux; the creatures in it, fishes of various forms and sizes: and in providence, in preserving ships and men in the most imminent danger, and even to a miracle; sometimes causing the wind to change or to subside in a moment, whereby deliverance is wrought. And his wonders in the deep; the strange and wonderful creatures that are in the deep waters of the sea, and to be seen nowhere else; and the amazing appearances of divine providence, in delivering when in the greatest distress, and none at hand to help, and all hope of salvation gone.\nVer."
  },
  "25": {
    "Commentary Vol. 155": "For he commandeth, and raiseth the stormy wind, etc.] Winds are not raised by men, nor by devils, nor by angels, but by the Lord himself; who has created them, holds them in his fist, brings them out of his treasures, and sends them forth to do his will; if he speaks the word, gives but the order, a storm arises at once, and executes what he pleases, [v_Psa_148_8] (<19E808>"
  }
});
